package com.bawaweb.model;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlReportAnswerSetValuesImpl extends EntityImpl {
    public static final int RAVID = 0;
    public static final int RAVRASID = 1;
    public static final int RAVANSWER = 2;
    public static final int RAVDISPLAYSEQ = 3;
    public static final int RAVASVID = 4;
    public static final int RAVDELETEYN = 5;
    public static final int BaWaWEBANSWERSETVALUES = 6;
    public static final int BaWaWEBREPORTANSWERSETS = 7;
    public static final int BaWaWEBSOURCEANSWERS = 8;
    public static final int BaWaWEBSOURCEMULTIANSWERS = 9;
    private static OtlReportAnswerSetValuesDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public OtlReportAnswerSetValuesImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (OtlReportAnswerSetValuesDefImpl)EntityDefImpl.findDefObject("com.bawaweb.model.OtlReportAnswerSetValues");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for RavId, using the alias name RavId
     */
    public Number getRavId() {
        return (Number)getAttributeInternal(RAVID);
    }

    /**Sets <code>value</code> as the attribute value for RavId
     */
    public void setRavId(Number value) {
        setAttributeInternal(RAVID, value);
    }

    /**Gets the attribute value for RavRasId, using the alias name RavRasId
     */
    public Number getRavRasId() {
        return (Number)getAttributeInternal(RAVRASID);
    }

    /**Sets <code>value</code> as the attribute value for RavRasId
     */
    public void setRavRasId(Number value) {
        setAttributeInternal(RAVRASID, value);
    }

    /**Gets the attribute value for RavAnswer, using the alias name RavAnswer
     */
    public String getRavAnswer() {
        return (String)getAttributeInternal(RAVANSWER);
    }

    /**Sets <code>value</code> as the attribute value for RavAnswer
     */
    public void setRavAnswer(String value) {
        setAttributeInternal(RAVANSWER, value);
    }

    /**Gets the attribute value for RavDisplaySeq, using the alias name RavDisplaySeq
     */
    public Number getRavDisplaySeq() {
        return (Number)getAttributeInternal(RAVDISPLAYSEQ);
    }

    /**Sets <code>value</code> as the attribute value for RavDisplaySeq
     */
    public void setRavDisplaySeq(Number value) {
        setAttributeInternal(RAVDISPLAYSEQ, value);
    }

    /**Gets the attribute value for RavAsvId, using the alias name RavAsvId
     */
    public Number getRavAsvId() {
        return (Number)getAttributeInternal(RAVASVID);
    }

    /**Sets <code>value</code> as the attribute value for RavAsvId
     */
    public void setRavAsvId(Number value) {
        setAttributeInternal(RAVASVID, value);
    }

    /**Gets the attribute value for RavDeleteYn, using the alias name RavDeleteYn
     */
    public String getRavDeleteYn() {
        return (String)getAttributeInternal(RAVDELETEYN);
    }

    /**Sets <code>value</code> as the attribute value for RavDeleteYn
     */
    public void setRavDeleteYn(String value) {
        setAttributeInternal(RAVDELETEYN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RAVID:
            return getRavId();
        case RAVRASID:
            return getRavRasId();
        case RAVANSWER:
            return getRavAnswer();
        case RAVDISPLAYSEQ:
            return getRavDisplaySeq();
        case RAVASVID:
            return getRavAsvId();
        case RAVDELETEYN:
            return getRavDeleteYn();
        case BaWaWEBSOURCEMULTIANSWERS:
            return getOtlSourceMultiAnswers();
        case BaWaWEBSOURCEANSWERS:
            return getOtlSourceAnswers();
        case BaWaWEBANSWERSETVALUES:
            return getOtlAnswerSetValues();
        case BaWaWEBREPORTANSWERSETS:
            return getOtlReportAnswerSets();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RAVID:
            setRavId((Number)value);
            return;
        case RAVRASID:
            setRavRasId((Number)value);
            return;
        case RAVANSWER:
            setRavAnswer((String)value);
            return;
        case RAVDISPLAYSEQ:
            setRavDisplaySeq((Number)value);
            return;
        case RAVASVID:
            setRavAsvId((Number)value);
            return;
        case RAVDELETEYN:
            setRavDeleteYn((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity OtlAnswerSetValuesImpl
     */
    public OtlAnswerSetValuesImpl getOtlAnswerSetValues() {
        return (OtlAnswerSetValuesImpl)getAttributeInternal(BaWaWEBANSWERSETVALUES);
    }

    /**Sets <code>value</code> as the associated entity OtlAnswerSetValuesImpl
     */
    public void setOtlAnswerSetValues(OtlAnswerSetValuesImpl value) {
        setAttributeInternal(BaWaWEBANSWERSETVALUES, value);
    }

    /**Gets the associated entity OtlReportAnswerSetsImpl
     */
    public OtlReportAnswerSetsImpl getOtlReportAnswerSets() {
        return (OtlReportAnswerSetsImpl)getAttributeInternal(BaWaWEBREPORTANSWERSETS);
    }

    /**Sets <code>value</code> as the associated entity OtlReportAnswerSetsImpl
     */
    public void setOtlReportAnswerSets(OtlReportAnswerSetsImpl value) {
        setAttributeInternal(BaWaWEBREPORTANSWERSETS, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getOtlSourceAnswers() {
        return (RowIterator)getAttributeInternal(BaWaWEBSOURCEANSWERS);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getOtlSourceMultiAnswers() {
        return (RowIterator)getAttributeInternal(BaWaWEBSOURCEMULTIANSWERS);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number ravId) {
        return new Key(new Object[]{ravId});
    }
}
