package com.bawaweb.model;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlReportAnswerSetsImpl extends EntityImpl {
    public static final int RASID = 0;
    public static final int RASRPRTID = 1;
    public static final int RASANSID = 2;
    public static final int RASNAME = 3;
    public static final int RASFRIDID = 4;
    public static final int RASORDERBYNAMEYN = 5;
    public static final int RASADDANSWERYN = 6;
    public static final int RASDELETEYN = 7;
    public static final int FRIDFIRMINDUSTRIES = 8;
    public static final int BaWaWEBANSWERSETS = 9;
    public static final int BaWaWEBREPORTANSWERSETVALUES = 10;
    public static final int RPRTREPORTS = 11;
    private static OtlReportAnswerSetsDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public OtlReportAnswerSetsImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (OtlReportAnswerSetsDefImpl)EntityDefImpl.findDefObject("com.bawaweb.model.OtlReportAnswerSets");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for RasId, using the alias name RasId
     */
    public Number getRasId() {
        return (Number)getAttributeInternal(RASID);
    }

    /**Sets <code>value</code> as the attribute value for RasId
     */
    public void setRasId(Number value) {
        setAttributeInternal(RASID, value);
    }

    /**Gets the attribute value for RasRprtId, using the alias name RasRprtId
     */
    public Number getRasRprtId() {
        return (Number)getAttributeInternal(RASRPRTID);
    }

    /**Sets <code>value</code> as the attribute value for RasRprtId
     */
    public void setRasRprtId(Number value) {
        setAttributeInternal(RASRPRTID, value);
    }

    /**Gets the attribute value for RasAnsId, using the alias name RasAnsId
     */
    public Number getRasAnsId() {
        return (Number)getAttributeInternal(RASANSID);
    }

    /**Sets <code>value</code> as the attribute value for RasAnsId
     */
    public void setRasAnsId(Number value) {
        setAttributeInternal(RASANSID, value);
    }

    /**Gets the attribute value for RasName, using the alias name RasName
     */
    public String getRasName() {
        return (String)getAttributeInternal(RASNAME);
    }

    /**Sets <code>value</code> as the attribute value for RasName
     */
    public void setRasName(String value) {
        setAttributeInternal(RASNAME, value);
    }

    /**Gets the attribute value for RasFridId, using the alias name RasFridId
     */
    public Number getRasFridId() {
        return (Number)getAttributeInternal(RASFRIDID);
    }

    /**Sets <code>value</code> as the attribute value for RasFridId
     */
    public void setRasFridId(Number value) {
        setAttributeInternal(RASFRIDID, value);
    }

    /**Gets the attribute value for RasOrderByNameYn, using the alias name RasOrderByNameYn
     */
    public String getRasOrderByNameYn() {
        return (String)getAttributeInternal(RASORDERBYNAMEYN);
    }

    /**Sets <code>value</code> as the attribute value for RasOrderByNameYn
     */
    public void setRasOrderByNameYn(String value) {
        setAttributeInternal(RASORDERBYNAMEYN, value);
    }

    /**Gets the attribute value for RasAddAnswerYn, using the alias name RasAddAnswerYn
     */
    public String getRasAddAnswerYn() {
        return (String)getAttributeInternal(RASADDANSWERYN);
    }

    /**Sets <code>value</code> as the attribute value for RasAddAnswerYn
     */
    public void setRasAddAnswerYn(String value) {
        setAttributeInternal(RASADDANSWERYN, value);
    }

    /**Gets the attribute value for RasDeleteYn, using the alias name RasDeleteYn
     */
    public String getRasDeleteYn() {
        return (String)getAttributeInternal(RASDELETEYN);
    }

    /**Sets <code>value</code> as the attribute value for RasDeleteYn
     */
    public void setRasDeleteYn(String value) {
        setAttributeInternal(RASDELETEYN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RASID:
            return getRasId();
        case RASRPRTID:
            return getRasRprtId();
        case RASANSID:
            return getRasAnsId();
        case RASNAME:
            return getRasName();
        case RASFRIDID:
            return getRasFridId();
        case RASORDERBYNAMEYN:
            return getRasOrderByNameYn();
        case RASADDANSWERYN:
            return getRasAddAnswerYn();
        case RASDELETEYN:
            return getRasDeleteYn();
        case BaWaWEBREPORTANSWERSETVALUES:
            return getOtlReportAnswerSetValues();
        case FRIDFIRMINDUSTRIES:
            return getFridFirmIndustries();
        case BaWaWEBANSWERSETS:
            return getOtlAnswerSets();
        case RPRTREPORTS:
            return getRprtReports();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RASID:
            setRasId((Number)value);
            return;
        case RASRPRTID:
            setRasRprtId((Number)value);
            return;
        case RASANSID:
            setRasAnsId((Number)value);
            return;
        case RASNAME:
            setRasName((String)value);
            return;
        case RASFRIDID:
            setRasFridId((Number)value);
            return;
        case RASORDERBYNAMEYN:
            setRasOrderByNameYn((String)value);
            return;
        case RASADDANSWERYN:
            setRasAddAnswerYn((String)value);
            return;
        case RASDELETEYN:
            setRasDeleteYn((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity FridFirmIndustriesImpl
     */
    public FridFirmIndustriesImpl getFridFirmIndustries() {
        return (FridFirmIndustriesImpl)getAttributeInternal(FRIDFIRMINDUSTRIES);
    }

    /**Sets <code>value</code> as the associated entity FridFirmIndustriesImpl
     */
    public void setFridFirmIndustries(FridFirmIndustriesImpl value) {
        setAttributeInternal(FRIDFIRMINDUSTRIES, value);
    }

    /**Gets the associated entity OtlAnswerSetsImpl
     */
    public OtlAnswerSetsImpl getOtlAnswerSets() {
        return (OtlAnswerSetsImpl)getAttributeInternal(BaWaWEBANSWERSETS);
    }

    /**Sets <code>value</code> as the associated entity OtlAnswerSetsImpl
     */
    public void setOtlAnswerSets(OtlAnswerSetsImpl value) {
        setAttributeInternal(BaWaWEBANSWERSETS, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getOtlReportAnswerSetValues() {
        return (RowIterator)getAttributeInternal(BaWaWEBREPORTANSWERSETVALUES);
    }

    /**Gets the associated entity RprtReportsImpl
     */
    public RprtReportsImpl getRprtReports() {
        return (RprtReportsImpl)getAttributeInternal(RPRTREPORTS);
    }

    /**Sets <code>value</code> as the associated entity RprtReportsImpl
     */
    public void setRprtReports(RprtReportsImpl value) {
        setAttributeInternal(RPRTREPORTS, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number rasId) {
        return new Key(new Object[]{rasId});
    }
}
