package com.bawaweb.model;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlRolesImpl extends EntityImpl {
    public static final int ROLID = 0;
    public static final int ROLNAME = 1;
    public static final int ROLSRCINDYN = 2;
    public static final int ROLRPRTINDYN = 3;
    public static final int ROLSRCRPRTYN = 4;
    public static final int ROLDISPLAYORDER = 5;
    public static final int BaWaWEBEMPLROLES = 6;
    private static OtlRolesDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public OtlRolesImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (OtlRolesDefImpl)EntityDefImpl.findDefObject("com.bawaweb.model.OtlRoles");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for RolId, using the alias name RolId
     */
    public Number getRolId() {
        return (Number)getAttributeInternal(ROLID);
    }

    /**Sets <code>value</code> as the attribute value for RolId
     */
    public void setRolId(Number value) {
        setAttributeInternal(ROLID, value);
    }

    /**Gets the attribute value for RolName, using the alias name RolName
     */
    public String getRolName() {
        return (String)getAttributeInternal(ROLNAME);
    }

    /**Sets <code>value</code> as the attribute value for RolName
     */
    public void setRolName(String value) {
        setAttributeInternal(ROLNAME, value);
    }

    /**Gets the attribute value for RolSrcIndYn, using the alias name RolSrcIndYn
     */
    public String getRolSrcIndYn() {
        return (String)getAttributeInternal(ROLSRCINDYN);
    }

    /**Sets <code>value</code> as the attribute value for RolSrcIndYn
     */
    public void setRolSrcIndYn(String value) {
        setAttributeInternal(ROLSRCINDYN, value);
    }

    /**Gets the attribute value for RolRprtIndYn, using the alias name RolRprtIndYn
     */
    public String getRolRprtIndYn() {
        return (String)getAttributeInternal(ROLRPRTINDYN);
    }

    /**Sets <code>value</code> as the attribute value for RolRprtIndYn
     */
    public void setRolRprtIndYn(String value) {
        setAttributeInternal(ROLRPRTINDYN, value);
    }

    /**Gets the attribute value for RolSrcRprtYn, using the alias name RolSrcRprtYn
     */
    public String getRolSrcRprtYn() {
        return (String)getAttributeInternal(ROLSRCRPRTYN);
    }

    /**Sets <code>value</code> as the attribute value for RolSrcRprtYn
     */
    public void setRolSrcRprtYn(String value) {
        setAttributeInternal(ROLSRCRPRTYN, value);
    }

    /**Gets the attribute value for RolDisplayOrder, using the alias name RolDisplayOrder
     */
    public Number getRolDisplayOrder() {
        return (Number)getAttributeInternal(ROLDISPLAYORDER);
    }

    /**Sets <code>value</code> as the attribute value for RolDisplayOrder
     */
    public void setRolDisplayOrder(Number value) {
        setAttributeInternal(ROLDISPLAYORDER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROLID:
            return getRolId();
        case ROLNAME:
            return getRolName();
        case ROLSRCINDYN:
            return getRolSrcIndYn();
        case ROLRPRTINDYN:
            return getRolRprtIndYn();
        case ROLSRCRPRTYN:
            return getRolSrcRprtYn();
        case ROLDISPLAYORDER:
            return getRolDisplayOrder();
        case BaWaWEBEMPLROLES:
            return getOtlEmplRoles();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROLID:
            setRolId((Number)value);
            return;
        case ROLNAME:
            setRolName((String)value);
            return;
        case ROLSRCINDYN:
            setRolSrcIndYn((String)value);
            return;
        case ROLRPRTINDYN:
            setRolRprtIndYn((String)value);
            return;
        case ROLSRCRPRTYN:
            setRolSrcRprtYn((String)value);
            return;
        case ROLDISPLAYORDER:
            setRolDisplayOrder((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getOtlEmplRoles() {
        return (RowIterator)getAttributeInternal(BaWaWEBEMPLROLES);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number rolId) {
        return new Key(new Object[]{rolId});
    }
}
