package com.bawaweb.views.gridcursors;

import com.bawaweb.model.EmplOtlEmployeesImpl;
import com.bawaweb.model.RprtReportsImpl;
import com.bawaweb.views.gridcursors.common.EditorInfoRow;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EditorInfoRowImpl extends ViewRowImpl implements EditorInfoRow {
    public static final int EMPLID = 0;
    public static final int EMPLINIT = 1;
    public static final int EMPLUSERID = 2;
    public static final int EMPLLNAME = 3;
    public static final int EMPLFNAME = 4;
    public static final int EMPLINITIAL = 5;
    public static final int DEPTID = 6;
    public static final int EMPLTITLE = 7;
    public static final int EMPLOFFICELOC = 8;
    public static final int EMPLDOB = 9;
    public static final int EMPLHIREDATE = 10;
    public static final int EMPLADDRESS = 11;
    public static final int EMPLCITY = 12;
    public static final int EMPLSTATE = 13;
    public static final int EMPLZIP = 14;
    public static final int EMPLCOUNTRY = 15;
    public static final int EMPLHOMEPHONE = 16;
    public static final int EMPLOFFICEPHONE = 17;
    public static final int EMPLINTEXTENSION = 18;
    public static final int EMPLOFFICEFAX = 19;
    public static final int EMPLEMAIL = 20;
    public static final int EMPLINTERNET = 21;
    public static final int EMPLNOTES = 22;
    public static final int EMPLREPTSTO = 23;
    public static final int EMPLDIRLISTING = 24;
    public static final int EMPLPASSWORD = 25;
    public static final int REGID = 26;
    public static final int RERGID = 27;
    public static final int ACGRID = 28;
    public static final int EMPLSTATUS = 29;
    public static final int EMPLIDHR = 30;

    /**This is the default constructor (do not remove)
     */
    public EditorInfoRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute EmplId
     */
    public Number getEmplId() {
        return (Number) getAttributeInternal(EMPLID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplId
     */
    public void setEmplId(Number value) {
        setAttributeInternal(EMPLID, value);
    }

    /**Gets the attribute value for the calculated attribute EmplInit
     */
    public String getEmplInit() {
        return (String) getAttributeInternal(EMPLINIT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplInit
     */
    public void setEmplInit(String value) {
        setAttributeInternal(EMPLINIT, value);
    }

    /**Gets the attribute value for the calculated attribute EmplUserid
     */
    public String getEmplUserid() {
        return (String) getAttributeInternal(EMPLUSERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplUserid
     */
    public void setEmplUserid(String value) {
        setAttributeInternal(EMPLUSERID, value);
    }

    /**Gets the attribute value for the calculated attribute EmplLname
     */
    public String getEmplLname() {
        return (String) getAttributeInternal(EMPLLNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplLname
     */
    public void setEmplLname(String value) {
        setAttributeInternal(EMPLLNAME, value);
    }

    /**Gets the attribute value for the calculated attribute EmplFname
     */
    public String getEmplFname() {
        return (String) getAttributeInternal(EMPLFNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplFname
     */
    public void setEmplFname(String value) {
        setAttributeInternal(EMPLFNAME, value);
    }

    /**Gets the attribute value for the calculated attribute EmplInitial
     */
    public String getEmplInitial() {
        return (String) getAttributeInternal(EMPLINITIAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplInitial
     */
    public void setEmplInitial(String value) {
        setAttributeInternal(EMPLINITIAL, value);
    }

    /**Gets the attribute value for the calculated attribute DeptId
     */
    public Number getDeptId() {
        return (Number) getAttributeInternal(DEPTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DeptId
     */
    public void setDeptId(Number value) {
        setAttributeInternal(DEPTID, value);
    }

    /**Gets the attribute value for the calculated attribute EmplTitle
     */
    public String getEmplTitle() {
        return (String) getAttributeInternal(EMPLTITLE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplTitle
     */
    public void setEmplTitle(String value) {
        setAttributeInternal(EMPLTITLE, value);
    }

    /**Gets the attribute value for the calculated attribute EmplOfficeLoc
     */
    public String getEmplOfficeLoc() {
        return (String) getAttributeInternal(EMPLOFFICELOC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplOfficeLoc
     */
    public void setEmplOfficeLoc(String value) {
        setAttributeInternal(EMPLOFFICELOC, value);
    }

    /**Gets the attribute value for the calculated attribute EmplDob
     */
    public Date getEmplDob() {
        return (Date) getAttributeInternal(EMPLDOB);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplDob
     */
    public void setEmplDob(Date value) {
        setAttributeInternal(EMPLDOB, value);
    }

    /**Gets the attribute value for the calculated attribute EmplHireDate
     */
    public Date getEmplHireDate() {
        return (Date) getAttributeInternal(EMPLHIREDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplHireDate
     */
    public void setEmplHireDate(Date value) {
        setAttributeInternal(EMPLHIREDATE, value);
    }

    /**Gets the attribute value for the calculated attribute EmplAddress
     */
    public String getEmplAddress() {
        return (String) getAttributeInternal(EMPLADDRESS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplAddress
     */
    public void setEmplAddress(String value) {
        setAttributeInternal(EMPLADDRESS, value);
    }

    /**Gets the attribute value for the calculated attribute EmplCity
     */
    public String getEmplCity() {
        return (String) getAttributeInternal(EMPLCITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplCity
     */
    public void setEmplCity(String value) {
        setAttributeInternal(EMPLCITY, value);
    }

    /**Gets the attribute value for the calculated attribute EmplState
     */
    public String getEmplState() {
        return (String) getAttributeInternal(EMPLSTATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplState
     */
    public void setEmplState(String value) {
        setAttributeInternal(EMPLSTATE, value);
    }

    /**Gets the attribute value for the calculated attribute EmplZip
     */
    public String getEmplZip() {
        return (String) getAttributeInternal(EMPLZIP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplZip
     */
    public void setEmplZip(String value) {
        setAttributeInternal(EMPLZIP, value);
    }

    /**Gets the attribute value for the calculated attribute EmplCountry
     */
    public String getEmplCountry() {
        return (String) getAttributeInternal(EMPLCOUNTRY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplCountry
     */
    public void setEmplCountry(String value) {
        setAttributeInternal(EMPLCOUNTRY, value);
    }

    /**Gets the attribute value for the calculated attribute EmplHomePhone
     */
    public String getEmplHomePhone() {
        return (String) getAttributeInternal(EMPLHOMEPHONE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplHomePhone
     */
    public void setEmplHomePhone(String value) {
        setAttributeInternal(EMPLHOMEPHONE, value);
    }

    /**Gets the attribute value for the calculated attribute EmplOfficePhone
     */
    public String getEmplOfficePhone() {
        return (String) getAttributeInternal(EMPLOFFICEPHONE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplOfficePhone
     */
    public void setEmplOfficePhone(String value) {
        setAttributeInternal(EMPLOFFICEPHONE, value);
    }

    /**Gets the attribute value for the calculated attribute EmplIntExtension
     */
    public String getEmplIntExtension() {
        return (String) getAttributeInternal(EMPLINTEXTENSION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplIntExtension
     */
    public void setEmplIntExtension(String value) {
        setAttributeInternal(EMPLINTEXTENSION, value);
    }

    /**Gets the attribute value for the calculated attribute EmplOfficeFax
     */
    public String getEmplOfficeFax() {
        return (String) getAttributeInternal(EMPLOFFICEFAX);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplOfficeFax
     */
    public void setEmplOfficeFax(String value) {
        setAttributeInternal(EMPLOFFICEFAX, value);
    }

    /**Gets the attribute value for the calculated attribute EmplEmail
     */
    public String getEmplEmail() {
        return (String) getAttributeInternal(EMPLEMAIL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplEmail
     */
    public void setEmplEmail(String value) {
        setAttributeInternal(EMPLEMAIL, value);
    }

    /**Gets the attribute value for the calculated attribute EmplInternet
     */
    public String getEmplInternet() {
        return (String) getAttributeInternal(EMPLINTERNET);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplInternet
     */
    public void setEmplInternet(String value) {
        setAttributeInternal(EMPLINTERNET, value);
    }

    /**Gets the attribute value for the calculated attribute EmplNotes
     */
    public String getEmplNotes() {
        return (String) getAttributeInternal(EMPLNOTES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplNotes
     */
    public void setEmplNotes(String value) {
        setAttributeInternal(EMPLNOTES, value);
    }

    /**Gets the attribute value for the calculated attribute EmplReptsTo
     */
    public Number getEmplReptsTo() {
        return (Number) getAttributeInternal(EMPLREPTSTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplReptsTo
     */
    public void setEmplReptsTo(Number value) {
        setAttributeInternal(EMPLREPTSTO, value);
    }

    /**Gets the attribute value for the calculated attribute EmplDirListing
     */
    public Number getEmplDirListing() {
        return (Number) getAttributeInternal(EMPLDIRLISTING);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplDirListing
     */
    public void setEmplDirListing(Number value) {
        setAttributeInternal(EMPLDIRLISTING, value);
    }

    /**Gets the attribute value for the calculated attribute EmplPassword
     */
    public String getEmplPassword() {
        return (String) getAttributeInternal(EMPLPASSWORD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplPassword
     */
    public void setEmplPassword(String value) {
        setAttributeInternal(EMPLPASSWORD, value);
    }

    /**Gets the attribute value for the calculated attribute RegId
     */
    public Number getRegId() {
        return (Number) getAttributeInternal(REGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RegId
     */
    public void setRegId(Number value) {
        setAttributeInternal(REGID, value);
    }

    /**Gets the attribute value for the calculated attribute RergId
     */
    public Number getRergId() {
        return (Number) getAttributeInternal(RERGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RergId
     */
    public void setRergId(Number value) {
        setAttributeInternal(RERGID, value);
    }

    /**Gets the attribute value for the calculated attribute AcgrId
     */
    public Number getAcgrId() {
        return (Number) getAttributeInternal(ACGRID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AcgrId
     */
    public void setAcgrId(Number value) {
        setAttributeInternal(ACGRID, value);
    }

    /**Gets the attribute value for the calculated attribute EmplStatus
     */
    public String getEmplStatus() {
        return (String) getAttributeInternal(EMPLSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplStatus
     */
    public void setEmplStatus(String value) {
        setAttributeInternal(EMPLSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute EmplIdHr
     */
    public Number getEmplIdHr() {
        return (Number) getAttributeInternal(EMPLIDHR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmplIdHr
     */
    public void setEmplIdHr(Number value) {
        setAttributeInternal(EMPLIDHR, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLID:
            return getEmplId();
        case EMPLINIT:
            return getEmplInit();
        case EMPLUSERID:
            return getEmplUserid();
        case EMPLLNAME:
            return getEmplLname();
        case EMPLFNAME:
            return getEmplFname();
        case EMPLINITIAL:
            return getEmplInitial();
        case DEPTID:
            return getDeptId();
        case EMPLTITLE:
            return getEmplTitle();
        case EMPLOFFICELOC:
            return getEmplOfficeLoc();
        case EMPLDOB:
            return getEmplDob();
        case EMPLHIREDATE:
            return getEmplHireDate();
        case EMPLADDRESS:
            return getEmplAddress();
        case EMPLCITY:
            return getEmplCity();
        case EMPLSTATE:
            return getEmplState();
        case EMPLZIP:
            return getEmplZip();
        case EMPLCOUNTRY:
            return getEmplCountry();
        case EMPLHOMEPHONE:
            return getEmplHomePhone();
        case EMPLOFFICEPHONE:
            return getEmplOfficePhone();
        case EMPLINTEXTENSION:
            return getEmplIntExtension();
        case EMPLOFFICEFAX:
            return getEmplOfficeFax();
        case EMPLEMAIL:
            return getEmplEmail();
        case EMPLINTERNET:
            return getEmplInternet();
        case EMPLNOTES:
            return getEmplNotes();
        case EMPLREPTSTO:
            return getEmplReptsTo();
        case EMPLDIRLISTING:
            return getEmplDirListing();
        case EMPLPASSWORD:
            return getEmplPassword();
        case REGID:
            return getRegId();
        case RERGID:
            return getRergId();
        case ACGRID:
            return getAcgrId();
        case EMPLSTATUS:
            return getEmplStatus();
        case EMPLIDHR:
            return getEmplIdHr();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLID:
            setEmplId((Number)value);
            return;
        case EMPLINIT:
            setEmplInit((String)value);
            return;
        case EMPLUSERID:
            setEmplUserid((String)value);
            return;
        case EMPLLNAME:
            setEmplLname((String)value);
            return;
        case EMPLFNAME:
            setEmplFname((String)value);
            return;
        case EMPLINITIAL:
            setEmplInitial((String)value);
            return;
        case DEPTID:
            setDeptId((Number)value);
            return;
        case EMPLTITLE:
            setEmplTitle((String)value);
            return;
        case EMPLOFFICELOC:
            setEmplOfficeLoc((String)value);
            return;
        case EMPLDOB:
            setEmplDob((Date)value);
            return;
        case EMPLHIREDATE:
            setEmplHireDate((Date)value);
            return;
        case EMPLADDRESS:
            setEmplAddress((String)value);
            return;
        case EMPLCITY:
            setEmplCity((String)value);
            return;
        case EMPLSTATE:
            setEmplState((String)value);
            return;
        case EMPLZIP:
            setEmplZip((String)value);
            return;
        case EMPLCOUNTRY:
            setEmplCountry((String)value);
            return;
        case EMPLHOMEPHONE:
            setEmplHomePhone((String)value);
            return;
        case EMPLOFFICEPHONE:
            setEmplOfficePhone((String)value);
            return;
        case EMPLINTEXTENSION:
            setEmplIntExtension((String)value);
            return;
        case EMPLOFFICEFAX:
            setEmplOfficeFax((String)value);
            return;
        case EMPLEMAIL:
            setEmplEmail((String)value);
            return;
        case EMPLINTERNET:
            setEmplInternet((String)value);
            return;
        case EMPLNOTES:
            setEmplNotes((String)value);
            return;
        case EMPLREPTSTO:
            setEmplReptsTo((Number)value);
            return;
        case EMPLDIRLISTING:
            setEmplDirListing((Number)value);
            return;
        case EMPLPASSWORD:
            setEmplPassword((String)value);
            return;
        case REGID:
            setRegId((Number)value);
            return;
        case RERGID:
            setRergId((Number)value);
            return;
        case ACGRID:
            setAcgrId((Number)value);
            return;
        case EMPLSTATUS:
            setEmplStatus((String)value);
            return;
        case EMPLIDHR:
            setEmplIdHr((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets EmplOtlEmployees entity object.
     */
    public EmplOtlEmployeesImpl getEmplOtlEmployees() {
        return (EmplOtlEmployeesImpl)getEntity(0);
    }

    /**Gets RprtReports entity object.
     */
    public RprtReportsImpl getRprtReports() {
        return (RprtReportsImpl)getEntity(1);
    }
}
