package com.bawaweb.views.gridcursors;

import com.bawaweb.model.OtlQuestionsImpl;
import com.bawaweb.model.OtlReportAnswerSetsImpl;
import com.bawaweb.model.OtlReportSortingCriteriaImpl;
import com.bawaweb.model.OtlSortingCriteriaImpl;
import com.bawaweb.views.gridcursors.common.QuestionsListRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QuestionsListRowImpl extends ViewRowImpl implements QuestionsListRow {
    public static final int QSTID = 0;
    public static final int QSTNUMBER = 1;
    public static final int ORDERBY1 = 2;
    public static final int NUMERICPART = 3;
    public static final int ALPHAPART = 4;
    public static final int QSTQUESTION = 5;
    public static final int QSTTYPE = 6;
    public static final int QSTMULTIANSWERS = 7;
    public static final int QSTQUESTIONHINT = 8;
    public static final int QSTTEXTREQUIREDYN = 9;
    public static final int QSTTEXTHINT = 10;
    public static final int QSTRASID = 11;
    public static final int RASFRIDID = 12;
    public static final int QSTTLYID = 13;
    public static final int NUMCOLS = 14;
    public static final int QSTANSID = 15;

    /**This is the default constructor (do not remove)
     */
    public QuestionsListRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute QstId
     */
    public Number getQstId() {
        return (Number) getAttributeInternal(QSTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstId
     */
    public void setQstId(Number value) {
        setAttributeInternal(QSTID, value);
    }

    /**Gets the attribute value for the calculated attribute QstNumber
     */
    public String getQstNumber() {
        return (String) getAttributeInternal(QSTNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstNumber
     */
    public void setQstNumber(String value) {
        setAttributeInternal(QSTNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute OrderBy1
     */
    public Number getOrderBy1() {
        return (Number) getAttributeInternal(ORDERBY1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrderBy1
     */
    public void setOrderBy1(Number value) {
        setAttributeInternal(ORDERBY1, value);
    }

    /**Gets the attribute value for the calculated attribute NumericPart
     */
    public Number getNumericPart() {
        return (Number) getAttributeInternal(NUMERICPART);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumericPart
     */
    public void setNumericPart(Number value) {
        setAttributeInternal(NUMERICPART, value);
    }

    /**Gets the attribute value for the calculated attribute AlphaPart
     */
    public String getAlphaPart() {
        return (String) getAttributeInternal(ALPHAPART);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AlphaPart
     */
    public void setAlphaPart(String value) {
        setAttributeInternal(ALPHAPART, value);
    }

    /**Gets the attribute value for the calculated attribute QstQuestion
     */
    public String getQstQuestion() {
        return (String) getAttributeInternal(QSTQUESTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstQuestion
     */
    public void setQstQuestion(String value) {
        setAttributeInternal(QSTQUESTION, value);
    }

    /**Gets the attribute value for the calculated attribute QstType
     */
    public String getQstType() {
        return (String) getAttributeInternal(QSTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstType
     */
    public void setQstType(String value) {
        setAttributeInternal(QSTTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute QstMultiAnswers
     */
    public Number getQstMultiAnswers() {
        return (Number) getAttributeInternal(QSTMULTIANSWERS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstMultiAnswers
     */
    public void setQstMultiAnswers(Number value) {
        setAttributeInternal(QSTMULTIANSWERS, value);
    }

    /**Gets the attribute value for the calculated attribute QstQuestionHint
     */
    public String getQstQuestionHint() {
        return (String) getAttributeInternal(QSTQUESTIONHINT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstQuestionHint
     */
    public void setQstQuestionHint(String value) {
        setAttributeInternal(QSTQUESTIONHINT, value);
    }

    /**Gets the attribute value for the calculated attribute QstTextRequiredYn
     */
    public String getQstTextRequiredYn() {
        return (String) getAttributeInternal(QSTTEXTREQUIREDYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstTextRequiredYn
     */
    public void setQstTextRequiredYn(String value) {
        setAttributeInternal(QSTTEXTREQUIREDYN, value);
    }

    /**Gets the attribute value for the calculated attribute QstTextHint
     */
    public String getQstTextHint() {
        return (String) getAttributeInternal(QSTTEXTHINT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstTextHint
     */
    public void setQstTextHint(String value) {
        setAttributeInternal(QSTTEXTHINT, value);
    }

    /**Gets the attribute value for the calculated attribute QstRasId
     */
    public Number getQstRasId() {
        return (Number) getAttributeInternal(QSTRASID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstRasId
     */
    public void setQstRasId(Number value) {
        setAttributeInternal(QSTRASID, value);
    }

    /**Gets the attribute value for the calculated attribute RasFridId
     */
    public Number getRasFridId() {
        return (Number) getAttributeInternal(RASFRIDID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RasFridId
     */
    public void setRasFridId(Number value) {
        setAttributeInternal(RASFRIDID, value);
    }

    /**Gets the attribute value for the calculated attribute QstTlyId
     */
    public Number getQstTlyId() {
        return (Number) getAttributeInternal(QSTTLYID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstTlyId
     */
    public void setQstTlyId(Number value) {
        setAttributeInternal(QSTTLYID, value);
    }

    /**Gets the attribute value for the calculated attribute NumCols
     */
    public Number getNumCols() {
        return (Number) getAttributeInternal(NUMCOLS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumCols
     */
    public void setNumCols(Number value) {
        setAttributeInternal(NUMCOLS, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case QSTID:
            return getQstId();
        case QSTNUMBER:
            return getQstNumber();
        case ORDERBY1:
            return getOrderBy1();
        case NUMERICPART:
            return getNumericPart();
        case ALPHAPART:
            return getAlphaPart();
        case QSTQUESTION:
            return getQstQuestion();
        case QSTTYPE:
            return getQstType();
        case QSTMULTIANSWERS:
            return getQstMultiAnswers();
        case QSTQUESTIONHINT:
            return getQstQuestionHint();
        case QSTTEXTREQUIREDYN:
            return getQstTextRequiredYn();
        case QSTTEXTHINT:
            return getQstTextHint();
        case QSTRASID:
            return getQstRasId();
        case RASFRIDID:
            return getRasFridId();
        case QSTTLYID:
            return getQstTlyId();
        case NUMCOLS:
            return getNumCols();
        case QSTANSID:
            return getQstAnsId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case QSTTLYID:
            setQstTlyId((Number)value);
            return;
        case QSTANSID:
            setQstAnsId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets OtlQuestions entity object.
     */
    public OtlQuestionsImpl getOtlQuestions() {
        return (OtlQuestionsImpl)getEntity(0);
    }

    /**Gets OtlReportAnswerSets entity object.
     */
    public OtlReportAnswerSetsImpl getOtlReportAnswerSets() {
        return (OtlReportAnswerSetsImpl)getEntity(1);
    }

    /**Gets OtlSortingCriteria entity object.
     */
    public OtlSortingCriteriaImpl getOtlSortingCriteria() {
        return (OtlSortingCriteriaImpl)getEntity(2);
    }

    /**Gets OtlReportSortingCriteria entity object.
     */
    public OtlReportSortingCriteriaImpl getOtlReportSortingCriteria() {
        return (OtlReportSortingCriteriaImpl)getEntity(3);
    }

    /**Gets the attribute value for the calculated attribute QstAnsId
     */
    public Number getQstAnsId() {
        return (Number) getAttributeInternal(QSTANSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstAnsId
     */
    public void setQstAnsId(Number value) {
        setAttributeInternal(QSTANSID, value);
    }
}
