package com.bawaweb.views.gridcursors;

import com.bawaweb.model.OtlEmplRolesImpl;
import com.bawaweb.model.OtlRolesImpl;
import com.bawaweb.views.gridcursors.common.RoleScopeRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RoleScopeRowImpl extends ViewRowImpl implements RoleScopeRow {


    public static final int ROLID = 0;
    public static final int ROLNAME = 1;
    public static final int ROLSRCINDYN = 2;
    public static final int ROLRPRTINDYN = 3;
    public static final int ROLSRCRPRTYN = 4;
    public static final int ROLDISPLAYORDER = 5;
    public static final int EMREMPLID = 6;
    public static final int EMRROLID = 7;
    public static final int Y = 8;

    /**This is the default constructor (do not remove)
     */
    public RoleScopeRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Y
     */
    public String getY() {
        return (String) getAttributeInternal(Y);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Y
     */
    public void setY(String value) {
        setAttributeInternal(Y, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROLID:
            return getRolId();
        case ROLNAME:
            return getRolName();
        case ROLSRCINDYN:
            return getRolSrcIndYn();
        case ROLRPRTINDYN:
            return getRolRprtIndYn();
        case ROLSRCRPRTYN:
            return getRolSrcRprtYn();
        case ROLDISPLAYORDER:
            return getRolDisplayOrder();
        case EMREMPLID:
            return getEmrEmplId();
        case EMRROLID:
            return getEmrRolId();
        case Y:
            return getY();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROLID:
            setRolId((Number)value);
            return;
        case ROLNAME:
            setRolName((String)value);
            return;
        case ROLSRCINDYN:
            setRolSrcIndYn((String)value);
            return;
        case ROLRPRTINDYN:
            setRolRprtIndYn((String)value);
            return;
        case ROLSRCRPRTYN:
            setRolSrcRprtYn((String)value);
            return;
        case ROLDISPLAYORDER:
            setRolDisplayOrder((Number)value);
            return;
        case EMREMPLID:
            setEmrEmplId((Number)value);
            return;
        case EMRROLID:
            setEmrRolId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets OtlRoles entity object.
     */
    public OtlRolesImpl getOtlRoles() {
        return (OtlRolesImpl)getEntity(0);
    }

    /**Gets OtlEmplRoles entity object.
     */
    public OtlEmplRolesImpl getOtlEmplRoles() {
        return (OtlEmplRolesImpl)getEntity(1);
    }

    /**Gets the attribute value for the calculated attribute RolId
     */
    public Number getRolId() {
        return (Number) getAttributeInternal(ROLID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RolId
     */
    public void setRolId(Number value) {
        setAttributeInternal(ROLID, value);
    }

    /**Gets the attribute value for the calculated attribute RolName
     */
    public String getRolName() {
        return (String) getAttributeInternal(ROLNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RolName
     */
    public void setRolName(String value) {
        setAttributeInternal(ROLNAME, value);
    }

    /**Gets the attribute value for the calculated attribute RolSrcIndYn
     */
    public String getRolSrcIndYn() {
        return (String) getAttributeInternal(ROLSRCINDYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RolSrcIndYn
     */
    public void setRolSrcIndYn(String value) {
        setAttributeInternal(ROLSRCINDYN, value);
    }

    /**Gets the attribute value for the calculated attribute RolRprtIndYn
     */
    public String getRolRprtIndYn() {
        return (String) getAttributeInternal(ROLRPRTINDYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RolRprtIndYn
     */
    public void setRolRprtIndYn(String value) {
        setAttributeInternal(ROLRPRTINDYN, value);
    }

    /**Gets the attribute value for the calculated attribute RolSrcRprtYn
     */
    public String getRolSrcRprtYn() {
        return (String) getAttributeInternal(ROLSRCRPRTYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RolSrcRprtYn
     */
    public void setRolSrcRprtYn(String value) {
        setAttributeInternal(ROLSRCRPRTYN, value);
    }

    /**Gets the attribute value for the calculated attribute RolDisplayOrder
     */
    public Number getRolDisplayOrder() {
        return (Number) getAttributeInternal(ROLDISPLAYORDER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RolDisplayOrder
     */
    public void setRolDisplayOrder(Number value) {
        setAttributeInternal(ROLDISPLAYORDER, value);
    }

    /**Gets the attribute value for the calculated attribute EmrEmplId
     */
    public Number getEmrEmplId() {
        return (Number) getAttributeInternal(EMREMPLID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmrEmplId
     */
    public void setEmrEmplId(Number value) {
        setAttributeInternal(EMREMPLID, value);
    }

    /**Gets the attribute value for the calculated attribute EmrRolId
     */
    public Number getEmrRolId() {
        return (Number) getAttributeInternal(EMRROLID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmrRolId
     */
    public void setEmrRolId(Number value) {
        setAttributeInternal(EMRROLID, value);
    }
}
