package com.bawaweb.views.gridcursors;

import com.bawaweb.model.OtlAnswerSetValuesImpl;
import com.bawaweb.model.OtlAnswerSetsImpl;
import com.bawaweb.model.OtlQuestionsImpl;
import com.bawaweb.model.OtlReportAnswerSetValuesImpl;
import com.bawaweb.model.OtlReportAnswerSetsImpl;

import com.bawaweb.views.gridcursors.common.SingleAnswerSetsRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SingleAnswerSetsRowImpl extends ViewRowImpl implements SingleAnswerSetsRow {
    public static final int RAVID = 0;
    public static final int RAVRASID = 1;
    public static final int RAVANSWER = 2;
    public static final int RAVDISPLAYSEQ = 3;
    public static final int RAVASVID = 4;
    public static final int RAVDELETEYN = 5;
    public static final int ANSID = 6;

    /**This is the default constructor (do not remove)
     */
    public SingleAnswerSetsRowImpl() {
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RAVID:
            return getRavId();
        case RAVRASID:
            return getRavRasId();
        case RAVANSWER:
            return getRavAnswer();
        case RAVDISPLAYSEQ:
            return getRavDisplaySeq();
        case RAVASVID:
            return getRavAsvId();
        case RAVDELETEYN:
            return getRavDeleteYn();
        case ANSID:
            return getAnsId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RAVID:
            setRavId((Number)value);
            return;
        case RAVRASID:
            setRavRasId((Number)value);
            return;
        case RAVANSWER:
            setRavAnswer((String)value);
            return;
        case RAVDISPLAYSEQ:
            setRavDisplaySeq((Number)value);
            return;
        case RAVASVID:
            setRavAsvId((Number)value);
            return;
        case RAVDELETEYN:
            setRavDeleteYn((String)value);
            return;
        case ANSID:
            setAnsId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets OtlQuestions entity object.
     */
    public OtlQuestionsImpl getOtlQuestions() {
        return (OtlQuestionsImpl)getEntity(3);
    }

    /**Gets the attribute value for the calculated attribute RavId
     */
    public Number getRavId() {
        return (Number) getAttributeInternal(RAVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavId
     */
    public void setRavId(Number value) {
        setAttributeInternal(RAVID, value);
    }

    /**Gets the attribute value for the calculated attribute RavRasId
     */
    public Number getRavRasId() {
        return (Number) getAttributeInternal(RAVRASID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavRasId
     */
    public void setRavRasId(Number value) {
        setAttributeInternal(RAVRASID, value);
    }

    /**Gets the attribute value for the calculated attribute RavAnswer
     */
    public String getRavAnswer() {
        return (String) getAttributeInternal(RAVANSWER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavAnswer
     */
    public void setRavAnswer(String value) {
        setAttributeInternal(RAVANSWER, value);
    }

    /**Gets the attribute value for the calculated attribute RavDisplaySeq
     */
    public Number getRavDisplaySeq() {
        return (Number) getAttributeInternal(RAVDISPLAYSEQ);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavDisplaySeq
     */
    public void setRavDisplaySeq(Number value) {
        setAttributeInternal(RAVDISPLAYSEQ, value);
    }

    /**Gets the attribute value for the calculated attribute RavAsvId
     */
    public Number getRavAsvId() {
        return (Number) getAttributeInternal(RAVASVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavAsvId
     */
    public void setRavAsvId(Number value) {
        setAttributeInternal(RAVASVID, value);
    }

    /**Gets the attribute value for the calculated attribute RavDeleteYn
     */
    public String getRavDeleteYn() {
        return (String) getAttributeInternal(RAVDELETEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavDeleteYn
     */
    public void setRavDeleteYn(String value) {
        setAttributeInternal(RAVDELETEYN, value);
    }

    /**Gets OtlReportAnswerSetValues entity object.
     */
    public OtlReportAnswerSetValuesImpl getOtlReportAnswerSetValues() {
        return (OtlReportAnswerSetValuesImpl)getEntity(1);
    }

    /**Gets the attribute value for the calculated attribute AnsId
     */
    public Number getAnsId() {
        return (Number) getAttributeInternal(ANSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AnsId
     */
    public void setAnsId(Number value) {
        setAttributeInternal(ANSID, value);
    }

    /**Gets OtlAnswerSets entity object.
     */
    public OtlAnswerSetsImpl getOtlAnswerSets() {
        return (OtlAnswerSetsImpl)getEntity(2);
    }
}
