package com.bawaweb.views.gridcursors;

import com.bawaweb.model.OtlMultiQuestionsImpl;
import com.bawaweb.model.OtlQuestionsImpl;
import com.bawaweb.model.OtlReportAnswerSetValuesImpl;
import com.bawaweb.model.OtlReportSourcesImpl;
import com.bawaweb.model.OtlSourceAnswersImpl;
import com.bawaweb.model.OtlSourceMultiAnswersImpl;
import com.bawaweb.model.RprtReportsImpl;
import com.bawaweb.views.gridcursors.common.SourceMultiAnswerSetsRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SourceMultiAnswerSetsRowImpl extends ViewRowImpl implements SourceMultiAnswerSetsRow {
    public static final int RAVID = 0;
    public static final int SRARAVID = 1;
    public static final int SMARAVID = 2;
    public static final int SRAID = 3;
    public static final int SMASRAID = 4;
    public static final int SRARPSID = 5;
    public static final int QMQID = 6;
    public static final int QMQNUMBER = 7;
    public static final int QMQTYPE = 8;
    public static final int QMQQSTID = 9;
    public static final int SRAQSTID = 10;
    public static final int ANSWER = 11;
    public static final int SRAANSWERTEXT = 12;
    public static final int SRACOLOR = 13;
    public static final int SRACOMMENT = 14;
    public static final int QSTTYPE = 15;
    public static final int RAVASVID = 16;
    public static final int SRAASVID = 17;
    public static final int SMAASVID = 18;
    public static final int SRAEXCLUDEYN = 19;
    public static final int SMAEXCLUDEYN = 20;
    public static final int RAVDISPLAYSEQ = 21;
    public static final int RAVDELETEYN = 22;
    public static final int SRAWEIGHTMULTIPLIER = 23;
    public static final int SMAWEIGHTMULTIPLIER = 24;

    /**This is the default constructor (do not remove)
     */
    public SourceMultiAnswerSetsRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RavId
     */
    public Number getRavId() {
        return (Number) getAttributeInternal(RAVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavId
     */
    public void setRavId(Number value) {
        setAttributeInternal(RAVID, value);
    }

    /**Gets the attribute value for the calculated attribute SraId
     */
    public Number getSraId() {
        return (Number) getAttributeInternal(SRAID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraId
     */
    public void setSraId(Number value) {
        setAttributeInternal(SRAID, value);
    }

    /**Gets the attribute value for the calculated attribute SmaSraId
     */
    public Number getSmaSraId() {
        return (Number) getAttributeInternal(SMASRAID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaSraId
     */
    public void setSmaSraId(Number value) {
        setAttributeInternal(SMASRAID, value);
    }

    /**Gets the attribute value for the calculated attribute SraRpsId
     */
    public Number getSraRpsId() {
        return (Number) getAttributeInternal(SRARPSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraRpsId
     */
    public void setSraRpsId(Number value) {
        setAttributeInternal(SRARPSID, value);
    }

    /**Gets the attribute value for the calculated attribute QmqId
     */
    public Number getQmqId() {
        return (Number) getAttributeInternal(QMQID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqId
     */
    public void setQmqId(Number value) {
        setAttributeInternal(QMQID, value);
    }

    /**Gets the attribute value for the calculated attribute QmqNumber
     */
    public String getQmqNumber() {
        return (String) getAttributeInternal(QMQNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqNumber
     */
    public void setQmqNumber(String value) {
        setAttributeInternal(QMQNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute QmqType
     */
    public String getQmqType() {
        return (String) getAttributeInternal(QMQTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqType
     */
    public void setQmqType(String value) {
        setAttributeInternal(QMQTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute QmqQstId
     */
    public Number getQmqQstId() {
        return (Number) getAttributeInternal(QMQQSTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqQstId
     */
    public void setQmqQstId(Number value) {
        setAttributeInternal(QMQQSTID, value);
    }

    /**Gets the attribute value for the calculated attribute Answer
     */
    public String getAnswer() {
        return (String) getAttributeInternal(ANSWER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Answer
     */
    public void setAnswer(String value) {
        setAttributeInternal(ANSWER, value);
    }

    /**Gets the attribute value for the calculated attribute SraAnswerText
     */
    public String getSraAnswerText() {
        return (String) getAttributeInternal(SRAANSWERTEXT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraAnswerText
     */
    public void setSraAnswerText(String value) {
        setAttributeInternal(SRAANSWERTEXT, value);
    }

    /**Gets the attribute value for the calculated attribute SraColor
     */
    public String getSraColor() {
        return (String) getAttributeInternal(SRACOLOR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraColor
     */
    public void setSraColor(String value) {
        setAttributeInternal(SRACOLOR, value);
    }

    /**Gets the attribute value for the calculated attribute SraComment
     */
    public String getSraComment() {
        return (String) getAttributeInternal(SRACOMMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraComment
     */
    public void setSraComment(String value) {
        setAttributeInternal(SRACOMMENT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RAVID:
            return getRavId();
        case SRARAVID:
            return getSraRavId();
        case SMARAVID:
            return getSmaRavId();
        case SRAID:
            return getSraId();
        case SMASRAID:
            return getSmaSraId();
        case SRARPSID:
            return getSraRpsId();
        case QMQID:
            return getQmqId();
        case QMQNUMBER:
            return getQmqNumber();
        case QMQTYPE:
            return getQmqType();
        case QMQQSTID:
            return getQmqQstId();
        case SRAQSTID:
            return getSraQstId();
        case ANSWER:
            return getAnswer();
        case SRAANSWERTEXT:
            return getSraAnswerText();
        case SRACOLOR:
            return getSraColor();
        case SRACOMMENT:
            return getSraComment();
        case QSTTYPE:
            return getQstType();
        case RAVASVID:
            return getRavAsvId();
        case SRAASVID:
            return getSraAsvId();
        case SMAASVID:
            return getSmaAsvId();
        case SRAEXCLUDEYN:
            return getSraExcludeYn();
        case SMAEXCLUDEYN:
            return getSmaExcludeYn();
        case RAVDISPLAYSEQ:
            return getRavDisplaySeq();
        case RAVDELETEYN:
            return getRavDeleteYn();
        case SRAWEIGHTMULTIPLIER:
            return getSraWeightMultiplier();
        case SMAWEIGHTMULTIPLIER:
            return getSmaWeightMultiplier();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RAVID:
            setRavId((Number)value);
            return;
        case SRARAVID:
            setSraRavId((Number)value);
            return;
        case SMARAVID:
            setSmaRavId((Number)value);
            return;
        case SRAID:
            setSraId((Number)value);
            return;
        case SMASRAID:
            setSmaSraId((Number)value);
            return;
        case SRARPSID:
            setSraRpsId((Number)value);
            return;
        case QMQID:
            setQmqId((Number)value);
            return;
        case QMQNUMBER:
            setQmqNumber((String)value);
            return;
        case QMQTYPE:
            setQmqType((String)value);
            return;
        case QMQQSTID:
            setQmqQstId((Number)value);
            return;
        case SRAQSTID:
            setSraQstId((Number)value);
            return;
        case ANSWER:
            setAnswer((String)value);
            return;
        case SRAANSWERTEXT:
            setSraAnswerText((String)value);
            return;
        case SRACOLOR:
            setSraColor((String)value);
            return;
        case SRACOMMENT:
            setSraComment((String)value);
            return;
        case QSTTYPE:
            setQstType((String)value);
            return;
        case RAVASVID:
            setRavAsvId((Number)value);
            return;
        case SRAASVID:
            setSraAsvId((Number)value);
            return;
        case SMAASVID:
            setSmaAsvId((Number)value);
            return;
        case SRAEXCLUDEYN:
            setSraExcludeYn((String)value);
            return;
        case SMAEXCLUDEYN:
            setSmaExcludeYn((String)value);
            return;
        case RAVDISPLAYSEQ:
            setRavDisplaySeq((Number)value);
            return;
        case RAVDELETEYN:
            setRavDeleteYn((String)value);
            return;
        case SRAWEIGHTMULTIPLIER:
            setSraWeightMultiplier((Number)value);
            return;
        case SMAWEIGHTMULTIPLIER:
            setSmaWeightMultiplier((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets OtlReportAnswerSetValues entity object.
     */
    public OtlReportAnswerSetValuesImpl getOtlReportAnswerSetValues() {
        return (OtlReportAnswerSetValuesImpl)getEntity(0);
    }

    /**Gets OtlMultiQuestions entity object.
     */
    public OtlMultiQuestionsImpl getOtlMultiQuestions() {
        return (OtlMultiQuestionsImpl)getEntity(1);
    }

    /**Gets OtlSourceMultiAnswers entity object.
     */
    public OtlSourceMultiAnswersImpl getOtlSourceMultiAnswers() {
        return (OtlSourceMultiAnswersImpl)getEntity(2);
    }

    /**Gets OtlSourceAnswers entity object.
     */
    public OtlSourceAnswersImpl getOtlSourceAnswers() {
        return (OtlSourceAnswersImpl)getEntity(3);
    }

    /**Gets RprtReports entity object.
     */
    public RprtReportsImpl getRprtReports() {
        return (RprtReportsImpl)getEntity(4);
    }

    /**Gets OtlReportSources entity object.
     */
    public OtlReportSourcesImpl getOtlReportSources() {
        return (OtlReportSourcesImpl)getEntity(5);
    }

    /**Gets the attribute value for the calculated attribute QstType
     */
    public String getQstType() {
        return (String) getAttributeInternal(QSTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QstType
     */
    public void setQstType(String value) {
        setAttributeInternal(QSTTYPE, value);
    }

    /**Gets OtlQuestions entity object.
     */
    public OtlQuestionsImpl getOtlQuestions() {
        return (OtlQuestionsImpl)getEntity(6);
    }


    /**Gets the attribute value for the calculated attribute SraRavId
     */
    public Number getSraRavId() {
        return (Number) getAttributeInternal(SRARAVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraRavId
     */
    public void setSraRavId(Number value) {
        setAttributeInternal(SRARAVID, value);
    }

    /**Gets the attribute value for the calculated attribute SmaRavId
     */
    public Number getSmaRavId() {
        return (Number) getAttributeInternal(SMARAVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaRavId
     */
    public void setSmaRavId(Number value) {
        setAttributeInternal(SMARAVID, value);
    }

    /**Gets the attribute value for the calculated attribute SraQstId
     */
    public Number getSraQstId() {
        return (Number) getAttributeInternal(SRAQSTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraQstId
     */
    public void setSraQstId(Number value) {
        setAttributeInternal(SRAQSTID, value);
    }

    /**Gets the attribute value for the calculated attribute RavAsvId
     */
    public Number getRavAsvId() {
        return (Number) getAttributeInternal(RAVASVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavAsvId
     */
    public void setRavAsvId(Number value) {
        setAttributeInternal(RAVASVID, value);
    }

    /**Gets the attribute value for the calculated attribute SraAsvId
     */
    public Number getSraAsvId() {
        return (Number) getAttributeInternal(SRAASVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraAsvId
     */
    public void setSraAsvId(Number value) {
        setAttributeInternal(SRAASVID, value);
    }

    /**Gets the attribute value for the calculated attribute SmaAsvId
     */
    public Number getSmaAsvId() {
        return (Number) getAttributeInternal(SMAASVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaAsvId
     */
    public void setSmaAsvId(Number value) {
        setAttributeInternal(SMAASVID, value);
    }

    /**Gets the attribute value for the calculated attribute SraExcludeYn
     */
    public String getSraExcludeYn() {
        return (String) getAttributeInternal(SRAEXCLUDEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraExcludeYn
     */
    public void setSraExcludeYn(String value) {
        setAttributeInternal(SRAEXCLUDEYN, value);
    }

    /**Gets the attribute value for the calculated attribute SmaExcludeYn
     */
    public String getSmaExcludeYn() {
        return (String) getAttributeInternal(SMAEXCLUDEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaExcludeYn
     */
    public void setSmaExcludeYn(String value) {
        setAttributeInternal(SMAEXCLUDEYN, value);
    }

    /**Gets the attribute value for the calculated attribute RavDisplaySeq
     */
    public Number getRavDisplaySeq() {
        return (Number) getAttributeInternal(RAVDISPLAYSEQ);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavDisplaySeq
     */
    public void setRavDisplaySeq(Number value) {
        setAttributeInternal(RAVDISPLAYSEQ, value);
    }

    /**Gets the attribute value for the calculated attribute RavDeleteYn
     */
    public String getRavDeleteYn() {
        return (String) getAttributeInternal(RAVDELETEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavDeleteYn
     */
    public void setRavDeleteYn(String value) {
        setAttributeInternal(RAVDELETEYN, value);
    }

    /**Gets the attribute value for the calculated attribute SraWeightMultiplier
     */
    public Number getSraWeightMultiplier() {
        return (Number) getAttributeInternal(SRAWEIGHTMULTIPLIER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraWeightMultiplier
     */
    public void setSraWeightMultiplier(Number value) {
        setAttributeInternal(SRAWEIGHTMULTIPLIER, value);
    }

    /**Gets the attribute value for the calculated attribute SmaWeightMultiplier
     */
    public Number getSmaWeightMultiplier() {
        return (Number) getAttributeInternal(SMAWEIGHTMULTIPLIER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaWeightMultiplier
     */
    public void setSmaWeightMultiplier(Number value) {
        setAttributeInternal(SMAWEIGHTMULTIPLIER, value);
    }
}
