package com.bawaweb.views.gridcursors.views;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllSourcesListViewDefImpl extends ViewDefImpl {
    public AllSourcesListViewDefImpl(String name) {
        super(name);
    }

    /**This is the default constructor (do not remove)
     */
    public AllSourcesListViewDefImpl() {
    }
}
