package com.bawaweb.views.gridcursors.views;


import com.bawaweb.model.viewobjects.QuestionListViewImpl;
import com.bawaweb.views.gridcursors.views.common.QuestionsListViewRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QuestionsListViewRowImpl extends ViewRowImpl implements QuestionsListViewRow {
    public static final int QSTID = 0;
    public static final int QSTNUMBER = 1;
    public static final int ORDERBY1 = 2;
    public static final int NUMERICPART = 3;
    public static final int ALPHAPART = 4;
    public static final int QSTQUESTION = 5;
    public static final int QSTTYPE = 6;
    public static final int QSTMULTIANSWERS = 7;
    public static final int QSTQUESTIONHINT = 8;
    public static final int QSTTEXTREQUIREDYN = 9;
    public static final int QSTTEXTHINT = 10;
    public static final int QSTRASID = 11;
    public static final int RASFRIDID = 12;
    public static final int QSTTLYID = 13;
    public static final int NUMCOLS = 14;
    public static final int QSTANSID = 15;
    public static final int RPRTID = 16;

    /**This is the default constructor (do not remove)
     */
    public QuestionsListViewRowImpl() {
    }

    /**Gets QuestionListView entity object.
     */
    public QuestionListViewImpl getQuestionListView() {
        return (QuestionListViewImpl)getEntity(0);
    }

    /**Gets the attribute value for QST_ID using the alias name QstId
     */
    public Number getQstId() {
        return (Number) getAttributeInternal(QSTID);
    }

    /**Sets <code>value</code> as attribute value for QST_ID using the alias name QstId
     */
    public void setQstId(Number value) {
        setAttributeInternal(QSTID, value);
    }

    /**Gets the attribute value for QST_NUMBER using the alias name QstNumber
     */
    public String getQstNumber() {
        return (String) getAttributeInternal(QSTNUMBER);
    }

    /**Sets <code>value</code> as attribute value for QST_NUMBER using the alias name QstNumber
     */
    public void setQstNumber(String value) {
        setAttributeInternal(QSTNUMBER, value);
    }

    /**Gets the attribute value for ORDER_BY using the alias name OrderBy1
     */
    public Number getOrderBy1() {
        return (Number) getAttributeInternal(ORDERBY1);
    }

    /**Sets <code>value</code> as attribute value for ORDER_BY using the alias name OrderBy1
     */
    public void setOrderBy1(Number value) {
        setAttributeInternal(ORDERBY1, value);
    }

    /**Gets the attribute value for NUMERIC_PART using the alias name NumericPart
     */
    public Number getNumericPart() {
        return (Number) getAttributeInternal(NUMERICPART);
    }

    /**Sets <code>value</code> as attribute value for NUMERIC_PART using the alias name NumericPart
     */
    public void setNumericPart(Number value) {
        setAttributeInternal(NUMERICPART, value);
    }

    /**Gets the attribute value for ALPHA_PART using the alias name AlphaPart
     */
    public String getAlphaPart() {
        return (String) getAttributeInternal(ALPHAPART);
    }

    /**Sets <code>value</code> as attribute value for ALPHA_PART using the alias name AlphaPart
     */
    public void setAlphaPart(String value) {
        setAttributeInternal(ALPHAPART, value);
    }

    /**Gets the attribute value for QST_QUESTION using the alias name QstQuestion
     */
    public String getQstQuestion() {
        return (String) getAttributeInternal(QSTQUESTION);
    }

    /**Sets <code>value</code> as attribute value for QST_QUESTION using the alias name QstQuestion
     */
    public void setQstQuestion(String value) {
        setAttributeInternal(QSTQUESTION, value);
    }

    /**Gets the attribute value for QST_TYPE using the alias name QstType
     */
    public String getQstType() {
        return (String) getAttributeInternal(QSTTYPE);
    }

    /**Sets <code>value</code> as attribute value for QST_TYPE using the alias name QstType
     */
    public void setQstType(String value) {
        setAttributeInternal(QSTTYPE, value);
    }

    /**Gets the attribute value for QST_MULTI_ANSWERS using the alias name QstMultiAnswers
     */
    public Number getQstMultiAnswers() {
        return (Number) getAttributeInternal(QSTMULTIANSWERS);
    }

    /**Sets <code>value</code> as attribute value for QST_MULTI_ANSWERS using the alias name QstMultiAnswers
     */
    public void setQstMultiAnswers(Number value) {
        setAttributeInternal(QSTMULTIANSWERS, value);
    }

    /**Gets the attribute value for QST_QUESTION_HINT using the alias name QstQuestionHint
     */
    public String getQstQuestionHint() {
        return (String) getAttributeInternal(QSTQUESTIONHINT);
    }

    /**Sets <code>value</code> as attribute value for QST_QUESTION_HINT using the alias name QstQuestionHint
     */
    public void setQstQuestionHint(String value) {
        setAttributeInternal(QSTQUESTIONHINT, value);
    }

    /**Gets the attribute value for QST_TEXT_REQUIRED_YN using the alias name QstTextRequiredYn
     */
    public String getQstTextRequiredYn() {
        return (String) getAttributeInternal(QSTTEXTREQUIREDYN);
    }

    /**Sets <code>value</code> as attribute value for QST_TEXT_REQUIRED_YN using the alias name QstTextRequiredYn
     */
    public void setQstTextRequiredYn(String value) {
        setAttributeInternal(QSTTEXTREQUIREDYN, value);
    }

    /**Gets the attribute value for QST_TEXT_HINT using the alias name QstTextHint
     */
    public String getQstTextHint() {
        return (String) getAttributeInternal(QSTTEXTHINT);
    }

    /**Sets <code>value</code> as attribute value for QST_TEXT_HINT using the alias name QstTextHint
     */
    public void setQstTextHint(String value) {
        setAttributeInternal(QSTTEXTHINT, value);
    }

    /**Gets the attribute value for QST_RAS_ID using the alias name QstRasId
     */
    public Number getQstRasId() {
        return (Number) getAttributeInternal(QSTRASID);
    }

    /**Sets <code>value</code> as attribute value for QST_RAS_ID using the alias name QstRasId
     */
    public void setQstRasId(Number value) {
        setAttributeInternal(QSTRASID, value);
    }

    /**Gets the attribute value for RAS_FRID_ID using the alias name RasFridId
     */
    public Number getRasFridId() {
        return (Number) getAttributeInternal(RASFRIDID);
    }

    /**Sets <code>value</code> as attribute value for RAS_FRID_ID using the alias name RasFridId
     */
    public void setRasFridId(Number value) {
        setAttributeInternal(RASFRIDID, value);
    }

    /**Gets the attribute value for QST_TLY_ID using the alias name QstTlyId
     */
    public Number getQstTlyId() {
        return (Number) getAttributeInternal(QSTTLYID);
    }

    /**Sets <code>value</code> as attribute value for QST_TLY_ID using the alias name QstTlyId
     */
    public void setQstTlyId(Number value) {
        setAttributeInternal(QSTTLYID, value);
    }

    /**Gets the attribute value for NUM_COLS using the alias name NumCols
     */
    public Number getNumCols() {
        return (Number) getAttributeInternal(NUMCOLS);
    }

    /**Sets <code>value</code> as attribute value for NUM_COLS using the alias name NumCols
     */
    public void setNumCols(Number value) {
        setAttributeInternal(NUMCOLS, value);
    }

    /**Gets the attribute value for QST_ANS_ID using the alias name QstAnsId
     */
    public Number getQstAnsId() {
        return (Number) getAttributeInternal(QSTANSID);
    }

    /**Sets <code>value</code> as attribute value for QST_ANS_ID using the alias name QstAnsId
     */
    public void setQstAnsId(Number value) {
        setAttributeInternal(QSTANSID, value);
    }

    /**Gets the attribute value for RPRT_ID using the alias name RprtId
     */
    public Number getRprtId() {
        return (Number) getAttributeInternal(RPRTID);
    }

    /**Sets <code>value</code> as attribute value for RPRT_ID using the alias name RprtId
     */
    public void setRprtId(Number value) {
        setAttributeInternal(RPRTID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case QSTID:
            return getQstId();
        case QSTNUMBER:
            return getQstNumber();
        case ORDERBY1:
            return getOrderBy1();
        case NUMERICPART:
            return getNumericPart();
        case ALPHAPART:
            return getAlphaPart();
        case QSTQUESTION:
            return getQstQuestion();
        case QSTTYPE:
            return getQstType();
        case QSTMULTIANSWERS:
            return getQstMultiAnswers();
        case QSTQUESTIONHINT:
            return getQstQuestionHint();
        case QSTTEXTREQUIREDYN:
            return getQstTextRequiredYn();
        case QSTTEXTHINT:
            return getQstTextHint();
        case QSTRASID:
            return getQstRasId();
        case RASFRIDID:
            return getRasFridId();
        case QSTTLYID:
            return getQstTlyId();
        case NUMCOLS:
            return getNumCols();
        case QSTANSID:
            return getQstAnsId();
        case RPRTID:
            return getRprtId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case QSTID:
            setQstId((Number)value);
            return;
        case QSTNUMBER:
            setQstNumber((String)value);
            return;
        case ORDERBY1:
            setOrderBy1((Number)value);
            return;
        case NUMERICPART:
            setNumericPart((Number)value);
            return;
        case ALPHAPART:
            setAlphaPart((String)value);
            return;
        case QSTQUESTION:
            setQstQuestion((String)value);
            return;
        case QSTTYPE:
            setQstType((String)value);
            return;
        case QSTMULTIANSWERS:
            setQstMultiAnswers((Number)value);
            return;
        case QSTQUESTIONHINT:
            setQstQuestionHint((String)value);
            return;
        case QSTTEXTREQUIREDYN:
            setQstTextRequiredYn((String)value);
            return;
        case QSTTEXTHINT:
            setQstTextHint((String)value);
            return;
        case QSTRASID:
            setQstRasId((Number)value);
            return;
        case RASFRIDID:
            setRasFridId((Number)value);
            return;
        case QSTTLYID:
            setQstTlyId((Number)value);
            return;
        case NUMCOLS:
            setNumCols((Number)value);
            return;
        case QSTANSID:
            setQstAnsId((Number)value);
            return;
        case RPRTID:
            setRprtId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
