package com.bawaweb.views.updatable;

import com.bawaweb.model.EmplOtlEmployeesImpl;

import com.bawaweb.views.updatable.common.EmplOtlEmployeesUViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmplOtlEmployeesUViewRowImpl extends ViewRowImpl implements EmplOtlEmployeesUViewRow {
    public static final int EMPLID = 0;
    public static final int EMPLINIT = 1;
    public static final int EMPLUSERID = 2;
    public static final int EMPLLNAME = 3;
    public static final int EMPLFNAME = 4;
    public static final int EMPLINITIAL = 5;
    public static final int DEPTID = 6;
    public static final int EMPLTITLE = 7;
    public static final int EMPLOFFICELOC = 8;
    public static final int EMPLDOB = 9;
    public static final int EMPLHIREDATE = 10;
    public static final int EMPLADDRESS = 11;
    public static final int EMPLCITY = 12;
    public static final int EMPLSTATE = 13;
    public static final int EMPLZIP = 14;
    public static final int EMPLCOUNTRY = 15;
    public static final int EMPLHOMEPHONE = 16;
    public static final int EMPLOFFICEPHONE = 17;
    public static final int EMPLINTEXTENSION = 18;
    public static final int EMPLOFFICEFAX = 19;
    public static final int EMPLEMAIL = 20;
    public static final int EMPLINTERNET = 21;
    public static final int EMPLNOTES = 22;
    public static final int EMPLREPTSTO = 23;
    public static final int EMPLDIRLISTING = 24;
    public static final int EMPLPASSWORD = 25;
    public static final int REGID = 26;
    public static final int RERGID = 27;
    public static final int ACGRID = 28;
    public static final int EMPLSTATUS = 29;
    public static final int EMPLIDHR = 30;
    public static final int BaWaWEBEMPLROLESUVIEW = 31;
    public static final int PANPANELUVIEW = 32;
    public static final int RPRTREPORTSUVIEW = 33;
    public static final int RPRTREPORTSUVIEW1 = 34;

    /**This is the default constructor (do not remove)
     */
    public EmplOtlEmployeesUViewRowImpl() {
    }

    /**Gets EmplOtlEmployees entity object.
     */
    public EmplOtlEmployeesImpl getEmplOtlEmployees() {
        return (EmplOtlEmployeesImpl)getEntity(0);
    }

    /**Gets the attribute value for EMPL_ID using the alias name EmplId
     */
    public Number getEmplId() {
        return (Number) getAttributeInternal(EMPLID);
    }

    /**Sets <code>value</code> as attribute value for EMPL_ID using the alias name EmplId
     */
    public void setEmplId(Number value) {
        setAttributeInternal(EMPLID, value);
    }

    /**Gets the attribute value for EMPL_INIT using the alias name EmplInit
     */
    public String getEmplInit() {
        return (String) getAttributeInternal(EMPLINIT);
    }

    /**Sets <code>value</code> as attribute value for EMPL_INIT using the alias name EmplInit
     */
    public void setEmplInit(String value) {
        setAttributeInternal(EMPLINIT, value);
    }

    /**Gets the attribute value for EMPL_USERID using the alias name EmplUserid
     */
    public String getEmplUserid() {
        return (String) getAttributeInternal(EMPLUSERID);
    }

    /**Sets <code>value</code> as attribute value for EMPL_USERID using the alias name EmplUserid
     */
    public void setEmplUserid(String value) {
        setAttributeInternal(EMPLUSERID, value);
    }

    /**Gets the attribute value for EMPL_LNAME using the alias name EmplLname
     */
    public String getEmplLname() {
        return (String) getAttributeInternal(EMPLLNAME);
    }

    /**Sets <code>value</code> as attribute value for EMPL_LNAME using the alias name EmplLname
     */
    public void setEmplLname(String value) {
        setAttributeInternal(EMPLLNAME, value);
    }

    /**Gets the attribute value for EMPL_FNAME using the alias name EmplFname
     */
    public String getEmplFname() {
        return (String) getAttributeInternal(EMPLFNAME);
    }

    /**Sets <code>value</code> as attribute value for EMPL_FNAME using the alias name EmplFname
     */
    public void setEmplFname(String value) {
        setAttributeInternal(EMPLFNAME, value);
    }

    /**Gets the attribute value for EMPL_INITIAL using the alias name EmplInitial
     */
    public String getEmplInitial() {
        return (String) getAttributeInternal(EMPLINITIAL);
    }

    /**Sets <code>value</code> as attribute value for EMPL_INITIAL using the alias name EmplInitial
     */
    public void setEmplInitial(String value) {
        setAttributeInternal(EMPLINITIAL, value);
    }

    /**Gets the attribute value for DEPT_ID using the alias name DeptId
     */
    public Number getDeptId() {
        return (Number) getAttributeInternal(DEPTID);
    }

    /**Sets <code>value</code> as attribute value for DEPT_ID using the alias name DeptId
     */
    public void setDeptId(Number value) {
        setAttributeInternal(DEPTID, value);
    }

    /**Gets the attribute value for EMPL_TITLE using the alias name EmplTitle
     */
    public String getEmplTitle() {
        return (String) getAttributeInternal(EMPLTITLE);
    }

    /**Sets <code>value</code> as attribute value for EMPL_TITLE using the alias name EmplTitle
     */
    public void setEmplTitle(String value) {
        setAttributeInternal(EMPLTITLE, value);
    }

    /**Gets the attribute value for EMPL_OFFICE_LOC using the alias name EmplOfficeLoc
     */
    public String getEmplOfficeLoc() {
        return (String) getAttributeInternal(EMPLOFFICELOC);
    }

    /**Sets <code>value</code> as attribute value for EMPL_OFFICE_LOC using the alias name EmplOfficeLoc
     */
    public void setEmplOfficeLoc(String value) {
        setAttributeInternal(EMPLOFFICELOC, value);
    }

    /**Gets the attribute value for EMPL_DOB using the alias name EmplDob
     */
    public Date getEmplDob() {
        return (Date) getAttributeInternal(EMPLDOB);
    }

    /**Sets <code>value</code> as attribute value for EMPL_DOB using the alias name EmplDob
     */
    public void setEmplDob(Date value) {
        setAttributeInternal(EMPLDOB, value);
    }

    /**Gets the attribute value for EMPL_HIRE_DATE using the alias name EmplHireDate
     */
    public Date getEmplHireDate() {
        return (Date) getAttributeInternal(EMPLHIREDATE);
    }

    /**Sets <code>value</code> as attribute value for EMPL_HIRE_DATE using the alias name EmplHireDate
     */
    public void setEmplHireDate(Date value) {
        setAttributeInternal(EMPLHIREDATE, value);
    }

    /**Gets the attribute value for EMPL_ADDRESS using the alias name EmplAddress
     */
    public String getEmplAddress() {
        return (String) getAttributeInternal(EMPLADDRESS);
    }

    /**Sets <code>value</code> as attribute value for EMPL_ADDRESS using the alias name EmplAddress
     */
    public void setEmplAddress(String value) {
        setAttributeInternal(EMPLADDRESS, value);
    }

    /**Gets the attribute value for EMPL_CITY using the alias name EmplCity
     */
    public String getEmplCity() {
        return (String) getAttributeInternal(EMPLCITY);
    }

    /**Sets <code>value</code> as attribute value for EMPL_CITY using the alias name EmplCity
     */
    public void setEmplCity(String value) {
        setAttributeInternal(EMPLCITY, value);
    }

    /**Gets the attribute value for EMPL_STATE using the alias name EmplState
     */
    public String getEmplState() {
        return (String) getAttributeInternal(EMPLSTATE);
    }

    /**Sets <code>value</code> as attribute value for EMPL_STATE using the alias name EmplState
     */
    public void setEmplState(String value) {
        setAttributeInternal(EMPLSTATE, value);
    }

    /**Gets the attribute value for EMPL_ZIP using the alias name EmplZip
     */
    public String getEmplZip() {
        return (String) getAttributeInternal(EMPLZIP);
    }

    /**Sets <code>value</code> as attribute value for EMPL_ZIP using the alias name EmplZip
     */
    public void setEmplZip(String value) {
        setAttributeInternal(EMPLZIP, value);
    }

    /**Gets the attribute value for EMPL_COUNTRY using the alias name EmplCountry
     */
    public String getEmplCountry() {
        return (String) getAttributeInternal(EMPLCOUNTRY);
    }

    /**Sets <code>value</code> as attribute value for EMPL_COUNTRY using the alias name EmplCountry
     */
    public void setEmplCountry(String value) {
        setAttributeInternal(EMPLCOUNTRY, value);
    }

    /**Gets the attribute value for EMPL_HOME_PHONE using the alias name EmplHomePhone
     */
    public String getEmplHomePhone() {
        return (String) getAttributeInternal(EMPLHOMEPHONE);
    }

    /**Sets <code>value</code> as attribute value for EMPL_HOME_PHONE using the alias name EmplHomePhone
     */
    public void setEmplHomePhone(String value) {
        setAttributeInternal(EMPLHOMEPHONE, value);
    }

    /**Gets the attribute value for EMPL_OFFICE_PHONE using the alias name EmplOfficePhone
     */
    public String getEmplOfficePhone() {
        return (String) getAttributeInternal(EMPLOFFICEPHONE);
    }

    /**Sets <code>value</code> as attribute value for EMPL_OFFICE_PHONE using the alias name EmplOfficePhone
     */
    public void setEmplOfficePhone(String value) {
        setAttributeInternal(EMPLOFFICEPHONE, value);
    }

    /**Gets the attribute value for EMPL_INT_EXTENSION using the alias name EmplIntExtension
     */
    public String getEmplIntExtension() {
        return (String) getAttributeInternal(EMPLINTEXTENSION);
    }

    /**Sets <code>value</code> as attribute value for EMPL_INT_EXTENSION using the alias name EmplIntExtension
     */
    public void setEmplIntExtension(String value) {
        setAttributeInternal(EMPLINTEXTENSION, value);
    }

    /**Gets the attribute value for EMPL_OFFICE_FAX using the alias name EmplOfficeFax
     */
    public String getEmplOfficeFax() {
        return (String) getAttributeInternal(EMPLOFFICEFAX);
    }

    /**Sets <code>value</code> as attribute value for EMPL_OFFICE_FAX using the alias name EmplOfficeFax
     */
    public void setEmplOfficeFax(String value) {
        setAttributeInternal(EMPLOFFICEFAX, value);
    }

    /**Gets the attribute value for EMPL_EMAIL using the alias name EmplEmail
     */
    public String getEmplEmail() {
        return (String) getAttributeInternal(EMPLEMAIL);
    }

    /**Sets <code>value</code> as attribute value for EMPL_EMAIL using the alias name EmplEmail
     */
    public void setEmplEmail(String value) {
        setAttributeInternal(EMPLEMAIL, value);
    }

    /**Gets the attribute value for EMPL_INTERNET using the alias name EmplInternet
     */
    public String getEmplInternet() {
        return (String) getAttributeInternal(EMPLINTERNET);
    }

    /**Sets <code>value</code> as attribute value for EMPL_INTERNET using the alias name EmplInternet
     */
    public void setEmplInternet(String value) {
        setAttributeInternal(EMPLINTERNET, value);
    }

    /**Gets the attribute value for EMPL_NOTES using the alias name EmplNotes
     */
    public String getEmplNotes() {
        return (String) getAttributeInternal(EMPLNOTES);
    }

    /**Sets <code>value</code> as attribute value for EMPL_NOTES using the alias name EmplNotes
     */
    public void setEmplNotes(String value) {
        setAttributeInternal(EMPLNOTES, value);
    }

    /**Gets the attribute value for EMPL_REPTS_TO using the alias name EmplReptsTo
     */
    public Number getEmplReptsTo() {
        return (Number) getAttributeInternal(EMPLREPTSTO);
    }

    /**Sets <code>value</code> as attribute value for EMPL_REPTS_TO using the alias name EmplReptsTo
     */
    public void setEmplReptsTo(Number value) {
        setAttributeInternal(EMPLREPTSTO, value);
    }

    /**Gets the attribute value for EMPL_DIR_LISTING using the alias name EmplDirListing
     */
    public Number getEmplDirListing() {
        return (Number) getAttributeInternal(EMPLDIRLISTING);
    }

    /**Sets <code>value</code> as attribute value for EMPL_DIR_LISTING using the alias name EmplDirListing
     */
    public void setEmplDirListing(Number value) {
        setAttributeInternal(EMPLDIRLISTING, value);
    }

    /**Gets the attribute value for EMPL_PASSWORD using the alias name EmplPassword
     */
    public String getEmplPassword() {
        return (String) getAttributeInternal(EMPLPASSWORD);
    }

    /**Sets <code>value</code> as attribute value for EMPL_PASSWORD using the alias name EmplPassword
     */
    public void setEmplPassword(String value) {
        setAttributeInternal(EMPLPASSWORD, value);
    }

    /**Gets the attribute value for REG_ID using the alias name RegId
     */
    public Number getRegId() {
        return (Number) getAttributeInternal(REGID);
    }

    /**Sets <code>value</code> as attribute value for REG_ID using the alias name RegId
     */
    public void setRegId(Number value) {
        setAttributeInternal(REGID, value);
    }

    /**Gets the attribute value for RERG_ID using the alias name RergId
     */
    public Number getRergId() {
        return (Number) getAttributeInternal(RERGID);
    }

    /**Sets <code>value</code> as attribute value for RERG_ID using the alias name RergId
     */
    public void setRergId(Number value) {
        setAttributeInternal(RERGID, value);
    }

    /**Gets the attribute value for ACGR_ID using the alias name AcgrId
     */
    public Number getAcgrId() {
        return (Number) getAttributeInternal(ACGRID);
    }

    /**Sets <code>value</code> as attribute value for ACGR_ID using the alias name AcgrId
     */
    public void setAcgrId(Number value) {
        setAttributeInternal(ACGRID, value);
    }

    /**Gets the attribute value for EMPL_STATUS using the alias name EmplStatus
     */
    public String getEmplStatus() {
        return (String) getAttributeInternal(EMPLSTATUS);
    }

    /**Sets <code>value</code> as attribute value for EMPL_STATUS using the alias name EmplStatus
     */
    public void setEmplStatus(String value) {
        setAttributeInternal(EMPLSTATUS, value);
    }

    /**Gets the attribute value for EMPL_ID_HR using the alias name EmplIdHr
     */
    public Number getEmplIdHr() {
        return (Number) getAttributeInternal(EMPLIDHR);
    }

    /**Sets <code>value</code> as attribute value for EMPL_ID_HR using the alias name EmplIdHr
     */
    public void setEmplIdHr(Number value) {
        setAttributeInternal(EMPLIDHR, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLID:
            return getEmplId();
        case EMPLINIT:
            return getEmplInit();
        case EMPLUSERID:
            return getEmplUserid();
        case EMPLLNAME:
            return getEmplLname();
        case EMPLFNAME:
            return getEmplFname();
        case EMPLINITIAL:
            return getEmplInitial();
        case DEPTID:
            return getDeptId();
        case EMPLTITLE:
            return getEmplTitle();
        case EMPLOFFICELOC:
            return getEmplOfficeLoc();
        case EMPLDOB:
            return getEmplDob();
        case EMPLHIREDATE:
            return getEmplHireDate();
        case EMPLADDRESS:
            return getEmplAddress();
        case EMPLCITY:
            return getEmplCity();
        case EMPLSTATE:
            return getEmplState();
        case EMPLZIP:
            return getEmplZip();
        case EMPLCOUNTRY:
            return getEmplCountry();
        case EMPLHOMEPHONE:
            return getEmplHomePhone();
        case EMPLOFFICEPHONE:
            return getEmplOfficePhone();
        case EMPLINTEXTENSION:
            return getEmplIntExtension();
        case EMPLOFFICEFAX:
            return getEmplOfficeFax();
        case EMPLEMAIL:
            return getEmplEmail();
        case EMPLINTERNET:
            return getEmplInternet();
        case EMPLNOTES:
            return getEmplNotes();
        case EMPLREPTSTO:
            return getEmplReptsTo();
        case EMPLDIRLISTING:
            return getEmplDirListing();
        case EMPLPASSWORD:
            return getEmplPassword();
        case REGID:
            return getRegId();
        case RERGID:
            return getRergId();
        case ACGRID:
            return getAcgrId();
        case EMPLSTATUS:
            return getEmplStatus();
        case EMPLIDHR:
            return getEmplIdHr();
        case BaWaWEBEMPLROLESUVIEW:
            return getOtlEmplRolesUView();
        case PANPANELUVIEW:
            return getPanPanelUView();
        case RPRTREPORTSUVIEW:
            return getRprtReportsUView();
        case RPRTREPORTSUVIEW1:
            return getRprtReportsUView1();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLID:
            setEmplId((Number)value);
            return;
        case EMPLINIT:
            setEmplInit((String)value);
            return;
        case EMPLUSERID:
            setEmplUserid((String)value);
            return;
        case EMPLLNAME:
            setEmplLname((String)value);
            return;
        case EMPLFNAME:
            setEmplFname((String)value);
            return;
        case EMPLINITIAL:
            setEmplInitial((String)value);
            return;
        case DEPTID:
            setDeptId((Number)value);
            return;
        case EMPLTITLE:
            setEmplTitle((String)value);
            return;
        case EMPLOFFICELOC:
            setEmplOfficeLoc((String)value);
            return;
        case EMPLDOB:
            setEmplDob((Date)value);
            return;
        case EMPLHIREDATE:
            setEmplHireDate((Date)value);
            return;
        case EMPLADDRESS:
            setEmplAddress((String)value);
            return;
        case EMPLCITY:
            setEmplCity((String)value);
            return;
        case EMPLSTATE:
            setEmplState((String)value);
            return;
        case EMPLZIP:
            setEmplZip((String)value);
            return;
        case EMPLCOUNTRY:
            setEmplCountry((String)value);
            return;
        case EMPLHOMEPHONE:
            setEmplHomePhone((String)value);
            return;
        case EMPLOFFICEPHONE:
            setEmplOfficePhone((String)value);
            return;
        case EMPLINTEXTENSION:
            setEmplIntExtension((String)value);
            return;
        case EMPLOFFICEFAX:
            setEmplOfficeFax((String)value);
            return;
        case EMPLEMAIL:
            setEmplEmail((String)value);
            return;
        case EMPLINTERNET:
            setEmplInternet((String)value);
            return;
        case EMPLNOTES:
            setEmplNotes((String)value);
            return;
        case EMPLREPTSTO:
            setEmplReptsTo((Number)value);
            return;
        case EMPLDIRLISTING:
            setEmplDirListing((Number)value);
            return;
        case EMPLPASSWORD:
            setEmplPassword((String)value);
            return;
        case REGID:
            setRegId((Number)value);
            return;
        case RERGID:
            setRergId((Number)value);
            return;
        case ACGRID:
            setAcgrId((Number)value);
            return;
        case EMPLSTATUS:
            setEmplStatus((String)value);
            return;
        case EMPLIDHR:
            setEmplIdHr((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlEmplRolesUView
     */
    public RowIterator getOtlEmplRolesUView() {
        return (RowIterator)getAttributeInternal(BaWaWEBEMPLROLESUVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link PanPanelUView
     */
    public RowIterator getPanPanelUView() {
        return (RowIterator)getAttributeInternal(PANPANELUVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link RprtReportsUView
     */
    public RowIterator getRprtReportsUView() {
        return (RowIterator)getAttributeInternal(RPRTREPORTSUVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link RprtReportsUView1
     */
    public RowIterator getRprtReportsUView1() {
        return (RowIterator)getAttributeInternal(RPRTREPORTSUVIEW1);
    }
}
