package com.bawaweb.views.updatable;

import com.bawaweb.model.OtlEmplRolesImpl;

import com.bawaweb.views.updatable.common.OtlEmplRolesUViewRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlEmplRolesUViewRowImpl extends ViewRowImpl implements OtlEmplRolesUViewRow {
    public static final int EMREMPLID = 0;
    public static final int EMRROLID = 1;

    /**This is the default constructor (do not remove)
     */
    public OtlEmplRolesUViewRowImpl() {
    }

    /**Gets OtlEmplRoles entity object.
     */
    public OtlEmplRolesImpl getOtlEmplRoles() {
        return (OtlEmplRolesImpl)getEntity(0);
    }

    /**Gets the attribute value for EMR_EMPL_ID using the alias name EmrEmplId
     */
    public Number getEmrEmplId() {
        return (Number) getAttributeInternal(EMREMPLID);
    }

    /**Sets <code>value</code> as attribute value for EMR_EMPL_ID using the alias name EmrEmplId
     */
    public void setEmrEmplId(Number value) {
        setAttributeInternal(EMREMPLID, value);
    }

    /**Gets the attribute value for EMR_ROL_ID using the alias name EmrRolId
     */
    public Number getEmrRolId() {
        return (Number) getAttributeInternal(EMRROLID);
    }

    /**Sets <code>value</code> as attribute value for EMR_ROL_ID using the alias name EmrRolId
     */
    public void setEmrRolId(Number value) {
        setAttributeInternal(EMRROLID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMREMPLID:
            return getEmrEmplId();
        case EMRROLID:
            return getEmrRolId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMREMPLID:
            setEmrEmplId((Number)value);
            return;
        case EMRROLID:
            setEmrRolId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
