package com.bawaweb.views.updatable;

import com.bawaweb.model.PanPanelImpl;

import com.bawaweb.views.updatable.common.PanPanelUViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PanPanelUViewRowImpl extends ViewRowImpl implements PanPanelUViewRow {
    public static final int PANID = 0;
    public static final int PANDESC = 1;
    public static final int FRIDID = 2;
    public static final int PANMULTINATIONALYN = 3;
    public static final int PANSRREPORTER = 4;
    public static final int PANSTATUS = 5;
    public static final int PANEUROPEANYN = 6;
    public static final int PANENHANCEDYN = 7;
    public static final int PANISPROPRIETARYYN = 8;
    public static final int RPRTREPORTSUVIEW = 9;

    /**This is the default constructor (do not remove)
     */
    public PanPanelUViewRowImpl() {
    }

    /**Gets PanPanel entity object.
     */
    public PanPanelImpl getPanPanel() {
        return (PanPanelImpl)getEntity(0);
    }

    /**Gets the attribute value for PAN_ID using the alias name PanId
     */
    public Number getPanId() {
        return (Number) getAttributeInternal(PANID);
    }

    /**Sets <code>value</code> as attribute value for PAN_ID using the alias name PanId
     */
    public void setPanId(Number value) {
        setAttributeInternal(PANID, value);
    }

    /**Gets the attribute value for PAN_DESC using the alias name PanDesc
     */
    public String getPanDesc() {
        return (String) getAttributeInternal(PANDESC);
    }

    /**Sets <code>value</code> as attribute value for PAN_DESC using the alias name PanDesc
     */
    public void setPanDesc(String value) {
        setAttributeInternal(PANDESC, value);
    }

    /**Gets the attribute value for FRID_ID using the alias name FridId
     */
    public Number getFridId() {
        return (Number) getAttributeInternal(FRIDID);
    }

    /**Sets <code>value</code> as attribute value for FRID_ID using the alias name FridId
     */
    public void setFridId(Number value) {
        setAttributeInternal(FRIDID, value);
    }

    /**Gets the attribute value for PAN_MULTI_NATIONAL_YN using the alias name PanMultiNationalYn
     */
    public String getPanMultiNationalYn() {
        return (String) getAttributeInternal(PANMULTINATIONALYN);
    }

    /**Sets <code>value</code> as attribute value for PAN_MULTI_NATIONAL_YN using the alias name PanMultiNationalYn
     */
    public void setPanMultiNationalYn(String value) {
        setAttributeInternal(PANMULTINATIONALYN, value);
    }

    /**Gets the attribute value for PAN_SR_REPORTER using the alias name PanSrReporter
     */
    public Number getPanSrReporter() {
        return (Number) getAttributeInternal(PANSRREPORTER);
    }

    /**Sets <code>value</code> as attribute value for PAN_SR_REPORTER using the alias name PanSrReporter
     */
    public void setPanSrReporter(Number value) {
        setAttributeInternal(PANSRREPORTER, value);
    }

    /**Gets the attribute value for PAN_STATUS using the alias name PanStatus
     */
    public Number getPanStatus() {
        return (Number) getAttributeInternal(PANSTATUS);
    }

    /**Sets <code>value</code> as attribute value for PAN_STATUS using the alias name PanStatus
     */
    public void setPanStatus(Number value) {
        setAttributeInternal(PANSTATUS, value);
    }

    /**Gets the attribute value for PAN_EUROPEAN_YN using the alias name PanEuropeanYn
     */
    public String getPanEuropeanYn() {
        return (String) getAttributeInternal(PANEUROPEANYN);
    }

    /**Sets <code>value</code> as attribute value for PAN_EUROPEAN_YN using the alias name PanEuropeanYn
     */
    public void setPanEuropeanYn(String value) {
        setAttributeInternal(PANEUROPEANYN, value);
    }

    /**Gets the attribute value for PAN_ENHANCED_YN using the alias name PanEnhancedYn
     */
    public String getPanEnhancedYn() {
        return (String) getAttributeInternal(PANENHANCEDYN);
    }

    /**Sets <code>value</code> as attribute value for PAN_ENHANCED_YN using the alias name PanEnhancedYn
     */
    public void setPanEnhancedYn(String value) {
        setAttributeInternal(PANENHANCEDYN, value);
    }

    /**Gets the attribute value for PAN_IS_PROPRIETARY_YN using the alias name PanIsProprietaryYn
     */
    public String getPanIsProprietaryYn() {
        return (String) getAttributeInternal(PANISPROPRIETARYYN);
    }

    /**Sets <code>value</code> as attribute value for PAN_IS_PROPRIETARY_YN using the alias name PanIsProprietaryYn
     */
    public void setPanIsProprietaryYn(String value) {
        setAttributeInternal(PANISPROPRIETARYYN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PANID:
            return getPanId();
        case PANDESC:
            return getPanDesc();
        case FRIDID:
            return getFridId();
        case PANMULTINATIONALYN:
            return getPanMultiNationalYn();
        case PANSRREPORTER:
            return getPanSrReporter();
        case PANSTATUS:
            return getPanStatus();
        case PANEUROPEANYN:
            return getPanEuropeanYn();
        case PANENHANCEDYN:
            return getPanEnhancedYn();
        case PANISPROPRIETARYYN:
            return getPanIsProprietaryYn();
        case RPRTREPORTSUVIEW:
            return getRprtReportsUView();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PANID:
            setPanId((Number)value);
            return;
        case PANDESC:
            setPanDesc((String)value);
            return;
        case FRIDID:
            setFridId((Number)value);
            return;
        case PANMULTINATIONALYN:
            setPanMultiNationalYn((String)value);
            return;
        case PANSRREPORTER:
            setPanSrReporter((Number)value);
            return;
        case PANSTATUS:
            setPanStatus((Number)value);
            return;
        case PANEUROPEANYN:
            setPanEuropeanYn((String)value);
            return;
        case PANENHANCEDYN:
            setPanEnhancedYn((String)value);
            return;
        case PANISPROPRIETARYYN:
            setPanIsProprietaryYn((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link RprtReportsUView
     */
    public RowIterator getRprtReportsUView() {
        return (RowIterator)getAttributeInternal(RPRTREPORTSUVIEW);
    }
}
