package com.bawaweb.views.updatable;

import com.bawaweb.model.RptyReporterTypesImpl;

import com.bawaweb.views.updatable.common.RptyReporterTypesUViewRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RptyReporterTypesUViewRowImpl extends ViewRowImpl implements RptyReporterTypesUViewRow {
    public static final int RPTYID = 0;
    public static final int RPTYDESC = 1;

    /**This is the default constructor (do not remove)
     */
    public RptyReporterTypesUViewRowImpl() {
    }

    /**Gets RptyReporterTypes entity object.
     */
    public RptyReporterTypesImpl getRptyReporterTypes() {
        return (RptyReporterTypesImpl)getEntity(0);
    }

    /**Gets the attribute value for RPTY_ID using the alias name RptyId
     */
    public Number getRptyId() {
        return (Number) getAttributeInternal(RPTYID);
    }

    /**Sets <code>value</code> as attribute value for RPTY_ID using the alias name RptyId
     */
    public void setRptyId(Number value) {
        setAttributeInternal(RPTYID, value);
    }

    /**Gets the attribute value for RPTY_DESC using the alias name RptyDesc
     */
    public String getRptyDesc() {
        return (String) getAttributeInternal(RPTYDESC);
    }

    /**Sets <code>value</code> as attribute value for RPTY_DESC using the alias name RptyDesc
     */
    public void setRptyDesc(String value) {
        setAttributeInternal(RPTYDESC, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RPTYID:
            return getRptyId();
        case RPTYDESC:
            return getRptyDesc();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RPTYID:
            setRptyId((Number)value);
            return;
        case RPTYDESC:
            setRptyDesc((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
