package com.bawaweb.views.model.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnswerSetValuesRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public AnswerSetValuesRowClient() {
    }


    public Number getAsvId() {
        return (Number)getAttribute("AsvId");
    }

    public void setAsvId(Number value) {
        setAttribute("AsvId", value);
    }

    public Number getAsvAnsId() {
        return (Number)getAttribute("AsvAnsId");
    }

    public void setAsvAnsId(Number value) {
        setAttribute("AsvAnsId", value);
    }

    public String getAsvAnswer() {
        return (String)getAttribute("AsvAnswer");
    }

    public void setAsvAnswer(String value) {
        setAttribute("AsvAnswer", value);
    }

    public Number getAsvDisplaySeq() {
        return (Number)getAttribute("AsvDisplaySeq");
    }

    public void setAsvDisplaySeq(Number value) {
        setAttribute("AsvDisplaySeq", value);
    }

    public String getAsvDeleteYn() {
        return (String)getAttribute("AsvDeleteYn");
    }

    public void setAsvDeleteYn(String value) {
        setAttribute("AsvDeleteYn", value);
    }
}
