package com.bawaweb.views.model.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountriesListRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public CountriesListRowClient() {
    }


    public Number getCtryId() {
        return (Number)getAttribute("CtryId");
    }

    public String getCtryIsoCntryCode() {
        return (String)getAttribute("CtryIsoCntryCode");
    }

    public String getCtryName() {
        return (String)getAttribute("CtryName");
    }

    public String getCtryShortname() {
        return (String)getAttribute("CtryShortname");
    }

    public Number getRergId() {
        return (Number)getAttribute("RergId");
    }

    public void setCtryId(Number value) {
        setAttribute("CtryId", value);
    }

    public void setCtryIsoCntryCode(String value) {
        setAttribute("CtryIsoCntryCode", value);
    }

    public void setCtryName(String value) {
        setAttribute("CtryName", value);
    }

    public void setCtryShortname(String value) {
        setAttribute("CtryShortname", value);
    }

    public void setRergId(Number value) {
        setAttribute("RergId", value);
    }
}
