package com.bawaweb.views.updatable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlEmplRolesUView extends ViewObject {
    long getEstimatedRowCount();

    Number getemr_empl_id();

    void setemr_empl_id(Number value);
}
