package com.bawaweb.views.updatable.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlMultiQuestionsUViewRow extends Row {
    Number getQmqAnsId();

    String getQmqHint();

    Number getQmqId();

    String getQmqNumber();

    Number getQmqPointSpread();

    Number getQmqQstId();

    Number getQmqRasId();

    Number getQmqTlyId();

    String getQmqType();

    RowID getRowID();

    void setQmqAnsId(Number value);

    void setQmqHint(String value);

    void setQmqId(Number value);

    void setQmqNumber(String value);

    void setQmqPointSpread(Number value);

    void setQmqQstId(Number value);

    void setQmqRasId(Number value);

    void setQmqTlyId(Number value);

    void setQmqType(String value);
}
