package com.bawaweb.views.updatable.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlReportSortingCriteriaUViewRow extends Row {
    Number getRsoDisplaySeq();

    Number getRsoRprtId();

    Number getRsoSrtId();

    void setRsoDisplaySeq(Number value);

    void setRsoRprtId(Number value);

    void setRsoSrtId(Number value);
}
