package com.bawaweb.views.updatable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlReportAnswerSetValuesUView extends ViewObject {
    long getEstimatedRowCount();

    Number getrav_id();

    void setrav_id(Number value);
}
