package com.bawaweb.views.updatable.common;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlSortingCriteriaUViewRow extends Row {
    RowIterator getOtlReportSortingCriteriaUView();

    RowIterator getOtlSortingCriteriaValuesUView();

    String getSrtDeleteYn();

    Number getSrtFridId();

    Number getSrtId();

    String getSrtName();

    void setSrtDeleteYn(String value);

    void setSrtFridId(Number value);

    void setSrtId(Number value);

    void setSrtName(String value);
}
