package com.bawaweb.views.updatable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlSourcesUView extends ViewObject {
    long getEstimatedRowCount();

    Number getsrc_id();

    void setsrc_id(Number value);
}
