package com.bawaweb.views.updatable.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtrEmployeeInfoUView extends ViewObject {
    long getEstimatedRowCount();
}
