package com.bawaweb.views.updatable.common;

import oracle.jbo.Row;
import oracle.jbo.domain.RowID;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtrEmployeeInfoUViewRow extends Row {
    String getAdditionalExpertise();

    String getCountry();

    String getCovers();

    String getDepartment();

    String getFirstName();

    String getLastName();

    String getLongBio();

    String getOtrSince();

    String getRegion();

    String getReportsTo();

    RowID getRowID();

    String getSectors();

    String getShortBio();

    String getTitle();

    void setAdditionalExpertise(String value);

    void setCountry(String value);

    void setCovers(String value);

    void setDepartment(String value);

    void setFirstName(String value);

    void setLastName(String value);

    void setLongBio(String value);

    void setOtrSince(String value);

    void setRegion(String value);

    void setReportsTo(String value);

    void setSectors(String value);

    void setShortBio(String value);

    void setTitle(String value);
}
