package com.bawaweb.views.updatable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface PanPanelUView extends ViewObject {
    long getEstimatedRowCount();

    Number getpan_id();

    void setpan_id(Number value);
}
