package com.bawaweb.views.updatable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface RtypReportTypesUView extends ViewObject {
    long getEstimatedRowCount();

    Number getrtyp_id();

    void setrtyp_id(Number value);
}
