package com.bawaweb.views.gridcursors.client;

import com.bawaweb.views.gridcursors.common.AnsGridErrFileInfo;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnsGridErrFileInfoClient extends ViewUsageImpl implements AnsGridErrFileInfo {
    /**This is the default constructor (do not remove)
     */
    public AnsGridErrFileInfoClient() {
    }

    public long getEstimatedRowCount() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getEstimatedRowCount",null,null);
        return ((Long)_ret).longValue();
    }

    public Number getrprtId() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getrprtId",null,null);
        return (Number)_ret;
    }

    public String getrprtrId() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getrprtrId",null,null);
        return (String)_ret;
    }

    public void setrprtId(Number value) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setrprtId",new String [] {"oracle.jbo.domain.Number"},new Object[] {value});
        return;
    }

    public void setrprtrId(String value) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setrprtrId",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
}
