package com.bawaweb.views.gridcursors.client;

import com.bawaweb.views.gridcursors.common.RoleScope;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RoleScopeClient extends ViewUsageImpl implements RoleScope {
    /**This is the default constructor (do not remove)
     */
    public RoleScopeClient() {
    }


    public long getEstimatedRowCount() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getEstimatedRowCount",null,null);
        return ((Long)_ret).longValue();
    }

    public Number getp_empl_id() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getp_empl_id",null,null);
        return (Number)_ret;
    }

    public void setp_empl_id(Number value) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setp_empl_id",new String [] {"oracle.jbo.domain.Number"},new Object[] {value});
        return;
    }
}
