package com.bawaweb.views.gridcursors.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TallyRangeSetsRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public TallyRangeSetsRowClient() {
    }


    public String getTlyDeleteYn() {
        return (String)getAttribute("TlyDeleteYn");
    }

    public Number getTlyId() {
        return (Number)getAttribute("TlyId");
    }

    public String getTlyName() {
        return (String)getAttribute("TlyName");
    }

    public String getTlyPrefix() {
        return (String)getAttribute("TlyPrefix");
    }

    public String getTlySuffix() {
        return (String)getAttribute("TlySuffix");
    }

    public String getTrlDeleteYn() {
        return (String)getAttribute("TrlDeleteYn");
    }

    public Number getTrlDisplaySeq() {
        return (Number)getAttribute("TrlDisplaySeq");
    }

    public String getTrlFrom() {
        return (String)getAttribute("TrlFrom");
    }

    public Number getTrlId() {
        return (Number)getAttribute("TrlId");
    }

    public Number getTrlTlyId() {
        return (Number)getAttribute("TrlTlyId");
    }

    public String getTrlTo() {
        return (String)getAttribute("TrlTo");
    }

    public String getTrlType() {
        return (String)getAttribute("TrlType");
    }

    public void setTlyDeleteYn(String value) {
        setAttribute("TlyDeleteYn", value);
    }

    public void setTlyId(Number value) {
        setAttribute("TlyId", value);
    }

    public void setTlyName(String value) {
        setAttribute("TlyName", value);
    }

    public void setTlyPrefix(String value) {
        setAttribute("TlyPrefix", value);
    }

    public void setTlySuffix(String value) {
        setAttribute("TlySuffix", value);
    }

    public void setTrlDeleteYn(String value) {
        setAttribute("TrlDeleteYn", value);
    }

    public void setTrlDisplaySeq(Number value) {
        setAttribute("TrlDisplaySeq", value);
    }

    public void setTrlFrom(String value) {
        setAttribute("TrlFrom", value);
    }

    public void setTrlId(Number value) {
        setAttribute("TrlId", value);
    }

    public void setTrlTlyId(Number value) {
        setAttribute("TrlTlyId", value);
    }

    public void setTrlTo(String value) {
        setAttribute("TrlTo", value);
    }

    public void setTrlType(String value) {
        setAttribute("TrlType", value);
    }
}
