package com.bawaweb.views.gridcursors.common;

import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface AnsGridErrFileInfoRow extends Row {
    Number getAgefId();

    void setAgefId(Number value);

    String getAgefFileName();

    void setAgefFileName(String value);

    String getAgefFileFormatType();

    void setAgefFileFormatType(String value);

    Number getAgefRprtId();

    void setAgefRprtId(Number value);

    Date getCreationDate();

    void setCreationDate(Date value);

    String getCreatedBy();

    void setCreatedBy(String value);

    BlobDomain getAgefFile();

    void setAgefFile(BlobDomain value);
}
