package com.bawaweb.views.gridcursors.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface EditorInfoRow extends Row {
    Number getEmplId();

    void setEmplId(Number value);

    String getEmplInit();

    void setEmplInit(String value);

    String getEmplUserid();

    void setEmplUserid(String value);

    String getEmplLname();

    void setEmplLname(String value);

    String getEmplFname();

    void setEmplFname(String value);

    String getEmplInitial();

    void setEmplInitial(String value);

    Number getDeptId();

    void setDeptId(Number value);

    String getEmplTitle();

    void setEmplTitle(String value);

    String getEmplOfficeLoc();

    void setEmplOfficeLoc(String value);

    Date getEmplDob();

    void setEmplDob(Date value);

    Date getEmplHireDate();

    void setEmplHireDate(Date value);

    String getEmplAddress();

    void setEmplAddress(String value);

    String getEmplCity();

    void setEmplCity(String value);

    String getEmplState();

    void setEmplState(String value);

    String getEmplZip();

    void setEmplZip(String value);

    String getEmplCountry();

    void setEmplCountry(String value);

    String getEmplHomePhone();

    void setEmplHomePhone(String value);

    String getEmplOfficePhone();

    void setEmplOfficePhone(String value);

    String getEmplIntExtension();

    void setEmplIntExtension(String value);

    String getEmplOfficeFax();

    void setEmplOfficeFax(String value);

    String getEmplEmail();

    void setEmplEmail(String value);

    String getEmplInternet();

    void setEmplInternet(String value);

    String getEmplNotes();

    void setEmplNotes(String value);

    Number getEmplReptsTo();

    void setEmplReptsTo(Number value);

    Number getEmplDirListing();

    void setEmplDirListing(Number value);

    String getEmplPassword();

    void setEmplPassword(String value);

    Number getRegId();

    void setRegId(Number value);

    Number getRergId();

    void setRergId(Number value);

    Number getAcgrId();

    void setAcgrId(Number value);

    String getEmplStatus();

    void setEmplStatus(String value);

    Number getEmplIdHr();

    void setEmplIdHr(Number value);
}
