package com.bawaweb.views.gridcursors.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface MultiAnswerSetsRow extends Row {


    String getRavAnswer();

    Number getRavAsvId();

    String getRavDeleteYn();

    Number getRavDisplaySeq();

    Number getRavId();

    Number getRavRasId();

    void setRavAnswer(String value);

    void setRavAsvId(Number value);

    void setRavDeleteYn(String value);

    void setRavDisplaySeq(Number value);

    void setRavId(Number value);

    void setRavRasId(Number value);

    Number getAnsId();

    void setAnsId(Number value);
}
