package com.bawaweb.views.gridcursors.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface QuestionsListRow extends Row {
    Number getQstId();

    void setQstId(Number value);

    String getQstNumber();

    void setQstNumber(String value);

    Number getOrderBy1();

    void setOrderBy1(Number value);

    Number getNumericPart();

    void setNumericPart(Number value);

    String getAlphaPart();

    void setAlphaPart(String value);

    String getQstQuestion();

    void setQstQuestion(String value);

    String getQstType();

    void setQstType(String value);

    Number getQstMultiAnswers();

    void setQstMultiAnswers(Number value);

    String getQstQuestionHint();

    void setQstQuestionHint(String value);

    String getQstTextRequiredYn();

    void setQstTextRequiredYn(String value);

    String getQstTextHint();

    void setQstTextHint(String value);

    Number getQstRasId();

    void setQstRasId(Number value);

    Number getRasFridId();

    void setRasFridId(Number value);

    Number getQstTlyId();

    void setQstTlyId(Number value);

    Number getNumCols();

    void setNumCols(Number value);

    Number getQstAnsId();

    void setQstAnsId(Number value);
}
