package com.bawaweb.views.gridcursors.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface SourcesSortingCriteriaSets extends ViewObject {
    long getEstimatedRowCount();

    Number getqst_id();

    Number getrprt_id();

    void setqst_id(Number value);

    void setrprt_id(Number value);


}
