package com.bawaweb.views.gridcursors.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface SourceMultiAnswerSetsRow extends Row {
    String getAnswer();

    Number getQmqId();

    String getQmqNumber();

    Number getQmqQstId();

    String getQmqType();

    String getQstType();

    Number getRavId();

    Number getSmaSraId();

    String getSraAnswerText();

    String getSraColor();

    String getSraComment();

    Number getSraId();

    Number getSraRpsId();

    void setAnswer(String value);

    void setQmqId(Number value);

    void setQmqNumber(String value);

    void setQmqQstId(Number value);

    void setQmqType(String value);

    void setQstType(String value);

    void setRavId(Number value);

    void setSmaSraId(Number value);

    void setSraAnswerText(String value);

    void setSraColor(String value);

    void setSraComment(String value);

    void setSraId(Number value);

    void setSraRpsId(Number value);

    Number getRavAsvId();

    String getRavDeleteYn();

    Number getRavDisplaySeq();

    Number getSmaAsvId();

    String getSmaExcludeYn();

    Number getSmaRavId();

    Number getSmaWeightMultiplier();

    Number getSraAsvId();

    String getSraExcludeYn();

    Number getSraQstId();

    Number getSraRavId();

    Number getSraWeightMultiplier();

    void setRavAsvId(Number value);

    void setRavDeleteYn(String value);

    void setRavDisplaySeq(Number value);

    void setSmaAsvId(Number value);

    void setSmaExcludeYn(String value);

    void setSmaRavId(Number value);

    void setSmaWeightMultiplier(Number value);

    void setSraAsvId(Number value);

    void setSraExcludeYn(String value);

    void setSraQstId(Number value);

    void setSraRavId(Number value);

    void setSraWeightMultiplier(Number value);
}
