package com.bawaweb.views.utils.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface IndustryViews extends ViewObject {
    long getEstimatedRowCount();
}
