package com.bawaweb.views.utils.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface TimeZonesRow extends Row {
    String getTmzDeleteYn();

    String getTmzDescription();

    Number getTmzGmtAdjustmentHrs();

    Number getTmzGmtAdjustmentMin();

    Number getTmzId();

    String getTmzName();

    String getTmzNameDescription();

    void setTmzDeleteYn(String value);

    void setTmzDescription(String value);

    void setTmzGmtAdjustmentHrs(Number value);

    void setTmzGmtAdjustmentMin(Number value);

    void setTmzId(Number value);

    void setTmzName(String value);

    void setTmzNameDescription(String value);
}
