package com.bawaweb.views.readable;

import com.bawaweb.model.FridFirmIndustriesImpl;

import com.bawaweb.views.readable.common.FridFirmIndustriesRViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FridFirmIndustriesRViewRowImpl extends ViewRowImpl implements FridFirmIndustriesRViewRow {
    public static final int FRIDID = 0;
    public static final int FRIDDESCRIPTION = 1;
    public static final int FRIDPROPCAPACITY = 2;
    public static final int BaWaWEBANSWERSETSRVIEW = 3;
    public static final int BaWaWEBREPORTANSWERSETSRVIEW = 4;
    public static final int BaWaWEBSORTINGCRITERIARVIEW = 5;
    public static final int PANPANELRVIEW = 6;
    public static final int RPRTREPORTSRVIEW = 7;

    /**This is the default constructor (do not remove)
     */
    public FridFirmIndustriesRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute FridId
     */
    public Number getFridId() {
        return (Number) getAttributeInternal(FRIDID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FridId
     */
    public void setFridId(Number value) {
        setAttributeInternal(FRIDID, value);
    }

    /**Gets the attribute value for the calculated attribute FridDescription
     */
    public String getFridDescription() {
        return (String) getAttributeInternal(FRIDDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FridDescription
     */
    public void setFridDescription(String value) {
        setAttributeInternal(FRIDDESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute FridPropCapacity
     */
    public String getFridPropCapacity() {
        return (String) getAttributeInternal(FRIDPROPCAPACITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FridPropCapacity
     */
    public void setFridPropCapacity(String value) {
        setAttributeInternal(FRIDPROPCAPACITY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case FRIDID:
            return getFridId();
        case FRIDDESCRIPTION:
            return getFridDescription();
        case FRIDPROPCAPACITY:
            return getFridPropCapacity();
        case BaWaWEBANSWERSETSRVIEW:
            return getOtlAnswerSetsRView();
        case BaWaWEBREPORTANSWERSETSRVIEW:
            return getOtlReportAnswerSetsRView();
        case BaWaWEBSORTINGCRITERIARVIEW:
            return getOtlSortingCriteriaRView();
        case PANPANELRVIEW:
            return getPanPanelRView();
        case RPRTREPORTSRVIEW:
            return getRprtReportsRView();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the associated <code>RowIterator</code> using master-detail link OtlReportAnswerSetsRView
     */
    public RowIterator getOtlReportAnswerSetsRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBREPORTANSWERSETSRVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlSortingCriteriaRView
     */
    public RowIterator getOtlSortingCriteriaRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBSORTINGCRITERIARVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link PanPanelRView
     */
    public RowIterator getPanPanelRView() {
        return (RowIterator)getAttributeInternal(PANPANELRVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link RprtReportsRView
     */
    public RowIterator getRprtReportsRView() {
        return (RowIterator)getAttributeInternal(RPRTREPORTSRVIEW);
    }

    /**Gets FridFirmIndustries entity object.
     */
    public FridFirmIndustriesImpl getFridFirmIndustries() {
        return (FridFirmIndustriesImpl)getEntity(0);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlAnswerSetsRView
     */
    public RowIterator getOtlAnswerSetsRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBANSWERSETSRVIEW);
    }
}
