package com.bawaweb.views.readable;

import com.bawaweb.model.OtlAnswerSetsImpl;

import com.bawaweb.views.readable.common.OtlAnswerSetsRViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlAnswerSetsRViewRowImpl extends ViewRowImpl implements OtlAnswerSetsRViewRow {
    public static final int ANSID = 0;
    public static final int ANSNAME = 1;
    public static final int ANSFRIDID = 2;
    public static final int ANSORDERBYNAMEYN = 3;
    public static final int ANSADDANSWERYN = 4;
    public static final int ANSDELETEYN = 5;
    public static final int BaWaWEBANSWERSETVALUESRVIEW = 6;
    public static final int BaWaWEBREPORTANSWERSETSRVIEW = 7;

    /**This is the default constructor (do not remove)
     */
    public OtlAnswerSetsRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute AnsId
     */
    public Number getAnsId() {
        return (Number) getAttributeInternal(ANSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AnsId
     */
    public void setAnsId(Number value) {
        setAttributeInternal(ANSID, value);
    }

    /**Gets the attribute value for the calculated attribute AnsName
     */
    public String getAnsName() {
        return (String) getAttributeInternal(ANSNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AnsName
     */
    public void setAnsName(String value) {
        setAttributeInternal(ANSNAME, value);
    }

    /**Gets the attribute value for the calculated attribute AnsFridId
     */
    public Number getAnsFridId() {
        return (Number) getAttributeInternal(ANSFRIDID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AnsFridId
     */
    public void setAnsFridId(Number value) {
        setAttributeInternal(ANSFRIDID, value);
    }

    /**Gets the attribute value for the calculated attribute AnsOrderByNameYn
     */
    public String getAnsOrderByNameYn() {
        return (String) getAttributeInternal(ANSORDERBYNAMEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AnsOrderByNameYn
     */
    public void setAnsOrderByNameYn(String value) {
        setAttributeInternal(ANSORDERBYNAMEYN, value);
    }

    /**Gets the attribute value for the calculated attribute AnsAddAnswerYn
     */
    public String getAnsAddAnswerYn() {
        return (String) getAttributeInternal(ANSADDANSWERYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AnsAddAnswerYn
     */
    public void setAnsAddAnswerYn(String value) {
        setAttributeInternal(ANSADDANSWERYN, value);
    }

    /**Gets the attribute value for the calculated attribute AnsDeleteYn
     */
    public String getAnsDeleteYn() {
        return (String) getAttributeInternal(ANSDELETEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AnsDeleteYn
     */
    public void setAnsDeleteYn(String value) {
        setAttributeInternal(ANSDELETEYN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ANSID:
            return getAnsId();
        case ANSNAME:
            return getAnsName();
        case ANSFRIDID:
            return getAnsFridId();
        case ANSORDERBYNAMEYN:
            return getAnsOrderByNameYn();
        case ANSADDANSWERYN:
            return getAnsAddAnswerYn();
        case ANSDELETEYN:
            return getAnsDeleteYn();
        case BaWaWEBANSWERSETVALUESRVIEW:
            return getOtlAnswerSetValuesRView();
        case BaWaWEBREPORTANSWERSETSRVIEW:
            return getOtlReportAnswerSetsRView();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlAnswerSetValuesRView
     */
    public RowIterator getOtlAnswerSetValuesRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBANSWERSETVALUESRVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlReportAnswerSetsRView
     */
    public RowIterator getOtlReportAnswerSetsRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBREPORTANSWERSETSRVIEW);
    }

    /**Gets OtlAnswerSets entity object.
     */
    public OtlAnswerSetsImpl getOtlAnswerSets() {
        return (OtlAnswerSetsImpl)getEntity(0);
    }
}
