package com.bawaweb.views.readable;

import com.bawaweb.model.OtlMultiQuestionsImpl;

import com.bawaweb.views.readable.common.OtlMultiQuestionsRViewRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlMultiQuestionsRViewRowImpl extends ViewRowImpl implements OtlMultiQuestionsRViewRow {
    public static final int QMQID = 0;
    public static final int QMQQSTID = 1;
    public static final int QMQNUMBER = 2;
    public static final int QMQTYPE = 3;
    public static final int QMQHINT = 4;
    public static final int QMQANSID = 5;
    public static final int QMQTLYID = 6;
    public static final int QMQPOINTSPREAD = 7;
    public static final int QMQRASID = 8;

    /**This is the default constructor (do not remove)
     */
    public OtlMultiQuestionsRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute QmqId
     */
    public Number getQmqId() {
        return (Number) getAttributeInternal(QMQID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqId
     */
    public void setQmqId(Number value) {
        setAttributeInternal(QMQID, value);
    }

    /**Gets the attribute value for the calculated attribute QmqQstId
     */
    public Number getQmqQstId() {
        return (Number) getAttributeInternal(QMQQSTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqQstId
     */
    public void setQmqQstId(Number value) {
        setAttributeInternal(QMQQSTID, value);
    }

    /**Gets the attribute value for the calculated attribute QmqNumber
     */
    public String getQmqNumber() {
        return (String) getAttributeInternal(QMQNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqNumber
     */
    public void setQmqNumber(String value) {
        setAttributeInternal(QMQNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute QmqType
     */
    public String getQmqType() {
        return (String) getAttributeInternal(QMQTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqType
     */
    public void setQmqType(String value) {
        setAttributeInternal(QMQTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute QmqHint
     */
    public String getQmqHint() {
        return (String) getAttributeInternal(QMQHINT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqHint
     */
    public void setQmqHint(String value) {
        setAttributeInternal(QMQHINT, value);
    }

    /**Gets the attribute value for the calculated attribute QmqAnsId
     */
    public Number getQmqAnsId() {
        return (Number) getAttributeInternal(QMQANSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqAnsId
     */
    public void setQmqAnsId(Number value) {
        setAttributeInternal(QMQANSID, value);
    }

    /**Gets the attribute value for the calculated attribute QmqTlyId
     */
    public Number getQmqTlyId() {
        return (Number) getAttributeInternal(QMQTLYID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqTlyId
     */
    public void setQmqTlyId(Number value) {
        setAttributeInternal(QMQTLYID, value);
    }

    /**Gets the attribute value for the calculated attribute QmqPointSpread
     */
    public Number getQmqPointSpread() {
        return (Number) getAttributeInternal(QMQPOINTSPREAD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqPointSpread
     */
    public void setQmqPointSpread(Number value) {
        setAttributeInternal(QMQPOINTSPREAD, value);
    }

    /**Gets the attribute value for the calculated attribute QmqRasId
     */
    public Number getQmqRasId() {
        return (Number) getAttributeInternal(QMQRASID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute QmqRasId
     */
    public void setQmqRasId(Number value) {
        setAttributeInternal(QMQRASID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case QMQID:
            return getQmqId();
        case QMQQSTID:
            return getQmqQstId();
        case QMQNUMBER:
            return getQmqNumber();
        case QMQTYPE:
            return getQmqType();
        case QMQHINT:
            return getQmqHint();
        case QMQANSID:
            return getQmqAnsId();
        case QMQTLYID:
            return getQmqTlyId();
        case QMQPOINTSPREAD:
            return getQmqPointSpread();
        case QMQRASID:
            return getQmqRasId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets OtlMultiQuestions entity object.
     */
    public OtlMultiQuestionsImpl getOtlMultiQuestions() {
        return (OtlMultiQuestionsImpl)getEntity(0);
    }
}
