package com.bawaweb.views.readable;

import com.bawaweb.model.OtlReportAnswerSetValuesImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlReportAnswerSetValuesRViewRowImpl extends ViewRowImpl {
    public static final int RAVID = 0;
    public static final int RAVRASID = 1;
    public static final int RAVANSWER = 2;
    public static final int RAVDISPLAYSEQ = 3;
    public static final int RAVASVID = 4;
    public static final int RAVDELETEYN = 5;
    public static final int BaWaWEBSOURCEANSWERSRVIEW = 6;
    public static final int BaWaWEBSOURCEMULTIANSWERSRVIEW = 7;

    /**This is the default constructor (do not remove)
     */
    public OtlReportAnswerSetValuesRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RavId
     */
    public Number getRavId() {
        return (Number) getAttributeInternal(RAVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavId
     */
    public void setRavId(Number value) {
        setAttributeInternal(RAVID, value);
    }

    /**Gets the attribute value for the calculated attribute RavRasId
     */
    public Number getRavRasId() {
        return (Number) getAttributeInternal(RAVRASID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavRasId
     */
    public void setRavRasId(Number value) {
        setAttributeInternal(RAVRASID, value);
    }

    /**Gets the attribute value for the calculated attribute RavAnswer
     */
    public String getRavAnswer() {
        return (String) getAttributeInternal(RAVANSWER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavAnswer
     */
    public void setRavAnswer(String value) {
        setAttributeInternal(RAVANSWER, value);
    }

    /**Gets the attribute value for the calculated attribute RavDisplaySeq
     */
    public Number getRavDisplaySeq() {
        return (Number) getAttributeInternal(RAVDISPLAYSEQ);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavDisplaySeq
     */
    public void setRavDisplaySeq(Number value) {
        setAttributeInternal(RAVDISPLAYSEQ, value);
    }

    /**Gets the attribute value for the calculated attribute RavAsvId
     */
    public Number getRavAsvId() {
        return (Number) getAttributeInternal(RAVASVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavAsvId
     */
    public void setRavAsvId(Number value) {
        setAttributeInternal(RAVASVID, value);
    }

    /**Gets the attribute value for the calculated attribute RavDeleteYn
     */
    public String getRavDeleteYn() {
        return (String) getAttributeInternal(RAVDELETEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RavDeleteYn
     */
    public void setRavDeleteYn(String value) {
        setAttributeInternal(RAVDELETEYN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RAVID:
            return getRavId();
        case RAVRASID:
            return getRavRasId();
        case RAVANSWER:
            return getRavAnswer();
        case RAVDISPLAYSEQ:
            return getRavDisplaySeq();
        case RAVASVID:
            return getRavAsvId();
        case RAVDELETEYN:
            return getRavDeleteYn();
        case BaWaWEBSOURCEANSWERSRVIEW:
            return getOtlSourceAnswersRView();
        case BaWaWEBSOURCEMULTIANSWERSRVIEW:
            return getOtlSourceMultiAnswersRView();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlSourceAnswersRView
     */
    public RowIterator getOtlSourceAnswersRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBSOURCEANSWERSRVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlSourceMultiAnswersRView
     */
    public RowIterator getOtlSourceMultiAnswersRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBSOURCEMULTIANSWERSRVIEW);
    }

    /**Gets OtlReportAnswerSetValues entity object.
     */
    public OtlReportAnswerSetValuesImpl getOtlReportAnswerSetValues() {
        return (OtlReportAnswerSetValuesImpl)getEntity(0);
    }
}
