package com.bawaweb.views.readable;

import com.bawaweb.model.OtlReportAnswerSetsImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlReportAnswerSetsRViewRowImpl extends ViewRowImpl {
    public static final int RASID = 0;
    public static final int RASRPRTID = 1;
    public static final int RASANSID = 2;
    public static final int RASNAME = 3;
    public static final int RASFRIDID = 4;
    public static final int RASORDERBYNAMEYN = 5;
    public static final int RASADDANSWERYN = 6;
    public static final int RASDELETEYN = 7;
    public static final int BaWaWEBREPORTANSWERSETVALUESRVIEW = 8;

    /**This is the default constructor (do not remove)
     */
    public OtlReportAnswerSetsRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RasId
     */
    public Number getRasId() {
        return (Number) getAttributeInternal(RASID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RasId
     */
    public void setRasId(Number value) {
        setAttributeInternal(RASID, value);
    }

    /**Gets the attribute value for the calculated attribute RasRprtId
     */
    public Number getRasRprtId() {
        return (Number) getAttributeInternal(RASRPRTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RasRprtId
     */
    public void setRasRprtId(Number value) {
        setAttributeInternal(RASRPRTID, value);
    }

    /**Gets the attribute value for the calculated attribute RasAnsId
     */
    public Number getRasAnsId() {
        return (Number) getAttributeInternal(RASANSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RasAnsId
     */
    public void setRasAnsId(Number value) {
        setAttributeInternal(RASANSID, value);
    }

    /**Gets the attribute value for the calculated attribute RasName
     */
    public String getRasName() {
        return (String) getAttributeInternal(RASNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RasName
     */
    public void setRasName(String value) {
        setAttributeInternal(RASNAME, value);
    }

    /**Gets the attribute value for the calculated attribute RasFridId
     */
    public Number getRasFridId() {
        return (Number) getAttributeInternal(RASFRIDID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RasFridId
     */
    public void setRasFridId(Number value) {
        setAttributeInternal(RASFRIDID, value);
    }

    /**Gets the attribute value for the calculated attribute RasOrderByNameYn
     */
    public String getRasOrderByNameYn() {
        return (String) getAttributeInternal(RASORDERBYNAMEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RasOrderByNameYn
     */
    public void setRasOrderByNameYn(String value) {
        setAttributeInternal(RASORDERBYNAMEYN, value);
    }

    /**Gets the attribute value for the calculated attribute RasAddAnswerYn
     */
    public String getRasAddAnswerYn() {
        return (String) getAttributeInternal(RASADDANSWERYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RasAddAnswerYn
     */
    public void setRasAddAnswerYn(String value) {
        setAttributeInternal(RASADDANSWERYN, value);
    }

    /**Gets the attribute value for the calculated attribute RasDeleteYn
     */
    public String getRasDeleteYn() {
        return (String) getAttributeInternal(RASDELETEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RasDeleteYn
     */
    public void setRasDeleteYn(String value) {
        setAttributeInternal(RASDELETEYN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RASID:
            return getRasId();
        case RASRPRTID:
            return getRasRprtId();
        case RASANSID:
            return getRasAnsId();
        case RASNAME:
            return getRasName();
        case RASFRIDID:
            return getRasFridId();
        case RASORDERBYNAMEYN:
            return getRasOrderByNameYn();
        case RASADDANSWERYN:
            return getRasAddAnswerYn();
        case RASDELETEYN:
            return getRasDeleteYn();
        case BaWaWEBREPORTANSWERSETVALUESRVIEW:
            return getOtlReportAnswerSetValuesRView();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlReportAnswerSetValuesRView
     */
    public RowIterator getOtlReportAnswerSetValuesRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBREPORTANSWERSETVALUESRVIEW);
    }

    /**Gets OtlReportAnswerSets entity object.
     */
    public OtlReportAnswerSetsImpl getOtlReportAnswerSets() {
        return (OtlReportAnswerSetsImpl)getEntity(0);
    }
}
