package com.bawaweb.views.readable;

import com.bawaweb.model.OtlReportSortingCriteriaImpl;

import com.bawaweb.views.readable.common.OtlReportSortingCriteriaRViewRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlReportSortingCriteriaRViewRowImpl extends ViewRowImpl implements OtlReportSortingCriteriaRViewRow {
    public static final int RSORPRTID = 0;
    public static final int RSOSRTID = 1;
    public static final int RSODISPLAYSEQ = 2;

    /**This is the default constructor (do not remove)
     */
    public OtlReportSortingCriteriaRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RsoRprtId
     */
    public Number getRsoRprtId() {
        return (Number) getAttributeInternal(RSORPRTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RsoRprtId
     */
    public void setRsoRprtId(Number value) {
        setAttributeInternal(RSORPRTID, value);
    }

    /**Gets the attribute value for the calculated attribute RsoSrtId
     */
    public Number getRsoSrtId() {
        return (Number) getAttributeInternal(RSOSRTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RsoSrtId
     */
    public void setRsoSrtId(Number value) {
        setAttributeInternal(RSOSRTID, value);
    }

    /**Gets the attribute value for the calculated attribute RsoDisplaySeq
     */
    public Number getRsoDisplaySeq() {
        return (Number) getAttributeInternal(RSODISPLAYSEQ);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RsoDisplaySeq
     */
    public void setRsoDisplaySeq(Number value) {
        setAttributeInternal(RSODISPLAYSEQ, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RSORPRTID:
            return getRsoRprtId();
        case RSOSRTID:
            return getRsoSrtId();
        case RSODISPLAYSEQ:
            return getRsoDisplaySeq();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets OtlReportSortingCriteria entity object.
     */
    public OtlReportSortingCriteriaImpl getOtlReportSortingCriteria() {
        return (OtlReportSortingCriteriaImpl)getEntity(0);
    }
}
