package com.bawaweb.views.readable;

import com.bawaweb.model.OtlSourceAnswersImpl;

import com.bawaweb.views.readable.common.OtlSourceAnswersRViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlSourceAnswersRViewRowImpl extends ViewRowImpl implements OtlSourceAnswersRViewRow {
    public static final int SRAID = 0;
    public static final int SRAQSTID = 1;
    public static final int SRARPSID = 2;
    public static final int SRAANSWER = 3;
    public static final int SRAANSWERTEXT = 4;
    public static final int SRAASVID = 5;
    public static final int SRAEXCLUDEYN = 6;
    public static final int SRAWEIGHTMULTIPLIER = 7;
    public static final int SRARAVID = 8;
    public static final int SRACOLOR = 9;
    public static final int SRACOMMENT = 10;
    public static final int BaWaWEBSOURCEMULTIANSWERSRVIEW = 11;

    /**This is the default constructor (do not remove)
     */
    public OtlSourceAnswersRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute SraId
     */
    public Number getSraId() {
        return (Number) getAttributeInternal(SRAID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraId
     */
    public void setSraId(Number value) {
        setAttributeInternal(SRAID, value);
    }

    /**Gets the attribute value for the calculated attribute SraQstId
     */
    public Number getSraQstId() {
        return (Number) getAttributeInternal(SRAQSTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraQstId
     */
    public void setSraQstId(Number value) {
        setAttributeInternal(SRAQSTID, value);
    }

    /**Gets the attribute value for the calculated attribute SraRpsId
     */
    public Number getSraRpsId() {
        return (Number) getAttributeInternal(SRARPSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraRpsId
     */
    public void setSraRpsId(Number value) {
        setAttributeInternal(SRARPSID, value);
    }

    /**Gets the attribute value for the calculated attribute SraAnswer
     */
    public String getSraAnswer() {
        return (String) getAttributeInternal(SRAANSWER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraAnswer
     */
    public void setSraAnswer(String value) {
        setAttributeInternal(SRAANSWER, value);
    }

    /**Gets the attribute value for the calculated attribute SraAnswerText
     */
    public String getSraAnswerText() {
        return (String) getAttributeInternal(SRAANSWERTEXT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraAnswerText
     */
    public void setSraAnswerText(String value) {
        setAttributeInternal(SRAANSWERTEXT, value);
    }

    /**Gets the attribute value for the calculated attribute SraAsvId
     */
    public Number getSraAsvId() {
        return (Number) getAttributeInternal(SRAASVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraAsvId
     */
    public void setSraAsvId(Number value) {
        setAttributeInternal(SRAASVID, value);
    }

    /**Gets the attribute value for the calculated attribute SraExcludeYn
     */
    public String getSraExcludeYn() {
        return (String) getAttributeInternal(SRAEXCLUDEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraExcludeYn
     */
    public void setSraExcludeYn(String value) {
        setAttributeInternal(SRAEXCLUDEYN, value);
    }

    /**Gets the attribute value for the calculated attribute SraWeightMultiplier
     */
    public Number getSraWeightMultiplier() {
        return (Number) getAttributeInternal(SRAWEIGHTMULTIPLIER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraWeightMultiplier
     */
    public void setSraWeightMultiplier(Number value) {
        setAttributeInternal(SRAWEIGHTMULTIPLIER, value);
    }

    /**Gets the attribute value for the calculated attribute SraRavId
     */
    public Number getSraRavId() {
        return (Number) getAttributeInternal(SRARAVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraRavId
     */
    public void setSraRavId(Number value) {
        setAttributeInternal(SRARAVID, value);
    }

    /**Gets the attribute value for the calculated attribute SraColor
     */
    public String getSraColor() {
        return (String) getAttributeInternal(SRACOLOR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraColor
     */
    public void setSraColor(String value) {
        setAttributeInternal(SRACOLOR, value);
    }

    /**Gets the attribute value for the calculated attribute SraComment
     */
    public String getSraComment() {
        return (String) getAttributeInternal(SRACOMMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SraComment
     */
    public void setSraComment(String value) {
        setAttributeInternal(SRACOMMENT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SRAID:
            return getSraId();
        case SRAQSTID:
            return getSraQstId();
        case SRARPSID:
            return getSraRpsId();
        case SRAANSWER:
            return getSraAnswer();
        case SRAANSWERTEXT:
            return getSraAnswerText();
        case SRAASVID:
            return getSraAsvId();
        case SRAEXCLUDEYN:
            return getSraExcludeYn();
        case SRAWEIGHTMULTIPLIER:
            return getSraWeightMultiplier();
        case SRARAVID:
            return getSraRavId();
        case SRACOLOR:
            return getSraColor();
        case SRACOMMENT:
            return getSraComment();
        case BaWaWEBSOURCEMULTIANSWERSRVIEW:
            return getOtlSourceMultiAnswersRView();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlSourceMultiAnswersRView
     */
    public RowIterator getOtlSourceMultiAnswersRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBSOURCEMULTIANSWERSRVIEW);
    }

    /**Gets OtlSourceAnswers entity object.
     */
    public OtlSourceAnswersImpl getOtlSourceAnswers() {
        return (OtlSourceAnswersImpl)getEntity(0);
    }
}
