package com.bawaweb.views.readable;

import com.bawaweb.model.OtlSourceMultiAnswersImpl;

import com.bawaweb.views.readable.common.OtlSourceMultiAnswersRViewRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlSourceMultiAnswersRViewRowImpl extends ViewRowImpl implements OtlSourceMultiAnswersRViewRow {
    public static final int SMASRAID = 0;
    public static final int SMAANSWER = 1;
    public static final int SMAASVID = 2;
    public static final int SMAQMQID = 3;
    public static final int SMAEXCLUDEYN = 4;
    public static final int SMAWEIGHTMULTIPLIER = 5;
    public static final int SMARAVID = 6;

    /**This is the default constructor (do not remove)
     */
    public OtlSourceMultiAnswersRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute SmaSraId
     */
    public Number getSmaSraId() {
        return (Number) getAttributeInternal(SMASRAID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaSraId
     */
    public void setSmaSraId(Number value) {
        setAttributeInternal(SMASRAID, value);
    }

    /**Gets the attribute value for the calculated attribute SmaAnswer
     */
    public String getSmaAnswer() {
        return (String) getAttributeInternal(SMAANSWER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaAnswer
     */
    public void setSmaAnswer(String value) {
        setAttributeInternal(SMAANSWER, value);
    }

    /**Gets the attribute value for the calculated attribute SmaAsvId
     */
    public Number getSmaAsvId() {
        return (Number) getAttributeInternal(SMAASVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaAsvId
     */
    public void setSmaAsvId(Number value) {
        setAttributeInternal(SMAASVID, value);
    }

    /**Gets the attribute value for the calculated attribute SmaQmqId
     */
    public Number getSmaQmqId() {
        return (Number) getAttributeInternal(SMAQMQID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaQmqId
     */
    public void setSmaQmqId(Number value) {
        setAttributeInternal(SMAQMQID, value);
    }

    /**Gets the attribute value for the calculated attribute SmaExcludeYn
     */
    public String getSmaExcludeYn() {
        return (String) getAttributeInternal(SMAEXCLUDEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaExcludeYn
     */
    public void setSmaExcludeYn(String value) {
        setAttributeInternal(SMAEXCLUDEYN, value);
    }

    /**Gets the attribute value for the calculated attribute SmaWeightMultiplier
     */
    public Number getSmaWeightMultiplier() {
        return (Number) getAttributeInternal(SMAWEIGHTMULTIPLIER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaWeightMultiplier
     */
    public void setSmaWeightMultiplier(Number value) {
        setAttributeInternal(SMAWEIGHTMULTIPLIER, value);
    }

    /**Gets the attribute value for the calculated attribute SmaRavId
     */
    public Number getSmaRavId() {
        return (Number) getAttributeInternal(SMARAVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SmaRavId
     */
    public void setSmaRavId(Number value) {
        setAttributeInternal(SMARAVID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SMASRAID:
            return getSmaSraId();
        case SMAANSWER:
            return getSmaAnswer();
        case SMAASVID:
            return getSmaAsvId();
        case SMAQMQID:
            return getSmaQmqId();
        case SMAEXCLUDEYN:
            return getSmaExcludeYn();
        case SMAWEIGHTMULTIPLIER:
            return getSmaWeightMultiplier();
        case SMARAVID:
            return getSmaRavId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets OtlSourceMultiAnswers entity object.
     */
    public OtlSourceMultiAnswersImpl getOtlSourceMultiAnswers() {
        return (OtlSourceMultiAnswersImpl)getEntity(0);
    }
}
