package com.bawaweb.views.readable;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlTallyRangeLimitsRViewRowImpl extends ViewRowImpl {
    public static final int TRLID = 0;
    public static final int TRLTLYID = 1;
    public static final int TRLFROM = 2;
    public static final int TRLTO = 3;
    public static final int TRLDISPLAYSEQ = 4;
    public static final int TRLTYPE = 5;
    public static final int TRLDELETEYN = 6;

    /**This is the default constructor (do not remove)
     */
    public OtlTallyRangeLimitsRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute TrlId
     */
    public Number getTrlId() {
        return (Number) getAttributeInternal(TRLID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TrlId
     */
    public void setTrlId(Number value) {
        setAttributeInternal(TRLID, value);
    }

    /**Gets the attribute value for the calculated attribute TrlTlyId
     */
    public Number getTrlTlyId() {
        return (Number) getAttributeInternal(TRLTLYID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TrlTlyId
     */
    public void setTrlTlyId(Number value) {
        setAttributeInternal(TRLTLYID, value);
    }

    /**Gets the attribute value for the calculated attribute TrlFrom
     */
    public String getTrlFrom() {
        return (String) getAttributeInternal(TRLFROM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TrlFrom
     */
    public void setTrlFrom(String value) {
        setAttributeInternal(TRLFROM, value);
    }

    /**Gets the attribute value for the calculated attribute TrlTo
     */
    public String getTrlTo() {
        return (String) getAttributeInternal(TRLTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TrlTo
     */
    public void setTrlTo(String value) {
        setAttributeInternal(TRLTO, value);
    }

    /**Gets the attribute value for the calculated attribute TrlDisplaySeq
     */
    public Number getTrlDisplaySeq() {
        return (Number) getAttributeInternal(TRLDISPLAYSEQ);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TrlDisplaySeq
     */
    public void setTrlDisplaySeq(Number value) {
        setAttributeInternal(TRLDISPLAYSEQ, value);
    }

    /**Gets the attribute value for the calculated attribute TrlType
     */
    public String getTrlType() {
        return (String) getAttributeInternal(TRLTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TrlType
     */
    public void setTrlType(String value) {
        setAttributeInternal(TRLTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute TrlDeleteYn
     */
    public String getTrlDeleteYn() {
        return (String) getAttributeInternal(TRLDELETEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TrlDeleteYn
     */
    public void setTrlDeleteYn(String value) {
        setAttributeInternal(TRLDELETEYN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TRLID:
            return getTrlId();
        case TRLTLYID:
            return getTrlTlyId();
        case TRLFROM:
            return getTrlFrom();
        case TRLTO:
            return getTrlTo();
        case TRLDISPLAYSEQ:
            return getTrlDisplaySeq();
        case TRLTYPE:
            return getTrlType();
        case TRLDELETEYN:
            return getTrlDeleteYn();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
