package com.bawaweb.views.readable;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtrEmployeeInfoRViewRowImpl extends ViewRowImpl {
    public static final int LASTNAME = 0;
    public static final int FIRSTNAME = 1;
    public static final int TITLE = 2;
    public static final int DEPARTMENT = 3;
    public static final int SECTORS = 4;
    public static final int COUNTRY = 5;
    public static final int REGION = 6;
    public static final int SHORTBIO = 7;
    public static final int LONGBIO = 8;
    public static final int REPORTSTO = 9;
    public static final int OTRSINCE = 10;
    public static final int ADDITIONALEXPERTISE = 11;
    public static final int COVERS = 12;

    /**This is the default constructor (do not remove)
     */
    public OtrEmployeeInfoRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Title
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Title
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**Gets the attribute value for the calculated attribute Department
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Department
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**Gets the attribute value for the calculated attribute Sectors
     */
    public String getSectors() {
        return (String) getAttributeInternal(SECTORS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sectors
     */
    public void setSectors(String value) {
        setAttributeInternal(SECTORS, value);
    }

    /**Gets the attribute value for the calculated attribute Country
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**Gets the attribute value for the calculated attribute Region
     */
    public String getRegion() {
        return (String) getAttributeInternal(REGION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Region
     */
    public void setRegion(String value) {
        setAttributeInternal(REGION, value);
    }

    /**Gets the attribute value for the calculated attribute ShortBio
     */
    public String getShortBio() {
        return (String) getAttributeInternal(SHORTBIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ShortBio
     */
    public void setShortBio(String value) {
        setAttributeInternal(SHORTBIO, value);
    }

    /**Gets the attribute value for the calculated attribute LongBio
     */
    public String getLongBio() {
        return (String) getAttributeInternal(LONGBIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LongBio
     */
    public void setLongBio(String value) {
        setAttributeInternal(LONGBIO, value);
    }

    /**Gets the attribute value for the calculated attribute ReportsTo
     */
    public String getReportsTo() {
        return (String) getAttributeInternal(REPORTSTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReportsTo
     */
    public void setReportsTo(String value) {
        setAttributeInternal(REPORTSTO, value);
    }

    /**Gets the attribute value for the calculated attribute OtrSince
     */
    public String getOtrSince() {
        return (String) getAttributeInternal(OTRSINCE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OtrSince
     */
    public void setOtrSince(String value) {
        setAttributeInternal(OTRSINCE, value);
    }

    /**Gets the attribute value for the calculated attribute AdditionalExpertise
     */
    public String getAdditionalExpertise() {
        return (String) getAttributeInternal(ADDITIONALEXPERTISE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AdditionalExpertise
     */
    public void setAdditionalExpertise(String value) {
        setAttributeInternal(ADDITIONALEXPERTISE, value);
    }

    /**Gets the attribute value for the calculated attribute Covers
     */
    public String getCovers() {
        return (String) getAttributeInternal(COVERS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Covers
     */
    public void setCovers(String value) {
        setAttributeInternal(COVERS, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LASTNAME:
            return getLastName();
        case FIRSTNAME:
            return getFirstName();
        case TITLE:
            return getTitle();
        case DEPARTMENT:
            return getDepartment();
        case SECTORS:
            return getSectors();
        case COUNTRY:
            return getCountry();
        case REGION:
            return getRegion();
        case SHORTBIO:
            return getShortBio();
        case LONGBIO:
            return getLongBio();
        case REPORTSTO:
            return getReportsTo();
        case OTRSINCE:
            return getOtrSince();
        case ADDITIONALEXPERTISE:
            return getAdditionalExpertise();
        case COVERS:
            return getCovers();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
