package com.bawaweb.views.readable;

import com.bawaweb.model.RprtReportReporterXrefImpl;

import com.bawaweb.views.readable.common.RprtReportReporterXrefRViewRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RprtReportReporterXrefRViewRowImpl extends ViewRowImpl implements RprtReportReporterXrefRViewRow {
    public static final int RPRTID = 0;
    public static final int RPTRID = 1;
    public static final int RPTYID = 2;
    public static final int DISTRIBUTIONNOTES = 3;

    /**This is the default constructor (do not remove)
     */
    public RprtReportReporterXrefRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RprtId
     */
    public Number getRprtId() {
        return (Number) getAttributeInternal(RPRTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtId
     */
    public void setRprtId(Number value) {
        setAttributeInternal(RPRTID, value);
    }

    /**Gets the attribute value for the calculated attribute RptrId
     */
    public Number getRptrId() {
        return (Number) getAttributeInternal(RPTRID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RptrId
     */
    public void setRptrId(Number value) {
        setAttributeInternal(RPTRID, value);
    }

    /**Gets the attribute value for the calculated attribute RptyId
     */
    public Number getRptyId() {
        return (Number) getAttributeInternal(RPTYID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RptyId
     */
    public void setRptyId(Number value) {
        setAttributeInternal(RPTYID, value);
    }

    /**Gets the attribute value for the calculated attribute DistributionNotes
     */
    public String getDistributionNotes() {
        return (String) getAttributeInternal(DISTRIBUTIONNOTES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DistributionNotes
     */
    public void setDistributionNotes(String value) {
        setAttributeInternal(DISTRIBUTIONNOTES, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RPRTID:
            return getRprtId();
        case RPTRID:
            return getRptrId();
        case RPTYID:
            return getRptyId();
        case DISTRIBUTIONNOTES:
            return getDistributionNotes();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets RprtReportReporterXref entity object.
     */
    public RprtReportReporterXrefImpl getRprtReportReporterXref() {
        return (RprtReportReporterXrefImpl)getEntity(0);
    }
}
