package com.bawaweb.views.readable;

import com.bawaweb.views.readable.common.RprtReportsRViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RprtReportsRViewRowImpl extends ViewRowImpl implements RprtReportsRViewRow {
    public static final int RPRTID = 0;
    public static final int RPRTDESC = 1;
    public static final int RPRTPDF = 2;
    public static final int RPSTID = 3;
    public static final int RTYPID = 4;
    public static final int RPTRID = 5;
    public static final int EDTRID = 6;
    public static final int RPRTISPROPRIETARY = 7;
    public static final int RPRTREPORTDATE = 8;
    public static final int RPRTDUEDATE = 9;
    public static final int RPRTCOMPLETEDDATE = 10;
    public static final int RPRTPRODCODE = 11;
    public static final int RPRTMKTCAP = 12;
    public static final int RPRTISCOFOCUS = 13;
    public static final int RPRTISSMALLCAP = 14;
    public static final int RPRTISTHUMBSUP = 15;
    public static final int RPRTLASTISTHUMBSUP = 16;
    public static final int RPRTACCURACYINDEX = 17;
    public static final int RPRTHIGHLIGHTS = 18;
    public static final int LASTUPDATEDATE = 19;
    public static final int LASTUPDATEBY = 20;
    public static final int OLDID = 21;
    public static final int RPRTNOTES = 22;
    public static final int INDRCODE = 23;
    public static final int INDUSTRY = 24;
    public static final int FLASHPARENT = 25;
    public static final int RPRTAHA = 26;
    public static final int ISDELETED = 27;
    public static final int IVSTID = 28;
    public static final int RPRTISCLASSIFIED = 29;
    public static final int FRIDID = 30;
    public static final int RPRTRESEARCHIN = 31;
    public static final int RPRTINTLDUEDATE = 32;
    public static final int RPRTIMPORTANCERATING = 33;
    public static final int RPRTRDPERSON = 34;
    public static final int RPRTPROPAPPR = 35;
    public static final int PANID = 36;
    public static final int RPRTIDEAGENIND = 37;
    public static final int RPRTHITBONUS = 38;
    public static final int RPRTTOPSTORYOFFDATE = 39;
    public static final int RPRTSOURCEDISPLAYFIELD = 40;
    public static final int RPRTREPORTERSVIEWALLYN = 41;
    public static final int RPRTSOURCEREPORT = 42;
    public static final int RPRTSCHEDULINGNOTES = 43;
    public static final int RPRTGROUPNOTES = 44;
    public static final int RPRTPARENTID = 45;
    public static final int RPRTPROPCOST = 46;
    public static final int RPRTLAUNCHDATE = 47;
    public static final int RPRTHOLDSOURCEDIST = 48;
    public static final int RPRTSOURCES = 49;
    public static final int RPRTREPEATSRCS = 50;
    public static final int RPRTFIELDFORCEVISITS = 51;
    public static final int SCSTID = 52;
    public static final int RPRTLATERSCHED = 53;
    public static final int RPRTHIDEFROMSCHEDULEYN = 54;
    public static final int RPRTRSMVID = 55;
    public static final int BaWaWEBQUESTIONSRVIEW = 56;
    public static final int BaWaWEBREPORTANSWERSETSRVIEW = 57;
    public static final int BaWaWEBREPORTSORTINGCRITERIARVIEW = 58;
    public static final int BaWaWEBREPORTSOURCESRVIEW = 59;

    /**This is the default constructor (do not remove)
     */
    public RprtReportsRViewRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RprtId
     */
    public Number getRprtId() {
        return (Number) getAttributeInternal(RPRTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtId
     */
    public void setRprtId(Number value) {
        setAttributeInternal(RPRTID, value);
    }

    /**Gets the attribute value for the calculated attribute RprtDesc
     */
    public String getRprtDesc() {
        return (String) getAttributeInternal(RPRTDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtDesc
     */
    public void setRprtDesc(String value) {
        setAttributeInternal(RPRTDESC, value);
    }

    /**Gets the attribute value for the calculated attribute RprtPdf
     */
    public String getRprtPdf() {
        return (String) getAttributeInternal(RPRTPDF);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtPdf
     */
    public void setRprtPdf(String value) {
        setAttributeInternal(RPRTPDF, value);
    }

    /**Gets the attribute value for the calculated attribute RpstId
     */
    public Number getRpstId() {
        return (Number) getAttributeInternal(RPSTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RpstId
     */
    public void setRpstId(Number value) {
        setAttributeInternal(RPSTID, value);
    }

    /**Gets the attribute value for the calculated attribute RtypId
     */
    public Number getRtypId() {
        return (Number) getAttributeInternal(RTYPID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RtypId
     */
    public void setRtypId(Number value) {
        setAttributeInternal(RTYPID, value);
    }

    /**Gets the attribute value for the calculated attribute RptrId
     */
    public Number getRptrId() {
        return (Number) getAttributeInternal(RPTRID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RptrId
     */
    public void setRptrId(Number value) {
        setAttributeInternal(RPTRID, value);
    }

    /**Gets the attribute value for the calculated attribute EdtrId
     */
    public Number getEdtrId() {
        return (Number) getAttributeInternal(EDTRID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EdtrId
     */
    public void setEdtrId(Number value) {
        setAttributeInternal(EDTRID, value);
    }

    /**Gets the attribute value for the calculated attribute RprtIsproprietary
     */
    public Number getRprtIsproprietary() {
        return (Number) getAttributeInternal(RPRTISPROPRIETARY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtIsproprietary
     */
    public void setRprtIsproprietary(Number value) {
        setAttributeInternal(RPRTISPROPRIETARY, value);
    }

    /**Gets the attribute value for the calculated attribute RprtReportdate
     */
    public Date getRprtReportdate() {
        return (Date) getAttributeInternal(RPRTREPORTDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtReportdate
     */
    public void setRprtReportdate(Date value) {
        setAttributeInternal(RPRTREPORTDATE, value);
    }

    /**Gets the attribute value for the calculated attribute RprtDuedate
     */
    public Date getRprtDuedate() {
        return (Date) getAttributeInternal(RPRTDUEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtDuedate
     */
    public void setRprtDuedate(Date value) {
        setAttributeInternal(RPRTDUEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute RprtCompleteddate
     */
    public Date getRprtCompleteddate() {
        return (Date) getAttributeInternal(RPRTCOMPLETEDDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtCompleteddate
     */
    public void setRprtCompleteddate(Date value) {
        setAttributeInternal(RPRTCOMPLETEDDATE, value);
    }

    /**Gets the attribute value for the calculated attribute RprtProdcode
     */
    public String getRprtProdcode() {
        return (String) getAttributeInternal(RPRTPRODCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtProdcode
     */
    public void setRprtProdcode(String value) {
        setAttributeInternal(RPRTPRODCODE, value);
    }

    /**Gets the attribute value for the calculated attribute RprtMktcap
     */
    public String getRprtMktcap() {
        return (String) getAttributeInternal(RPRTMKTCAP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtMktcap
     */
    public void setRprtMktcap(String value) {
        setAttributeInternal(RPRTMKTCAP, value);
    }

    /**Gets the attribute value for the calculated attribute RprtIscofocus
     */
    public Number getRprtIscofocus() {
        return (Number) getAttributeInternal(RPRTISCOFOCUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtIscofocus
     */
    public void setRprtIscofocus(Number value) {
        setAttributeInternal(RPRTISCOFOCUS, value);
    }

    /**Gets the attribute value for the calculated attribute RprtIssmallcap
     */
    public Number getRprtIssmallcap() {
        return (Number) getAttributeInternal(RPRTISSMALLCAP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtIssmallcap
     */
    public void setRprtIssmallcap(Number value) {
        setAttributeInternal(RPRTISSMALLCAP, value);
    }

    /**Gets the attribute value for the calculated attribute RprtIsthumbsup
     */
    public String getRprtIsthumbsup() {
        return (String) getAttributeInternal(RPRTISTHUMBSUP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtIsthumbsup
     */
    public void setRprtIsthumbsup(String value) {
        setAttributeInternal(RPRTISTHUMBSUP, value);
    }

    /**Gets the attribute value for the calculated attribute RprtLastisthumbsup
     */
    public String getRprtLastisthumbsup() {
        return (String) getAttributeInternal(RPRTLASTISTHUMBSUP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtLastisthumbsup
     */
    public void setRprtLastisthumbsup(String value) {
        setAttributeInternal(RPRTLASTISTHUMBSUP, value);
    }

    /**Gets the attribute value for the calculated attribute RprtAccuracyindex
     */
    public String getRprtAccuracyindex() {
        return (String) getAttributeInternal(RPRTACCURACYINDEX);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtAccuracyindex
     */
    public void setRprtAccuracyindex(String value) {
        setAttributeInternal(RPRTACCURACYINDEX, value);
    }

    /**Gets the attribute value for the calculated attribute RprtHighlights
     */
    public String getRprtHighlights() {
        return (String) getAttributeInternal(RPRTHIGHLIGHTS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtHighlights
     */
    public void setRprtHighlights(String value) {
        setAttributeInternal(RPRTHIGHLIGHTS, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateBy
     */
    public Number getLastUpdateBy() {
        return (Number) getAttributeInternal(LASTUPDATEBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateBy
     */
    public void setLastUpdateBy(Number value) {
        setAttributeInternal(LASTUPDATEBY, value);
    }

    /**Gets the attribute value for the calculated attribute Oldid
     */
    public Number getOldid() {
        return (Number) getAttributeInternal(OLDID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Oldid
     */
    public void setOldid(Number value) {
        setAttributeInternal(OLDID, value);
    }

    /**Gets the attribute value for the calculated attribute RprtNotes
     */
    public String getRprtNotes() {
        return (String) getAttributeInternal(RPRTNOTES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtNotes
     */
    public void setRprtNotes(String value) {
        setAttributeInternal(RPRTNOTES, value);
    }

    /**Gets the attribute value for the calculated attribute IndrCode
     */
    public Number getIndrCode() {
        return (Number) getAttributeInternal(INDRCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IndrCode
     */
    public void setIndrCode(Number value) {
        setAttributeInternal(INDRCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Industry
     */
    public String getIndustry() {
        return (String) getAttributeInternal(INDUSTRY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Industry
     */
    public void setIndustry(String value) {
        setAttributeInternal(INDUSTRY, value);
    }

    /**Gets the attribute value for the calculated attribute FlashParent
     */
    public Number getFlashParent() {
        return (Number) getAttributeInternal(FLASHPARENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FlashParent
     */
    public void setFlashParent(Number value) {
        setAttributeInternal(FLASHPARENT, value);
    }

    /**Gets the attribute value for the calculated attribute RprtAha
     */
    public Number getRprtAha() {
        return (Number) getAttributeInternal(RPRTAHA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtAha
     */
    public void setRprtAha(Number value) {
        setAttributeInternal(RPRTAHA, value);
    }

    /**Gets the attribute value for the calculated attribute IsDeleted
     */
    public Number getIsDeleted() {
        return (Number) getAttributeInternal(ISDELETED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsDeleted
     */
    public void setIsDeleted(Number value) {
        setAttributeInternal(ISDELETED, value);
    }

    /**Gets the attribute value for the calculated attribute IvstId
     */
    public Number getIvstId() {
        return (Number) getAttributeInternal(IVSTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IvstId
     */
    public void setIvstId(Number value) {
        setAttributeInternal(IVSTID, value);
    }

    /**Gets the attribute value for the calculated attribute RprtIsclassified
     */
    public Number getRprtIsclassified() {
        return (Number) getAttributeInternal(RPRTISCLASSIFIED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtIsclassified
     */
    public void setRprtIsclassified(Number value) {
        setAttributeInternal(RPRTISCLASSIFIED, value);
    }

    /**Gets the attribute value for the calculated attribute FridId
     */
    public Number getFridId() {
        return (Number) getAttributeInternal(FRIDID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FridId
     */
    public void setFridId(Number value) {
        setAttributeInternal(FRIDID, value);
    }

    /**Gets the attribute value for the calculated attribute RprtResearchin
     */
    public Date getRprtResearchin() {
        return (Date) getAttributeInternal(RPRTRESEARCHIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtResearchin
     */
    public void setRprtResearchin(Date value) {
        setAttributeInternal(RPRTRESEARCHIN, value);
    }

    /**Gets the attribute value for the calculated attribute RprtIntlDuedate
     */
    public Date getRprtIntlDuedate() {
        return (Date) getAttributeInternal(RPRTINTLDUEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtIntlDuedate
     */
    public void setRprtIntlDuedate(Date value) {
        setAttributeInternal(RPRTINTLDUEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute RprtImportanceRating
     */
    public Number getRprtImportanceRating() {
        return (Number) getAttributeInternal(RPRTIMPORTANCERATING);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtImportanceRating
     */
    public void setRprtImportanceRating(Number value) {
        setAttributeInternal(RPRTIMPORTANCERATING, value);
    }

    /**Gets the attribute value for the calculated attribute RprtRdPerson
     */
    public Number getRprtRdPerson() {
        return (Number) getAttributeInternal(RPRTRDPERSON);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtRdPerson
     */
    public void setRprtRdPerson(Number value) {
        setAttributeInternal(RPRTRDPERSON, value);
    }

    /**Gets the attribute value for the calculated attribute RprtPropAppr
     */
    public Number getRprtPropAppr() {
        return (Number) getAttributeInternal(RPRTPROPAPPR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtPropAppr
     */
    public void setRprtPropAppr(Number value) {
        setAttributeInternal(RPRTPROPAPPR, value);
    }

    /**Gets the attribute value for the calculated attribute PanId
     */
    public Number getPanId() {
        return (Number) getAttributeInternal(PANID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PanId
     */
    public void setPanId(Number value) {
        setAttributeInternal(PANID, value);
    }

    /**Gets the attribute value for the calculated attribute RprtIdeaGenInd
     */
    public Number getRprtIdeaGenInd() {
        return (Number) getAttributeInternal(RPRTIDEAGENIND);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtIdeaGenInd
     */
    public void setRprtIdeaGenInd(Number value) {
        setAttributeInternal(RPRTIDEAGENIND, value);
    }

    /**Gets the attribute value for the calculated attribute RprtHitBonus
     */
    public String getRprtHitBonus() {
        return (String) getAttributeInternal(RPRTHITBONUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtHitBonus
     */
    public void setRprtHitBonus(String value) {
        setAttributeInternal(RPRTHITBONUS, value);
    }

    /**Gets the attribute value for the calculated attribute RprtTopStoryOffDate
     */
    public Date getRprtTopStoryOffDate() {
        return (Date) getAttributeInternal(RPRTTOPSTORYOFFDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtTopStoryOffDate
     */
    public void setRprtTopStoryOffDate(Date value) {
        setAttributeInternal(RPRTTOPSTORYOFFDATE, value);
    }

    /**Gets the attribute value for the calculated attribute RprtSourceDisplayField
     */
    public String getRprtSourceDisplayField() {
        return (String) getAttributeInternal(RPRTSOURCEDISPLAYFIELD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtSourceDisplayField
     */
    public void setRprtSourceDisplayField(String value) {
        setAttributeInternal(RPRTSOURCEDISPLAYFIELD, value);
    }

    /**Gets the attribute value for the calculated attribute RprtReportersViewAllYn
     */
    public String getRprtReportersViewAllYn() {
        return (String) getAttributeInternal(RPRTREPORTERSVIEWALLYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtReportersViewAllYn
     */
    public void setRprtReportersViewAllYn(String value) {
        setAttributeInternal(RPRTREPORTERSVIEWALLYN, value);
    }

    /**Gets the attribute value for the calculated attribute RprtSourceReport
     */
    public String getRprtSourceReport() {
        return (String) getAttributeInternal(RPRTSOURCEREPORT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtSourceReport
     */
    public void setRprtSourceReport(String value) {
        setAttributeInternal(RPRTSOURCEREPORT, value);
    }

    /**Gets the attribute value for the calculated attribute RprtSchedulingNotes
     */
    public String getRprtSchedulingNotes() {
        return (String) getAttributeInternal(RPRTSCHEDULINGNOTES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtSchedulingNotes
     */
    public void setRprtSchedulingNotes(String value) {
        setAttributeInternal(RPRTSCHEDULINGNOTES, value);
    }

    /**Gets the attribute value for the calculated attribute RprtGroupNotes
     */
    public String getRprtGroupNotes() {
        return (String) getAttributeInternal(RPRTGROUPNOTES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtGroupNotes
     */
    public void setRprtGroupNotes(String value) {
        setAttributeInternal(RPRTGROUPNOTES, value);
    }

    /**Gets the attribute value for the calculated attribute RprtParentId
     */
    public Number getRprtParentId() {
        return (Number) getAttributeInternal(RPRTPARENTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtParentId
     */
    public void setRprtParentId(Number value) {
        setAttributeInternal(RPRTPARENTID, value);
    }

    /**Gets the attribute value for the calculated attribute RprtPropCost
     */
    public Number getRprtPropCost() {
        return (Number) getAttributeInternal(RPRTPROPCOST);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtPropCost
     */
    public void setRprtPropCost(Number value) {
        setAttributeInternal(RPRTPROPCOST, value);
    }

    /**Gets the attribute value for the calculated attribute RprtLaunchDate
     */
    public Date getRprtLaunchDate() {
        return (Date) getAttributeInternal(RPRTLAUNCHDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtLaunchDate
     */
    public void setRprtLaunchDate(Date value) {
        setAttributeInternal(RPRTLAUNCHDATE, value);
    }

    /**Gets the attribute value for the calculated attribute RprtHoldSourceDist
     */
    public Number getRprtHoldSourceDist() {
        return (Number) getAttributeInternal(RPRTHOLDSOURCEDIST);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtHoldSourceDist
     */
    public void setRprtHoldSourceDist(Number value) {
        setAttributeInternal(RPRTHOLDSOURCEDIST, value);
    }

    /**Gets the attribute value for the calculated attribute RprtSources
     */
    public Number getRprtSources() {
        return (Number) getAttributeInternal(RPRTSOURCES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtSources
     */
    public void setRprtSources(Number value) {
        setAttributeInternal(RPRTSOURCES, value);
    }

    /**Gets the attribute value for the calculated attribute RprtRepeatSrcs
     */
    public Number getRprtRepeatSrcs() {
        return (Number) getAttributeInternal(RPRTREPEATSRCS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtRepeatSrcs
     */
    public void setRprtRepeatSrcs(Number value) {
        setAttributeInternal(RPRTREPEATSRCS, value);
    }

    /**Gets the attribute value for the calculated attribute RprtFieldForceVisits
     */
    public Number getRprtFieldForceVisits() {
        return (Number) getAttributeInternal(RPRTFIELDFORCEVISITS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtFieldForceVisits
     */
    public void setRprtFieldForceVisits(Number value) {
        setAttributeInternal(RPRTFIELDFORCEVISITS, value);
    }

    /**Gets the attribute value for the calculated attribute ScstId
     */
    public Number getScstId() {
        return (Number) getAttributeInternal(SCSTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ScstId
     */
    public void setScstId(Number value) {
        setAttributeInternal(SCSTID, value);
    }

    /**Gets the attribute value for the calculated attribute RprtLateRsched
     */
    public Number getRprtLateRsched() {
        return (Number) getAttributeInternal(RPRTLATERSCHED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtLateRsched
     */
    public void setRprtLateRsched(Number value) {
        setAttributeInternal(RPRTLATERSCHED, value);
    }

    /**Gets the attribute value for the calculated attribute RprtHideFromScheduleYn
     */
    public String getRprtHideFromScheduleYn() {
        return (String) getAttributeInternal(RPRTHIDEFROMSCHEDULEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtHideFromScheduleYn
     */
    public void setRprtHideFromScheduleYn(String value) {
        setAttributeInternal(RPRTHIDEFROMSCHEDULEYN, value);
    }

    /**Gets the attribute value for the calculated attribute RprtRsmvId
     */
    public Number getRprtRsmvId() {
        return (Number) getAttributeInternal(RPRTRSMVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RprtRsmvId
     */
    public void setRprtRsmvId(Number value) {
        setAttributeInternal(RPRTRSMVID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RPRTID:
            return getRprtId();
        case RPRTDESC:
            return getRprtDesc();
        case RPRTPDF:
            return getRprtPdf();
        case RPSTID:
            return getRpstId();
        case RTYPID:
            return getRtypId();
        case RPTRID:
            return getRptrId();
        case EDTRID:
            return getEdtrId();
        case RPRTISPROPRIETARY:
            return getRprtIsproprietary();
        case RPRTREPORTDATE:
            return getRprtReportdate();
        case RPRTDUEDATE:
            return getRprtDuedate();
        case RPRTCOMPLETEDDATE:
            return getRprtCompleteddate();
        case RPRTPRODCODE:
            return getRprtProdcode();
        case RPRTMKTCAP:
            return getRprtMktcap();
        case RPRTISCOFOCUS:
            return getRprtIscofocus();
        case RPRTISSMALLCAP:
            return getRprtIssmallcap();
        case RPRTISTHUMBSUP:
            return getRprtIsthumbsup();
        case RPRTLASTISTHUMBSUP:
            return getRprtLastisthumbsup();
        case RPRTACCURACYINDEX:
            return getRprtAccuracyindex();
        case RPRTHIGHLIGHTS:
            return getRprtHighlights();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEBY:
            return getLastUpdateBy();
        case OLDID:
            return getOldid();
        case RPRTNOTES:
            return getRprtNotes();
        case INDRCODE:
            return getIndrCode();
        case INDUSTRY:
            return getIndustry();
        case FLASHPARENT:
            return getFlashParent();
        case RPRTAHA:
            return getRprtAha();
        case ISDELETED:
            return getIsDeleted();
        case IVSTID:
            return getIvstId();
        case RPRTISCLASSIFIED:
            return getRprtIsclassified();
        case FRIDID:
            return getFridId();
        case RPRTRESEARCHIN:
            return getRprtResearchin();
        case RPRTINTLDUEDATE:
            return getRprtIntlDuedate();
        case RPRTIMPORTANCERATING:
            return getRprtImportanceRating();
        case RPRTRDPERSON:
            return getRprtRdPerson();
        case RPRTPROPAPPR:
            return getRprtPropAppr();
        case PANID:
            return getPanId();
        case RPRTIDEAGENIND:
            return getRprtIdeaGenInd();
        case RPRTHITBONUS:
            return getRprtHitBonus();
        case RPRTTOPSTORYOFFDATE:
            return getRprtTopStoryOffDate();
        case RPRTSOURCEDISPLAYFIELD:
            return getRprtSourceDisplayField();
        case RPRTREPORTERSVIEWALLYN:
            return getRprtReportersViewAllYn();
        case RPRTSOURCEREPORT:
            return getRprtSourceReport();
        case RPRTSCHEDULINGNOTES:
            return getRprtSchedulingNotes();
        case RPRTGROUPNOTES:
            return getRprtGroupNotes();
        case RPRTPARENTID:
            return getRprtParentId();
        case RPRTPROPCOST:
            return getRprtPropCost();
        case RPRTLAUNCHDATE:
            return getRprtLaunchDate();
        case RPRTHOLDSOURCEDIST:
            return getRprtHoldSourceDist();
        case RPRTSOURCES:
            return getRprtSources();
        case RPRTREPEATSRCS:
            return getRprtRepeatSrcs();
        case RPRTFIELDFORCEVISITS:
            return getRprtFieldForceVisits();
        case SCSTID:
            return getScstId();
        case RPRTLATERSCHED:
            return getRprtLateRsched();
        case RPRTHIDEFROMSCHEDULEYN:
            return getRprtHideFromScheduleYn();
        case RPRTRSMVID:
            return getRprtRsmvId();
        case BaWaWEBQUESTIONSRVIEW:
            return getOtlQuestionsRView();
        case BaWaWEBREPORTANSWERSETSRVIEW:
            return getOtlReportAnswerSetsRView();
        case BaWaWEBREPORTSORTINGCRITERIARVIEW:
            return getOtlReportSortingCriteriaRView();
        case BaWaWEBREPORTSOURCESRVIEW:
            return getOtlReportSourcesRView();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the associated <code>RowIterator</code> using master-detail link OtlReportAnswerSetsRView
     */
    public RowIterator getOtlReportAnswerSetsRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBREPORTANSWERSETSRVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlReportSortingCriteriaRView
     */
    public RowIterator getOtlReportSortingCriteriaRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBREPORTSORTINGCRITERIARVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlReportSourcesRView
     */
    public RowIterator getOtlReportSourcesRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBREPORTSOURCESRVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OtlQuestionsRView
     */
    public RowIterator getOtlQuestionsRView() {
        return (RowIterator)getAttributeInternal(BaWaWEBQUESTIONSRVIEW);
    }
}
