package com.bawaweb.views.model.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlAnswerSetValues extends ViewObject {
    long getEstimatedRowCount();

    Number getasv_id();

    void setasv_id(Number value);
}
