package com.bawaweb.views.model.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface ReporterSources extends ViewObject {
    long getEstimatedRowCount();

    Number getrprtr_id();

    Number getsrc_id();

    void setrprtr_id(Number value);

    void setsrc_id(Number value);
}
