package com.bawaweb.views.model.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface ReportSources extends ViewObject {
    long getEstimatedRowCount();

    Number getrps_id();

    void setrps_id(Number value);

    Number getrprt_id();

    Number getrprtr_id();

    void setrprt_id(Number value);

    void setrprtr_id(Number value);
}
