package com.bawaweb.views.model;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlAnswerSetValuesDefImpl extends ViewDefImpl {
    public OtlAnswerSetValuesDefImpl(String name) {
        super(name);
    }

    /**This is the default constructor (do not remove)
     */
    public OtlAnswerSetValuesDefImpl() {
    }
}
