package com.bawaweb.views.model;

import com.bawaweb.model.OtlSourceSortingCriteriaImpl;

import com.bawaweb.views.model.common.SourceSortingCriteriaRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SourceSortingCriteriaRowImpl extends ViewRowImpl implements SourceSortingCriteriaRow {
    public static final int SSCRPSID = 0;
    public static final int SSCSCVID = 1;

    /**This is the default constructor (do not remove)
     */
    public SourceSortingCriteriaRowImpl() {
    }

    /**Gets OtlSourceSortingCriteria entity object.
     */
    public OtlSourceSortingCriteriaImpl getOtlSourceSortingCriteria() {
        return (OtlSourceSortingCriteriaImpl)getEntity(0);
    }

    /**Gets the attribute value for SSC_RPS_ID using the alias name SscRpsId
     */
    public Number getSscRpsId() {
        return (Number) getAttributeInternal(SSCRPSID);
    }

    /**Sets <code>value</code> as attribute value for SSC_RPS_ID using the alias name SscRpsId
     */
    public void setSscRpsId(Number value) {
        setAttributeInternal(SSCRPSID, value);
    }

    /**Gets the attribute value for SSC_SCV_ID using the alias name SscScvId
     */
    public Number getSscScvId() {
        return (Number) getAttributeInternal(SSCSCVID);
    }

    /**Sets <code>value</code> as attribute value for SSC_SCV_ID using the alias name SscScvId
     */
    public void setSscScvId(Number value) {
        setAttributeInternal(SSCSCVID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SSCRPSID:
            return getSscRpsId();
        case SSCSCVID:
            return getSscScvId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SSCRPSID:
            setSscRpsId((Number)value);
            return;
        case SSCSCVID:
            setSscScvId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
