package com.bawaweb.views.readable.client;

import com.bawaweb.views.readable.common.FridFirmIndustriesRViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FridFirmIndustriesRViewRowClient extends RowImpl implements FridFirmIndustriesRViewRow {
    /**This is the default constructor (do not remove)
     */
    public FridFirmIndustriesRViewRowClient() {
    }


    public RowIterator getOtlAnswerSetsRView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlAnswerSetsRView",null,null);
        return (RowIterator)_ret;
    }

    public RowIterator getOtlReportAnswerSetsRView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlReportAnswerSetsRView",null,null);
        return (RowIterator)_ret;
    }

    public RowIterator getOtlSortingCriteriaRView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlSortingCriteriaRView",null,null);
        return (RowIterator)_ret;
    }

    public RowIterator getPanPanelRView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getPanPanelRView",null,null);
        return (RowIterator)_ret;
    }

    public RowIterator getRprtReportsRView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getRprtReportsRView",null,null);
        return (RowIterator)_ret;
    }

    public String getFridDescription() {
        return (String)getAttribute("FridDescription");
    }

    public Number getFridId() {
        return (Number)getAttribute("FridId");
    }

    public String getFridPropCapacity() {
        return (String)getAttribute("FridPropCapacity");
    }

    public void setFridDescription(String value) {
        setAttribute("FridDescription", value);
    }

    public void setFridId(Number value) {
        setAttribute("FridId", value);
    }

    public void setFridPropCapacity(String value) {
        setAttribute("FridPropCapacity", value);
    }
}
