package com.bawaweb.views.readable.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlEmplRolesRViewRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public OtlEmplRolesRViewRowClient() {
    }


    public Number getEmrEmplId() {
        return (Number)getAttribute("EmrEmplId");
    }

    public Number getEmrRolId() {
        return (Number)getAttribute("EmrRolId");
    }

    public void setEmrEmplId(Number value) {
        setAttribute("EmrEmplId", value);
    }

    public void setEmrRolId(Number value) {
        setAttribute("EmrRolId", value);
    }
}
