package com.bawaweb.views.readable.client;

import com.bawaweb.views.readable.common.RprtReportsRViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RprtReportsRViewRowClient extends RowImpl implements RprtReportsRViewRow {
    /**This is the default constructor (do not remove)
     */
    public RprtReportsRViewRowClient() {
    }

    public RowIterator getOtlQuestionsRView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlQuestionsRView",null,null);
        return (RowIterator)_ret;
    }

    public RowIterator getOtlReportAnswerSetsRView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlReportAnswerSetsRView",null,null);
        return (RowIterator)_ret;
    }

    public RowIterator getOtlReportSortingCriteriaRView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlReportSortingCriteriaRView",null,null);
        return (RowIterator)_ret;
    }

    public RowIterator getOtlReportSourcesRView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlReportSourcesRView",null,null);
        return (RowIterator)_ret;
    }

    public Number getEdtrId() {
        return (Number)getAttribute("EdtrId");
    }

    public Number getFlashParent() {
        return (Number)getAttribute("FlashParent");
    }

    public Number getFridId() {
        return (Number)getAttribute("FridId");
    }

    public Number getIndrCode() {
        return (Number)getAttribute("IndrCode");
    }

    public String getIndustry() {
        return (String)getAttribute("Industry");
    }

    public Number getIsDeleted() {
        return (Number)getAttribute("IsDeleted");
    }

    public Number getIvstId() {
        return (Number)getAttribute("IvstId");
    }

    public Number getLastUpdateBy() {
        return (Number)getAttribute("LastUpdateBy");
    }

    public Date getLastUpdateDate() {
        return (Date)getAttribute("LastUpdateDate");
    }

    public Number getOldid() {
        return (Number)getAttribute("Oldid");
    }

    public Number getPanId() {
        return (Number)getAttribute("PanId");
    }

    public String getRprtAccuracyindex() {
        return (String)getAttribute("RprtAccuracyindex");
    }

    public Number getRprtAha() {
        return (Number)getAttribute("RprtAha");
    }

    public Date getRprtCompleteddate() {
        return (Date)getAttribute("RprtCompleteddate");
    }

    public String getRprtDesc() {
        return (String)getAttribute("RprtDesc");
    }

    public Date getRprtDuedate() {
        return (Date)getAttribute("RprtDuedate");
    }

    public Number getRprtFieldForceVisits() {
        return (Number)getAttribute("RprtFieldForceVisits");
    }

    public String getRprtGroupNotes() {
        return (String)getAttribute("RprtGroupNotes");
    }

    public String getRprtHideFromScheduleYn() {
        return (String)getAttribute("RprtHideFromScheduleYn");
    }

    public String getRprtHighlights() {
        return (String)getAttribute("RprtHighlights");
    }

    public String getRprtHitBonus() {
        return (String)getAttribute("RprtHitBonus");
    }

    public Number getRprtHoldSourceDist() {
        return (Number)getAttribute("RprtHoldSourceDist");
    }

    public Number getRprtId() {
        return (Number)getAttribute("RprtId");
    }

    public Number getRprtIdeaGenInd() {
        return (Number)getAttribute("RprtIdeaGenInd");
    }

    public Number getRprtImportanceRating() {
        return (Number)getAttribute("RprtImportanceRating");
    }

    public Date getRprtIntlDuedate() {
        return (Date)getAttribute("RprtIntlDuedate");
    }

    public Number getRprtIsclassified() {
        return (Number)getAttribute("RprtIsclassified");
    }

    public Number getRprtIscofocus() {
        return (Number)getAttribute("RprtIscofocus");
    }

    public Number getRprtIsproprietary() {
        return (Number)getAttribute("RprtIsproprietary");
    }

    public Number getRprtIssmallcap() {
        return (Number)getAttribute("RprtIssmallcap");
    }

    public String getRprtIsthumbsup() {
        return (String)getAttribute("RprtIsthumbsup");
    }

    public String getRprtLastisthumbsup() {
        return (String)getAttribute("RprtLastisthumbsup");
    }

    public Number getRprtLateRsched() {
        return (Number)getAttribute("RprtLateRsched");
    }

    public Date getRprtLaunchDate() {
        return (Date)getAttribute("RprtLaunchDate");
    }

    public String getRprtMktcap() {
        return (String)getAttribute("RprtMktcap");
    }

    public String getRprtNotes() {
        return (String)getAttribute("RprtNotes");
    }

    public Number getRprtParentId() {
        return (Number)getAttribute("RprtParentId");
    }

    public String getRprtPdf() {
        return (String)getAttribute("RprtPdf");
    }

    public String getRprtProdcode() {
        return (String)getAttribute("RprtProdcode");
    }

    public Number getRprtPropAppr() {
        return (Number)getAttribute("RprtPropAppr");
    }

    public Number getRprtPropCost() {
        return (Number)getAttribute("RprtPropCost");
    }

    public Number getRprtRdPerson() {
        return (Number)getAttribute("RprtRdPerson");
    }

    public Number getRprtRepeatSrcs() {
        return (Number)getAttribute("RprtRepeatSrcs");
    }

    public Date getRprtReportdate() {
        return (Date)getAttribute("RprtReportdate");
    }

    public String getRprtReportersViewAllYn() {
        return (String)getAttribute("RprtReportersViewAllYn");
    }

    public Date getRprtResearchin() {
        return (Date)getAttribute("RprtResearchin");
    }

    public Number getRprtRsmvId() {
        return (Number)getAttribute("RprtRsmvId");
    }

    public String getRprtSchedulingNotes() {
        return (String)getAttribute("RprtSchedulingNotes");
    }

    public String getRprtSourceDisplayField() {
        return (String)getAttribute("RprtSourceDisplayField");
    }

    public String getRprtSourceReport() {
        return (String)getAttribute("RprtSourceReport");
    }

    public Number getRprtSources() {
        return (Number)getAttribute("RprtSources");
    }

    public Date getRprtTopStoryOffDate() {
        return (Date)getAttribute("RprtTopStoryOffDate");
    }

    public Number getRpstId() {
        return (Number)getAttribute("RpstId");
    }

    public Number getRptrId() {
        return (Number)getAttribute("RptrId");
    }

    public Number getRtypId() {
        return (Number)getAttribute("RtypId");
    }

    public Number getScstId() {
        return (Number)getAttribute("ScstId");
    }

    public void setEdtrId(Number value) {
        setAttribute("EdtrId", value);
    }

    public void setFlashParent(Number value) {
        setAttribute("FlashParent", value);
    }

    public void setFridId(Number value) {
        setAttribute("FridId", value);
    }

    public void setIndrCode(Number value) {
        setAttribute("IndrCode", value);
    }

    public void setIndustry(String value) {
        setAttribute("Industry", value);
    }

    public void setIsDeleted(Number value) {
        setAttribute("IsDeleted", value);
    }

    public void setIvstId(Number value) {
        setAttribute("IvstId", value);
    }

    public void setLastUpdateBy(Number value) {
        setAttribute("LastUpdateBy", value);
    }

    public void setLastUpdateDate(Date value) {
        setAttribute("LastUpdateDate", value);
    }

    public void setOldid(Number value) {
        setAttribute("Oldid", value);
    }

    public void setPanId(Number value) {
        setAttribute("PanId", value);
    }

    public void setRprtAccuracyindex(String value) {
        setAttribute("RprtAccuracyindex", value);
    }

    public void setRprtAha(Number value) {
        setAttribute("RprtAha", value);
    }

    public void setRprtCompleteddate(Date value) {
        setAttribute("RprtCompleteddate", value);
    }

    public void setRprtDesc(String value) {
        setAttribute("RprtDesc", value);
    }

    public void setRprtDuedate(Date value) {
        setAttribute("RprtDuedate", value);
    }

    public void setRprtFieldForceVisits(Number value) {
        setAttribute("RprtFieldForceVisits", value);
    }

    public void setRprtGroupNotes(String value) {
        setAttribute("RprtGroupNotes", value);
    }

    public void setRprtHideFromScheduleYn(String value) {
        setAttribute("RprtHideFromScheduleYn", value);
    }

    public void setRprtHighlights(String value) {
        setAttribute("RprtHighlights", value);
    }

    public void setRprtHitBonus(String value) {
        setAttribute("RprtHitBonus", value);
    }

    public void setRprtHoldSourceDist(Number value) {
        setAttribute("RprtHoldSourceDist", value);
    }

    public void setRprtId(Number value) {
        setAttribute("RprtId", value);
    }

    public void setRprtIdeaGenInd(Number value) {
        setAttribute("RprtIdeaGenInd", value);
    }

    public void setRprtImportanceRating(Number value) {
        setAttribute("RprtImportanceRating", value);
    }

    public void setRprtIntlDuedate(Date value) {
        setAttribute("RprtIntlDuedate", value);
    }

    public void setRprtIsclassified(Number value) {
        setAttribute("RprtIsclassified", value);
    }

    public void setRprtIscofocus(Number value) {
        setAttribute("RprtIscofocus", value);
    }

    public void setRprtIsproprietary(Number value) {
        setAttribute("RprtIsproprietary", value);
    }

    public void setRprtIssmallcap(Number value) {
        setAttribute("RprtIssmallcap", value);
    }

    public void setRprtIsthumbsup(String value) {
        setAttribute("RprtIsthumbsup", value);
    }

    public void setRprtLastisthumbsup(String value) {
        setAttribute("RprtLastisthumbsup", value);
    }

    public void setRprtLateRsched(Number value) {
        setAttribute("RprtLateRsched", value);
    }

    public void setRprtLaunchDate(Date value) {
        setAttribute("RprtLaunchDate", value);
    }

    public void setRprtMktcap(String value) {
        setAttribute("RprtMktcap", value);
    }

    public void setRprtNotes(String value) {
        setAttribute("RprtNotes", value);
    }

    public void setRprtParentId(Number value) {
        setAttribute("RprtParentId", value);
    }

    public void setRprtPdf(String value) {
        setAttribute("RprtPdf", value);
    }

    public void setRprtProdcode(String value) {
        setAttribute("RprtProdcode", value);
    }

    public void setRprtPropAppr(Number value) {
        setAttribute("RprtPropAppr", value);
    }

    public void setRprtPropCost(Number value) {
        setAttribute("RprtPropCost", value);
    }

    public void setRprtRdPerson(Number value) {
        setAttribute("RprtRdPerson", value);
    }

    public void setRprtRepeatSrcs(Number value) {
        setAttribute("RprtRepeatSrcs", value);
    }

    public void setRprtReportdate(Date value) {
        setAttribute("RprtReportdate", value);
    }

    public void setRprtReportersViewAllYn(String value) {
        setAttribute("RprtReportersViewAllYn", value);
    }

    public void setRprtResearchin(Date value) {
        setAttribute("RprtResearchin", value);
    }

    public void setRprtRsmvId(Number value) {
        setAttribute("RprtRsmvId", value);
    }

    public void setRprtSchedulingNotes(String value) {
        setAttribute("RprtSchedulingNotes", value);
    }

    public void setRprtSourceDisplayField(String value) {
        setAttribute("RprtSourceDisplayField", value);
    }

    public void setRprtSourceReport(String value) {
        setAttribute("RprtSourceReport", value);
    }

    public void setRprtSources(Number value) {
        setAttribute("RprtSources", value);
    }

    public void setRprtTopStoryOffDate(Date value) {
        setAttribute("RprtTopStoryOffDate", value);
    }

    public void setRpstId(Number value) {
        setAttribute("RpstId", value);
    }

    public void setRptrId(Number value) {
        setAttribute("RptrId", value);
    }

    public void setRtypId(Number value) {
        setAttribute("RtypId", value);
    }

    public void setScstId(Number value) {
        setAttribute("ScstId", value);
    }
}
