package com.bawaweb.views.readable.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RptyReporterTypesRViewRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public RptyReporterTypesRViewRowClient() {
    }

    public String getRptyDesc() {
        return (String)getAttribute("RptyDesc");
    }

    public Number getRptyId() {
        return (Number)getAttribute("RptyId");
    }

    public void setRptyDesc(String value) {
        setAttribute("RptyDesc", value);
    }

    public void setRptyId(Number value) {
        setAttribute("RptyId", value);
    }
}
