package com.bawaweb.views.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DBInstanceRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public DBInstanceRowClient() {
    }


    public String getEdition() {
        return (String)getAttribute("Edition");
    }

    public void setEdition(String value) {
        setAttribute("Edition", value);
    }


    public String getActiveState() {
        return (String)getAttribute("ActiveState");
    }

    public String getArchiver() {
        return (String)getAttribute("Archiver");
    }

    public String getBlocked() {
        return (String)getAttribute("Blocked");
    }

    public String getDatabaseStatus() {
        return (String)getAttribute("DatabaseStatus");
    }

    public String getHostName() {
        return (String)getAttribute("HostName");
    }

    public String getInstanceName() {
        return (String)getAttribute("InstanceName");
    }

    public Number getInstanceNumber() {
        return (Number)getAttribute("InstanceNumber");
    }

    public String getInstanceRole() {
        return (String)getAttribute("InstanceRole");
    }

    public String getLogSwitchWait() {
        return (String)getAttribute("LogSwitchWait");
    }

    public String getLogins() {
        return (String)getAttribute("Logins");
    }

    public String getParallel() {
        return (String)getAttribute("Parallel");
    }

    public String getShutdownPending() {
        return (String)getAttribute("ShutdownPending");
    }

    public Date getStartupTime() {
        return (Date)getAttribute("StartupTime");
    }

    public String getStatus() {
        return (String)getAttribute("Status");
    }

    public Number getThread() {
        return (Number)getAttribute("Thread");
    }

    public String getVersion() {
        return (String)getAttribute("Version");
    }

    public void setActiveState(String value) {
        setAttribute("ActiveState", value);
    }

    public void setArchiver(String value) {
        setAttribute("Archiver", value);
    }

    public void setBlocked(String value) {
        setAttribute("Blocked", value);
    }

    public void setDatabaseStatus(String value) {
        setAttribute("DatabaseStatus", value);
    }

    public void setHostName(String value) {
        setAttribute("HostName", value);
    }

    public void setInstanceName(String value) {
        setAttribute("InstanceName", value);
    }

    public void setInstanceNumber(Number value) {
        setAttribute("InstanceNumber", value);
    }

    public void setInstanceRole(String value) {
        setAttribute("InstanceRole", value);
    }

    public void setLogSwitchWait(String value) {
        setAttribute("LogSwitchWait", value);
    }

    public void setLogins(String value) {
        setAttribute("Logins", value);
    }

    public void setParallel(String value) {
        setAttribute("Parallel", value);
    }

    public void setShutdownPending(String value) {
        setAttribute("ShutdownPending", value);
    }

    public void setStartupTime(Date value) {
        setAttribute("StartupTime", value);
    }

    public void setStatus(String value) {
        setAttribute("Status", value);
    }

    public void setThread(Number value) {
        setAttribute("Thread", value);
    }

    public void setVersion(String value) {
        setAttribute("Version", value);
    }
}
