package com.bawaweb.views.identify.client;

import com.bawaweb.views.identify.common.GetBestSourceId;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GetBestSourceIdClient extends ViewUsageImpl implements GetBestSourceId {
    /**This is the default constructor (do not remove)
     */
    public GetBestSourceIdClient() {
    }


    public long getEstimatedRowCount() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getEstimatedRowCount",null,null);
        return ((Long)_ret).longValue();
    }

    public String getlist_ids() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getlist_ids",null,null);
        return (String)_ret;
    }

    public void setlist_ids(String value) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setlist_ids",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
}
