package com.bawaweb.views.identify.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReportLockInfoRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public ReportLockInfoRowClient() {
    }


    public Number getOtlId() {
        return (Number)getAttribute("OtlId");
    }

    public void setOtlId(Number value) {
        setAttribute("OtlId", value);
    }

    public String getOtlTabName() {
        return (String)getAttribute("OtlTabName");
    }

    public void setOtlTabName(String value) {
        setAttribute("OtlTabName", value);
    }

    public Number getOtlTabId() {
        return (Number)getAttribute("OtlTabId");
    }

    public void setOtlTabId(Number value) {
        setAttribute("OtlTabId", value);
    }

    public String getOtlEmplId() {
        return (String)getAttribute("OtlEmplId");
    }

    public void setOtlEmplId(String value) {
        setAttribute("OtlEmplId", value);
    }

    public Date getOtlCreatedDt() {
        return (Date)getAttribute("OtlCreatedDt");
    }

    public void setOtlCreatedDt(Date value) {
        setAttribute("OtlCreatedDt", value);
    }

    public String getOtlStatus() {
        return (String)getAttribute("OtlStatus");
    }

    public void setOtlStatus(String value) {
        setAttribute("OtlStatus", value);
    }
}
