package com.bawaweb.views.readable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface CtryCountriesRView extends ViewObject {
    long getEstimatedRowCount();

    Number getctry_id();

    void setctry_id(Number value);
}
