package com.bawaweb.views.readable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlFunctionsRView extends ViewObject {
    long getEstimatedRowCount();

    Number getfnc_id();

    void setfnc_id(Number value);
}
