package com.bawaweb.views.readable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlQuestionsRView extends ViewObject {
    Number getqst_id();

    void setqst_id(Number value);

    long getEstimatedRowCount();
}
