package com.bawaweb.views.readable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlSourceSortingCriteriaRView extends ViewObject {
    long getEstimatedRowCount();

    Number getssc_rps_id();

    void setssc_rps_id(Number value);
}
