package com.bawaweb.views.readable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlSortingCriteriaRView extends ViewObject {
    long getEstimatedRowCount();

    Number getsrt_id();

    void setsrt_id(Number value);
}
