package com.bawaweb.views.readable.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtlSourceSortingCriteriaRViewRow extends Row {
    Number getSscRpsId();

    Number getSscScvId();

    void setSscRpsId(Number value);

    void setSscScvId(Number value);
}
