package com.bawaweb.views.readable.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface OtrTabLocksRViewRow extends Row {
    Date getOtlCreatedDt();

    String getOtlEmplId();

    Number getOtlId();

    Number getOtlTabId();

    String getOtlTabName();

    void setOtlCreatedDt(Date value);

    void setOtlEmplId(String value);

    void setOtlId(Number value);

    void setOtlTabId(Number value);

    void setOtlTabName(String value);
}
