package com.bawaweb.views.readable.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface RprtReportReporterXrefRView extends ViewObject {
    long getEstimatedRowCount();

    Number getrprt_id();

    void setrprt_id(Number value);
}
