package com.bawaweb.views.readable.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface RptyReporterTypesRViewRow extends Row {
    String getRptyDesc();

    Number getRptyId();

    void setRptyDesc(String value);

    void setRptyId(Number value);
}
