package com.bawaweb.views.updatable.client;

import com.bawaweb.views.updatable.common.OtlAnswerSetValuesUViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlAnswerSetValuesUViewRowClient extends RowImpl implements OtlAnswerSetValuesUViewRow {
    /**This is the default constructor (do not remove)
     */
    public OtlAnswerSetValuesUViewRowClient() {
    }

    public RowIterator getOtlReportAnswerSetValuesUView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlReportAnswerSetValuesUView",null,null);
        return (RowIterator)_ret;
    }

    public RowIterator getOtlSourceAnswersUView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlSourceAnswersUView",null,null);
        return (RowIterator)_ret;
    }

    public RowIterator getOtlSourceMultiAnswersUView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getOtlSourceMultiAnswersUView",null,null);
        return (RowIterator)_ret;
    }

    public Number getAsvAnsId() {
        return (Number)getAttribute("AsvAnsId");
    }

    public String getAsvAnswer() {
        return (String)getAttribute("AsvAnswer");
    }

    public String getAsvDeleteYn() {
        return (String)getAttribute("AsvDeleteYn");
    }

    public Number getAsvDisplaySeq() {
        return (Number)getAttribute("AsvDisplaySeq");
    }

    public Number getAsvId() {
        return (Number)getAttribute("AsvId");
    }

    public void setAsvAnsId(Number value) {
        setAttribute("AsvAnsId", value);
    }

    public void setAsvAnswer(String value) {
        setAttribute("AsvAnswer", value);
    }

    public void setAsvDeleteYn(String value) {
        setAttribute("AsvDeleteYn", value);
    }

    public void setAsvDisplaySeq(Number value) {
        setAttribute("AsvDisplaySeq", value);
    }

    public void setAsvId(Number value) {
        setAttribute("AsvId", value);
    }
}
