package com.bawaweb.views.updatable.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlSourceSortingCriteriaUViewRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public OtlSourceSortingCriteriaUViewRowClient() {
    }

    public Number getSscRpsId() {
        return (Number)getAttribute("SscRpsId");
    }

    public Number getSscScvId() {
        return (Number)getAttribute("SscScvId");
    }

    public void setSscRpsId(Number value) {
        setAttribute("SscRpsId", value);
    }

    public void setSscScvId(Number value) {
        setAttribute("SscScvId", value);
    }
}
