package com.bawaweb.views.updatable.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtlSourceMultiAnswersUViewRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public OtlSourceMultiAnswersUViewRowClient() {
    }

    public String getSmaAnswer() {
        return (String)getAttribute("SmaAnswer");
    }

    public Number getSmaAsvId() {
        return (Number)getAttribute("SmaAsvId");
    }

    public String getSmaExcludeYn() {
        return (String)getAttribute("SmaExcludeYn");
    }

    public Number getSmaQmqId() {
        return (Number)getAttribute("SmaQmqId");
    }

    public Number getSmaRavId() {
        return (Number)getAttribute("SmaRavId");
    }

    public Number getSmaSraId() {
        return (Number)getAttribute("SmaSraId");
    }

    public Number getSmaWeightMultiplier() {
        return (Number)getAttribute("SmaWeightMultiplier");
    }

    public void setSmaAnswer(String value) {
        setAttribute("SmaAnswer", value);
    }

    public void setSmaAsvId(Number value) {
        setAttribute("SmaAsvId", value);
    }

    public void setSmaExcludeYn(String value) {
        setAttribute("SmaExcludeYn", value);
    }

    public void setSmaQmqId(Number value) {
        setAttribute("SmaQmqId", value);
    }

    public void setSmaRavId(Number value) {
        setAttribute("SmaRavId", value);
    }

    public void setSmaSraId(Number value) {
        setAttribute("SmaSraId", value);
    }

    public void setSmaWeightMultiplier(Number value) {
        setAttribute("SmaWeightMultiplier", value);
    }
}
