package com.bawaweb.views.updatable.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.RowID;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtrEmployeeInfoUViewRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public OtrEmployeeInfoUViewRowClient() {
    }


    public String getAdditionalExpertise() {
        return (String)getAttribute("AdditionalExpertise");
    }

    public String getCountry() {
        return (String)getAttribute("Country");
    }

    public String getCovers() {
        return (String)getAttribute("Covers");
    }

    public String getDepartment() {
        return (String)getAttribute("Department");
    }

    public String getFirstName() {
        return (String)getAttribute("FirstName");
    }

    public String getLastName() {
        return (String)getAttribute("LastName");
    }

    public String getLongBio() {
        return (String)getAttribute("LongBio");
    }

    public String getOtrSince() {
        return (String)getAttribute("OtrSince");
    }

    public String getRegion() {
        return (String)getAttribute("Region");
    }

    public String getReportsTo() {
        return (String)getAttribute("ReportsTo");
    }

    public RowID getRowID() {
        return (RowID)getAttribute("RowID");
    }

    public String getSectors() {
        return (String)getAttribute("Sectors");
    }

    public String getShortBio() {
        return (String)getAttribute("ShortBio");
    }

    public String getTitle() {
        return (String)getAttribute("Title");
    }

    public void setAdditionalExpertise(String value) {
        setAttribute("AdditionalExpertise", value);
    }

    public void setCountry(String value) {
        setAttribute("Country", value);
    }

    public void setCovers(String value) {
        setAttribute("Covers", value);
    }

    public void setDepartment(String value) {
        setAttribute("Department", value);
    }

    public void setFirstName(String value) {
        setAttribute("FirstName", value);
    }

    public void setLastName(String value) {
        setAttribute("LastName", value);
    }

    public void setLongBio(String value) {
        setAttribute("LongBio", value);
    }

    public void setOtrSince(String value) {
        setAttribute("OtrSince", value);
    }

    public void setRegion(String value) {
        setAttribute("Region", value);
    }

    public void setReportsTo(String value) {
        setAttribute("ReportsTo", value);
    }

    public void setSectors(String value) {
        setAttribute("Sectors", value);
    }

    public void setShortBio(String value) {
        setAttribute("ShortBio", value);
    }

    public void setTitle(String value) {
        setAttribute("Title", value);
    }
}
