package com.bawaweb.views.updatable.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RprtReportReporterXrefUViewRowClient extends RowImpl {
    /**This is the default constructor (do not remove)
     */
    public RprtReportReporterXrefUViewRowClient() {
    }

    public String getDistributionNotes() {
        return (String)getAttribute("DistributionNotes");
    }

    public RowID getRowID() {
        return (RowID)getAttribute("RowID");
    }

    public Number getRprtId() {
        return (Number)getAttribute("RprtId");
    }

    public Number getRptrId() {
        return (Number)getAttribute("RptrId");
    }

    public Number getRptyId() {
        return (Number)getAttribute("RptyId");
    }

    public void setDistributionNotes(String value) {
        setAttribute("DistributionNotes", value);
    }

    public void setRprtId(Number value) {
        setAttribute("RprtId", value);
    }

    public void setRptrId(Number value) {
        setAttribute("RptrId", value);
    }

    public void setRptyId(Number value) {
        setAttribute("RptyId", value);
    }
}
