package com.bawaweb.views.updatable.client;

import com.bawaweb.views.updatable.common.RtypReportTypesUViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RtypReportTypesUViewRowClient extends RowImpl implements RtypReportTypesUViewRow {
    /**This is the default constructor (do not remove)
     */
    public RtypReportTypesUViewRowClient() {
    }

    public RowIterator getRprtReportsUView() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getRprtReportsUView",null,null);
        return (RowIterator)_ret;
    }

    public String getRtypDesc() {
        return (String)getAttribute("RtypDesc");
    }

    public Number getRtypDisplaySeq() {
        return (Number)getAttribute("RtypDisplaySeq");
    }

    public Number getRtypId() {
        return (Number)getAttribute("RtypId");
    }

    public Number getRtypInterviewDays() {
        return (Number)getAttribute("RtypInterviewDays");
    }

    public String getRtypLimitNumber() {
        return (String)getAttribute("RtypLimitNumber");
    }

    public Number getRtypTallyDays() {
        return (Number)getAttribute("RtypTallyDays");
    }

    public void setRtypDesc(String value) {
        setAttribute("RtypDesc", value);
    }

    public void setRtypDisplaySeq(Number value) {
        setAttribute("RtypDisplaySeq", value);
    }

    public void setRtypId(Number value) {
        setAttribute("RtypId", value);
    }

    public void setRtypInterviewDays(Number value) {
        setAttribute("RtypInterviewDays", value);
    }

    public void setRtypLimitNumber(String value) {
        setAttribute("RtypLimitNumber", value);
    }

    public void setRtypTallyDays(Number value) {
        setAttribute("RtypTallyDays", value);
    }
}
