package com.bawaweb.views.utils;

import com.bawaweb.model.OtlCourtesyTitlesImpl;

import com.bawaweb.views.utils.common.CourtesyTitlesRow;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CourtesyTitlesRowImpl extends ViewRowImpl implements CourtesyTitlesRow {
    public static final int CTLCODE = 0;
    public static final int CTLDESC = 1;
    public static final int CTLCOURTESYTITLE = 2;
    public static final int CTLDELETEYN = 3;

    /**This is the default constructor (do not remove)
     */
    public CourtesyTitlesRowImpl() {
    }

    /**Gets OtlCourtesyTitles entity object.
     */
    public OtlCourtesyTitlesImpl getOtlCourtesyTitles() {
        return (OtlCourtesyTitlesImpl)getEntity(0);
    }

    /**Gets the attribute value for the calculated attribute CtlCode
     */
    public String getCtlCode() {
        return (String) getAttributeInternal(CTLCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CtlCode
     */
    public void setCtlCode(String value) {
        setAttributeInternal(CTLCODE, value);
    }

    /**Gets the attribute value for the calculated attribute CtlDesc
     */
    public String getCtlDesc() {
        return (String) getAttributeInternal(CTLDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CtlDesc
     */
    public void setCtlDesc(String value) {
        setAttributeInternal(CTLDESC, value);
    }

    /**Gets the attribute value for the calculated attribute CtlCourtesyTitle
     */
    public String getCtlCourtesyTitle() {
        return (String) getAttributeInternal(CTLCOURTESYTITLE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CtlCourtesyTitle
     */
    public void setCtlCourtesyTitle(String value) {
        setAttributeInternal(CTLCOURTESYTITLE, value);
    }

    /**Gets the attribute value for the calculated attribute CtlDeleteYn
     */
    public String getCtlDeleteYn() {
        return (String) getAttributeInternal(CTLDELETEYN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CtlDeleteYn
     */
    public void setCtlDeleteYn(String value) {
        setAttributeInternal(CTLDELETEYN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CTLCODE:
            return getCtlCode();
        case CTLDESC:
            return getCtlDesc();
        case CTLCOURTESYTITLE:
            return getCtlCourtesyTitle();
        case CTLDELETEYN:
            return getCtlDeleteYn();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CTLCODE:
            setCtlCode((String)value);
            return;
        case CTLDESC:
            setCtlDesc((String)value);
            return;
        case CTLCOURTESYTITLE:
            setCtlCourtesyTitle((String)value);
            return;
        case CTLDELETEYN:
            setCtlDeleteYn((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
