package com.bawaweb.views.identify;

import com.bawaweb.model.OtlAnswerSetValuesImpl;
import com.bawaweb.model.OtlAnswerSetsImpl;
import com.bawaweb.model.OtlQuestionsImpl;

import com.bawaweb.model.OtlReportAnswerSetsImpl;
import com.bawaweb.views.identify.common.ExtraQstnsAnswerSetValuesRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExtraQstnsAnswerSetValuesRowImpl extends ViewRowImpl implements ExtraQstnsAnswerSetValuesRow {
    public static final int QSTID = 0;
    public static final int QSTRASID = 1;
    public static final int ASVID = 2;
    public static final int ASVANSID = 3;
    public static final int ASVANSWER = 4;
    public static final int ASVDISPLAYSEQ = 5;
    public static final int ASVDELETEYN = 6;
    public static final int ANSID = 7;
    public static final int QSTANSID = 8;

    /**This is the default constructor (do not remove)
     */
    public ExtraQstnsAnswerSetValuesRowImpl() {
    }

    /**Gets OtlQuestions entity object.
     */
    public OtlQuestionsImpl getOtlQuestions() {
        return (OtlQuestionsImpl)getEntity(0);
    }

    /**Gets OtlAnswerSets entity object.
     */
    public OtlAnswerSetsImpl getOtlAnswerSets() {
        return (OtlAnswerSetsImpl)getEntity(1);
    }

    /**Gets OtlAnswerSetValues entity object.
     */
    public OtlAnswerSetValuesImpl getOtlAnswerSetValues() {
        return (OtlAnswerSetValuesImpl)getEntity(2);
    }

    /**Gets the attribute value for QST_ID using the alias name QstId
     */
    public Number getQstId() {
        return (Number) getAttributeInternal(QSTID);
    }

    /**Sets <code>value</code> as attribute value for QST_ID using the alias name QstId
     */
    public void setQstId(Number value) {
        setAttributeInternal(QSTID, value);
    }

    /**Gets the attribute value for QST_RAS_ID using the alias name QstRasId
     */
    public Number getQstRasId() {
        return (Number) getAttributeInternal(QSTRASID);
    }

    /**Sets <code>value</code> as attribute value for QST_RAS_ID using the alias name QstRasId
     */
    public void setQstRasId(Number value) {
        setAttributeInternal(QSTRASID, value);
    }

    /**Gets the attribute value for ASV_ID using the alias name AsvId
     */
    public Number getAsvId() {
        return (Number) getAttributeInternal(ASVID);
    }

    /**Sets <code>value</code> as attribute value for ASV_ID using the alias name AsvId
     */
    public void setAsvId(Number value) {
        setAttributeInternal(ASVID, value);
    }

    /**Gets the attribute value for ASV_ANS_ID using the alias name AsvAnsId
     */
    public Number getAsvAnsId() {
        return (Number) getAttributeInternal(ASVANSID);
    }

    /**Sets <code>value</code> as attribute value for ASV_ANS_ID using the alias name AsvAnsId
     */
    public void setAsvAnsId(Number value) {
        setAttributeInternal(ASVANSID, value);
    }

    /**Gets the attribute value for ASV_ANSWER using the alias name AsvAnswer
     */
    public String getAsvAnswer() {
        return (String) getAttributeInternal(ASVANSWER);
    }

    /**Sets <code>value</code> as attribute value for ASV_ANSWER using the alias name AsvAnswer
     */
    public void setAsvAnswer(String value) {
        setAttributeInternal(ASVANSWER, value);
    }

    /**Gets the attribute value for ASV_DISPLAY_SEQ using the alias name AsvDisplaySeq
     */
    public Number getAsvDisplaySeq() {
        return (Number) getAttributeInternal(ASVDISPLAYSEQ);
    }

    /**Sets <code>value</code> as attribute value for ASV_DISPLAY_SEQ using the alias name AsvDisplaySeq
     */
    public void setAsvDisplaySeq(Number value) {
        setAttributeInternal(ASVDISPLAYSEQ, value);
    }

    /**Gets the attribute value for ASV_DELETE_YN using the alias name AsvDeleteYn
     */
    public String getAsvDeleteYn() {
        return (String) getAttributeInternal(ASVDELETEYN);
    }

    /**Sets <code>value</code> as attribute value for ASV_DELETE_YN using the alias name AsvDeleteYn
     */
    public void setAsvDeleteYn(String value) {
        setAttributeInternal(ASVDELETEYN, value);
    }

    /**Gets the attribute value for ANS_ID using the alias name AnsId
     */
    public Number getAnsId() {
        return (Number) getAttributeInternal(ANSID);
    }

    /**Sets <code>value</code> as attribute value for ANS_ID using the alias name AnsId
     */
    public void setAnsId(Number value) {
        setAttributeInternal(ANSID, value);
    }

    /**Gets the attribute value for QST_ANS_ID using the alias name QstAnsId
     */
    public Number getQstAnsId() {
        return (Number) getAttributeInternal(QSTANSID);
    }

    /**Sets <code>value</code> as attribute value for QST_ANS_ID using the alias name QstAnsId
     */
    public void setQstAnsId(Number value) {
        setAttributeInternal(QSTANSID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case QSTID:
            return getQstId();
        case QSTRASID:
            return getQstRasId();
        case ASVID:
            return getAsvId();
        case ASVANSID:
            return getAsvAnsId();
        case ASVANSWER:
            return getAsvAnswer();
        case ASVDISPLAYSEQ:
            return getAsvDisplaySeq();
        case ASVDELETEYN:
            return getAsvDeleteYn();
        case ANSID:
            return getAnsId();
        case QSTANSID:
            return getQstAnsId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case QSTID:
            setQstId((Number)value);
            return;
        case QSTRASID:
            setQstRasId((Number)value);
            return;
        case ASVID:
            setAsvId((Number)value);
            return;
        case ASVANSID:
            setAsvAnsId((Number)value);
            return;
        case ASVANSWER:
            setAsvAnswer((String)value);
            return;
        case ASVDISPLAYSEQ:
            setAsvDisplaySeq((Number)value);
            return;
        case ASVDELETEYN:
            setAsvDeleteYn((String)value);
            return;
        case ANSID:
            setAnsId((Number)value);
            return;
        case QSTANSID:
            setQstAnsId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets OtlReportAnswerSets entity object.
     */
    public OtlReportAnswerSetsImpl getOtlReportAnswerSets() {
        return (OtlReportAnswerSetsImpl)getEntity(3);
    }
}
