package com.bawaweb.views.identify;

import com.bawaweb.views.identify.common.GetBestSourceId;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GetBestSourceIdImpl extends ViewObjectImpl implements GetBestSourceId {
    /**This is the default constructor (do not remove)
     */
    public GetBestSourceIdImpl() {
    }

    /**Gets the bind variable value for list_ids
     */
    public String getlist_ids() {
        return (String)getNamedWhereClauseParam("list_ids");
    }

    /**Sets <code>value</code> for bind variable list_ids
     */
    public void setlist_ids(String value) {
        setNamedWhereClauseParam("list_ids", value);
    }

    /**executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object params[], int noUserParams) {super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc, 
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**getEstimatedRowCount - overridden for custom java data source support.
     */
    public long getEstimatedRowCount() {
        long value = super.getEstimatedRowCount();
        return value;
    }
}
