package com.bawaweb.views.identify;

import com.bawaweb.views.identify.common.MaxRavIdRow;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MaxRavIdRowImpl extends ViewRowImpl implements MaxRavIdRow {


    public static final int MAXRAVID = 0;

    /**This is the default constructor (do not remove)
     */
    public MaxRavIdRowImpl() {
    }

    /**Gets the attribute value for the calculated attribute MaxRavId
     */
    public Number getMaxRavId() {
        return (Number) getAttributeInternal(MAXRAVID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MaxRavId
     */
    public void setMaxRavId(Number value) {
        setAttributeInternal(MAXRAVID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case MAXRAVID:
            return getMaxRavId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
