package com.bawaweb.views.identify.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface AddAnswerSetForQstnRow extends Row {

    String getRasAddAnswerYn();

    void setRasAddAnswerYn(String value);
}
