package com.bawaweb.views.identify.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface ASVAnswerValuesRow extends Row {
    String getAsvAnswer();

    void setAsvAnswer(String value);

    Number getAsvId();

    void setAsvId(Number value);
}
