package com.bawaweb.views.identify.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface GetBestSourceId extends ViewObject {
    long getEstimatedRowCount();

    String getlist_ids();

    void setlist_ids(String value);
}
