package com.bawaweb.views.identify.common;

import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface GetErrXLFileInfoRow extends Row {
    BlobDomain getAgefFile();

    String getAgefFileFormatType();

    String getAgefFileName();

    Number getAgefId();

    Number getAgefRprtId();

    String getCreatedBy();

    Date getCreationDate();

    void setAgefFile(BlobDomain value);

    void setAgefFileFormatType(String value);

    void setAgefFileName(String value);

    void setAgefId(Number value);

    void setAgefRprtId(Number value);

    void setCreatedBy(String value);

    void setCreationDate(Date value);
}
