package com.bawaweb.views.identify.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface MaxAsvId extends ViewObject {
    long getEstimatedRowCount();
}
