package com.bawaweb.views.identify.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface MaxRpsIdRow extends Row {
    Number getMaxRpsId();

    void setMaxRpsId(Number value);
}
