package com.bawaweb.views.identify.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface RAVInfoRow extends Row {
    Number getRavId();

    void setRavId(Number value);

    Number getRavRasId();

    void setRavRasId(Number value);

    String getRavAnswer();

    void setRavAnswer(String value);

    Number getRavDisplaySeq();

    void setRavDisplaySeq(Number value);

    Number getRavAsvId();

    void setRavAsvId(Number value);

    String getRavDeleteYn();

    void setRavDeleteYn(String value);
}
