package com.bawaweb.views.identify.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface SSCInfo extends ViewObject {
    long getEstimatedRowCount();

    String getanswer();

    Number getqst_id();

    void setanswer(String value);

    void setqst_id(Number value);
}
